NeoRazorX/facturascripts

Core/Base/DataBase.php, Core/Base/DataBase/DataBaseUtils.php, Core/Base/DataBase/Mysql.php, Core/Base/DataBase/Postgresql.php, Core/Base/IPFilter.php, Core/Base/Model.php, Core/Base/Utils.php, Core/Model/Agente.php, Core/Model/Almacen.php, Core/Model/Divisa.php, Core/Model/Ejercicio.php, Core/Model/FormaPago.php, Core/Model/Page.php, Core/Model/Pais.php, Core/Model/Serie.php
- Reemplazada comparación estricta en donde es posible hacerlo
- Reemplazados intval($x) por (int)$x, supuestamente es x6 más rápido
=> Varios reemplazos recomendados por PHP Code Sniffer

Core/Base/DataBase/Mysql.php
Ocultar warning si falla conexión de base de datos y capturar texto de error
=> Evitar que aparezca warning si falla la conexión

Core/View/Dashboard.html
Se realizó el cambio de diseño del dashboard de col-3 a card-columns agregando 10px de padding lateral para despegar las tarjetas de los margenes left y right
=> FS2018: Cambiar diseño de dashboard de col-3 a card-columns

Core/Base/Cache/APCAdapter.php, Core/Base/Cache/AdaptorInterface.php, Core/Base/Cache/FileCache.php, Core/Base/Cache/MemcacheAdapter.php
- APCAdapter: better code for get/set/clear (now works)
=> PHPBlocks translations for Core/Base/Cache.

Core/Controller/AdminHome.php, Core/View/AdminHome.html
- Control actions on execAction with var action.
- Add support to check if facturascripts.ini exists on plugin zip.
- Add support to check if name exists in facturascripts.ini to rename (if needed) the plugin to the correct folder.
- Enable support for delete also files on delTree (if a file was extracted from plugin zip to plugins folder by error, is not happening, but can occur).
=> Some changes on AdminHome for manage plugin actions and some new checks

Core/Controller/EditProveedor.php, Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditAlbaranProveedor.xml, Core/XMLView/EditFacturaProveedor.xml, Core/XMLView/EditProveedorArticulo.xml
listView, no EditListView. Y se debe modificar editProveedorArticulo.xml 
para mostrar los resultados como en un listado, es decir, sin grupos.
Añadir todas las columnas faltantes a editFacturaProveedor.xml, 
como está en editAlbaranCliente.xml 
(a excepción de las direcciones de envío y facturación
Añadir todas las columnas faltantes a editAlbaranProveedor.xml, 
como está en editAlbaranCliente.xml 
(a excepción de las direcciones de envío y facturación)
=> En el controlador EditProveedor, la vista de artículos debe ser

Core/Controller/DocumentReports.php, Core/View/DocumentReports.html, Core/View/Macro/Forms.html
Change the Form Macros so that i18n is not a parameter (strings should
be translated before), simpleSelect now works with associative arrays
instead of indexed ones and the class attribute can be fully overriden (
no form-control class is added when overriding with the attributes 
parameter).
Updated DocumentReports.php and DocumentReports.html to work with the
new changes.
=> Update Form macros to have simpleSelect receive associative arrays and remove i18n var from inputs and selects

Core/Base/ExtendedController/EditController.php, Core/Base/ExtendedController/PanelController.php, Core/Base/ExtendedController/RowItem.php, Core/Base/ExtendedController/RowItemCards.php, Core/Model/Agente.php, Core/Model/Base/ModelTrait.php, Core/View/DocumentReports.html, Core/View/Macro/BaseController.html, Core/View/Master/DocumentController.html, Core/View/Master/EditController.html, Core/View/Master/ListController.html, Core/View/Master/PanelController.html, Core/View/Master/PanelControllerBottom.html, Core/View/Master/PanelControllerTop.html, Core/XMLView/EditCliente.xml, Core/XMLView/SettingsEmail.xml, Documentation/EN/EditController.rst, Documentation/EN/Models.rst, Documentation/EN/XMLViews.rst, Documentation/ES/EditController.rst, Documentation/ES/Models.rst, Documentation/ES/XMLViews.rst, Test/Core/Model/AgenteTest.php
The "head" type rows now become "statistics" type, keeping their operation unchanged.
The RowItemFooter class is renamed by RowItemCards more in line with its new function.
A new "head" type is added to the RowItemCards, similar to the existing ones ("footer") but which are displayed in the header of the views.
=> Added information panels in the view header

.gitignore, bin/phpunit, composer.json, config/services_test.yaml, phpunit.xml.dist
Deprecate raw use of phpunit and use Symfony phpunit bridge for testing
=> <feature> Use Symfony phpunit bridge for tests

Core/App/AppController.php, Core/Base/Controller.php, Core/Base/PluginManager.php, Core/Controller/AccountingReports.php, Core/Controller/AdminHome.php, Core/Controller/Dashboard.php, Core/Controller/DocumentReports.php, Core/Controller/EditEjercicio.php, Core/Controller/EditPageOption.php, Core/Controller/EditRole.php, Core/Controller/EditSettings.php, Core/Controller/ListAsiento.php, Core/Controller/Randomizer.php, Core/Lib/ExtendedController/DocumentController.php, Core/Lib/ExtendedController/EditController.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/PanelController.php
This PR avoid the param minilog in controllers or extended controllers and it uses the injected logger via symfony monolog bridge service. 
Note: Future PR should affect to othe parts that still use the old Minilog class. For models shouldn't have logs or logic for the logger and throw exceptions instead to upper controllers.
=> Force to use PSR3 monolog logger

composer.json
When do:
- composer install, also is auto-called to npm install.
- composer update, also is auto-called to npm update.
Doing something like that at the end of composer execution:
> npm update
Only for test, for users that maybe hasn't all dependecies installed on system, they can see a message like that:
> non-existing-command
sh: non-existing-command: command not found
Script non-existing-command handling the post-update-cmd event returned with error code 127
Replace 'non-existing-command' for any binary call, including the npm added here.
=> Add support for custom commands in composer

Core/Lib/ExtendedController/WidgetItemAutocomplete.php, Core/View/Macro/DocumentController.html.twig, Core/View/Macro/ListFilter.html.twig, Core/View/Master/ListController.html.twig, Core/View/MegaSearch.html.twig
- Replaced input-group-btn with input-group-prepend (According to https://getbootstrap.com/docs/4.0/migration/#input-groups)
=> Fixes visual glitches on some BS components.

CONTRIBUTING.md
As described in [Trello task 288](https://trello.com/c/OpsR7IQL/288-actualizar-contributingmd-más-info-dentro).
Also includes some fixes to misspellings, an a possible way to use branches (only described, not suggested).
=> Added new guidelines to contributing guide.

Core/Lib/RandomDataGenerator/Subcuentas.php
The Subcuentas generator fails because the codsubcuenta field needs an exact length that is setted in the Accounting Year Model.
In the Randomizer::Subcuentas controller has been added a call to the Model\Ejercicio and generated the codsubcuenta inside a str_pad filling with zeros the number to match the length.
=> fs2018: Fix Randomizer::Subcuentas generator

Core/Lib/ExtendedController/WidgetItemSelect.php
The automatic loading of values from a table in the database failed because a item was added to the array of values before processing the "auto values". The component expects that in the first element of the array of values are the data necessary to obtain the "auto values". The load of this new item is moved to after the auto charge.
=> Fix WidgetSelect auto load options

Core/View/Macro/BaseController.html.twig
The delete button was visible when it was high.
Html code is not applied if there are no statistical buttons.
=> FIX delete Button and Statistics Margin

Core/App/AppAPI.php, Core/Model/ApiKey.php
This PR implements the [trello issue 94](https://trello.com/c/6OZb8ttJ/94-a%C3%B1adir-autenticaci%C3%B3n-a-la-api-archivo-core-app-appapiphp). A basic authentication via header "Token" and respecting if the api key is enabled or not.
FYI: The idea and if it gets accepted in the future could be use the Security Firewall from Symfony and the API authentication
https://symfony.com/doc/current/security/api_key_authentication.html
For testing:
The token is "hola" in md5. Could be whatever string that you want.
`
INSERT INTO api_keys VALUES(1, '916f4c31aaa35d6b867dae9a7f54270d', 'Prueba', 1, NOW(), 'shakaran');`
```
mysql> select * from api_keys;
+----+----------------------------------+-------------+---------+--------------+----------+
| id | apikey                           | description | …
```
=> Implement authentication via token for API. Trello Issue 94

Core/Translation/ca_ES.json, Core/Translation/en_EN.json, Core/Translation/en_US.json, Core/Translation/es_ES.json, Core/XMLView/EditAgente.xml, Core/XMLView/ListImpuesto.xml
The '%' symbol is changed to 'percentage' text to avoid errors and confusion with the variables that use the same symbol in their declaration.
=>  Translated using Weblate and  Change '%' into name per 'percentage'

Test/Core/Translation/TranslationTest.php, phpunit.xml
- Check that all files have well format
> Prepared tests but disabled from now:
> - Look for waste keys on all files comparing to en_EN
> - Verify that JSON are keys sorted
> 
**Note:** This is the sample suggested [here](https://github.com/NeoRazorX/facturascripts/pull/407)
- `Added` (non-breaking change which adds functionality)
=> Added Tests related to JSON translation files (Trello task 340)

Core/App/AppAPI.php, Core/Lib/API/APIModel.php, Core/Lib/API/Base/APIResourceClass.php, Core/Lib/API/Calculate.php
The model API is extracted and a general-purpose generic kernel is created.
=> Refactoring the API library

Core/Base/FileManager.php, Core/Base/IntegrityCheck.php, Core/Controller/IntegritySystemCheck.php, Core/Translation/en_EN.json, Core/View/IntegritySystemCheck.html.twig, Test/Core/Base/IntegrityCheckTest.php
- Can save and load integrity files from/to json file with file => hash options on MyFiles folder
- Compare system and user looking for missing files, invalid hashes and extra files
- Innitial tests for this class
- Updated: FileManager::scanFolder to allow pass a different exclude list than the default, needed to ignore some files and folders
=> Added support to check integrity of the FS installation files

Core/Base/DataBase.php
The return type has been added to the connection methods of the DataBase class. Now these methods are strong typing.
=> Add return type to connection method

Core/Lib/ExtendedController/RowItemStatus.php, Core/View/Macro/BaseController.html.twig, Core/XMLView/ListAsiento.xml
Modify the operation of the row status to be able to indicate the fieldname in the option tag.
Now you can indicate the name of the field globally, as it was previously in the declaration of the row, and at the level of each of the option labels.
=> Add fieldname tag to row status options

Core/Controller/EditDashboardData.php, Core/Controller/EditSettings.php, Core/Controller/ListAsiento.php, Core/Lib/ExtendedController/BaseView.php, Core/Lib/ExtendedController/EditController.php, Core/Lib/ExtendedController/GridView.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/PanelController.php, Core/View/Macro/BaseController.html.twig, Core/View/Macro/BusinessDocumentController.html.twig, Core/View/Master/BusinessDocumentController.html.twig, Core/View/Master/GridController.html.twig, Core/View/Master/PanelController.html.twig, Core/View/Master/PanelControllerBottom.html.twig, Core/View/Master/PanelControllerTop.html.twig
The getModel method has been removed because the model property has been elevated to public.
There is only one method that is called equal in EditController but that performs actions to calculate which is the model to use, so the method is left.
=> Remove getModel function from BaseView

Core/App/AppInstaller.php, Core/Translation/en_EN.json, Core/View/Installer/Install.html.twig
Related to [Trello task](https://trello.com/c/4v43crHu/367-modificar-el-install-para-añadir-como-inputs-las-variables-cookieexpire-debug-y-route)
- Adds support for receive POST values for:
- fs_cookies_expire by default 604800
- fs_route by default getUri()
- The previous values aren't required to be added also on view as hidden input type as described on task
- fs_debug by default false
- Added checkbox for enable/disable debug mode from user on view
=> Updated AppInstaller to allow more custom values from unattended installer

Core/Lib/ExtendedController/WidgetItemSelect.php, Core/XMLView/EditRoleAccess.xml, Core/XMLView/ListEjercicio.xml, Core/XMLView/ListRoleAccess.xml, Core/XMLView/SettingsDefault.xml
The Select widget now applies the css styles indicated with the "option" tags.
Now translation is applied to the titles when the values are loaded from an array and the "title" is informed. If "title" is not reported, the "value" content is displayed as a description without applying translation.
For cases in which titles and values are loaded from the database, translation is applied if the attribute "translate" is added to the declaration of the "value" tag with value "true".
=> Fix Options css style and translate title in WidgetSelect

Core/Controller/ListLogMessage.php
Added autocomplete filter and date filter on ListLogMessage controller.
=> Add autocomplete and date filter

Core/Controller/ListCliente.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/ListView.php
Now you can specify one or more fields for the sort in each of the sorting options.
To indicate more than one sort field in one of the options, an array of strings with the field names must be reported when the sort order is added from the controller.
- Sort by ONE FIELD
`$this->addOrderBy('ListCliente', 'codcliente', 'code');`
- Sort by MORE ONE FIELD
` $this->addOrderBy('ListCliente', ['fechaalta', 'codcliente'], 'date');`
=> Add sort listcontroller by more than one field

Core/Assets/JS/GridController.js, Core/Assets/JS/ListController.js, Core/Controller/ListCuenta.php, Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/ListController.php, Core/View/Master/GridController.html.twig, Core/View/Master/ListController.html.twig
- Now you can control whether a view can or not insert data using the settings of the controller. When it can not insert data, the 'insert' button goes to the 'disabled' state.
**Into Controller for disable insert action**:
`$this->setSettings('MyViewName', 'insert', false);`
- Rename to UpperCamelCase gridController.js file.
- Separated the JavaScript code from the List Controller template to a separate file.
=> Add control on the insert button and minor Fix

Core/App/AppController.php, Core/View/Login/Login.html.twig
- When user logout, replaced login view to a redirection to main page
- Webportal default url or if not setted to FS_FOLDER
- When user is doing a new login, post action url must be do it to fsc.url and not to index.php (index.php it's implicit), and user goes to page he expects after login
=> Minor improvements to login/logout

Core/Base/Translator.php
- Added support for change default translator language from external place (for example, webportal fully rendered in english, french, ...)
- Find first code lang match (webportal use 2 digits lang code versus FS use 5 digits), found the first match, BUT checking first default language.
- For example es_ES is after es_AR, but if not checked first, es_AR is used as default lang if FS_LANG=es_ES.
=> Added external access to setLangCode, to change default language

Core/Controller/EditRole.php
The problem was the form how call to the variable.
self is to static variables or constant.
=> Fixed problem when added a menu on rules

Core/App/WebRender.php
To convert parsed HTML to real HTML and lets Twig to rendered it.
This is needed in case anyone needs to store HTML code in database to render it later. Not the same as store code sample (as in documentation), that can be used directly escaped without use this filter.
=> Added Twig Filter to use Utils:fixHtml

Core/Assets/JS/PanelController.js, Core/Lib/ExtendedController/BaseController.php
Now you can indicate the values for the autocomplete by defining a list of values in the xml file of the view.
How to use:
Autocomplete from database table:
```
<widget type="autocomplete" fieldname="codsubcuenta" required="true">
<values source="subcuentas" fieldcode="codsubcuenta" fieldtitle="descripcion"></values>
</widget>
```
Autocomplete from fixes values:
```
<widget type="autocomplete" fieldname="codsubcuenta" required="true">
<values title="title-to-translate1">Value1</values>
<values title="title-to-translate2">Value2</values>
<values title="title-to-translate3">Value3</values>
</widget>
```
=> Add Autocomplete from Widget values

Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditFacturaCliente.xml, Core/XMLView/EditPedidoCliente.xml, Core/XMLView/EditPresupuestoCliente.xml
Added codeCountry on edit xmlview about sales documents.
=> Added codeCountry

Core/App/AppAPI.php
Currently in isAllowed a loop is used to check if the use of the resource is allowed for the user.
The loop is removed and the requested resource is located directly via loadFromCode.
As it is, all() method is limited by default to the first 50 registers, and therefore did not make the complete verification.
=> Remove loop and locate the requested resource directly.

Core/View/Macro/MenuItems.html.twig, Core/View/Master/MenuTemplate.html.twig
- Replaced MenuTemplate call to macro
- Added 6 little macros to replace all previous method on class:
- generate() as entry point
- getHTMLIcon()
- getMenuLabel()
- getMenuId()
- getHTML()
- getItem()
=> Replace Core/Lib/MenuItem class with a Twig macro

Core/Base/FileManager.php, Core/Controller/Updater.php
Now the function recursiveCopy on FileManager return false if it can´t create the directory.
So, I added a break on the loop of update function to finish it.
=> Return true false on recursive copy

Core/Lib/RandomDataGenerator/AbstractRandom.php, Core/Lib/RandomDataGenerator/Agentes.php, Core/Lib/RandomDataGenerator/AlbaranesCliente.php, Core/Lib/RandomDataGenerator/AlbaranesProveedor.php, Core/Lib/RandomDataGenerator/Articulos.php, Core/Lib/RandomDataGenerator/ArticulosProveedor.php, Core/Lib/RandomDataGenerator/Asientos.php, Core/Lib/RandomDataGenerator/Clientes.php, Core/Lib/RandomDataGenerator/Cuentas.php, Core/Lib/RandomDataGenerator/Fabricantes.php, Core/Lib/RandomDataGenerator/Familias.php, Core/Lib/RandomDataGenerator/Grupos.php, Core/Lib/RandomDataGenerator/PedidosCliente.php, Core/Lib/RandomDataGenerator/PedidosProveedor.php, Core/Lib/RandomDataGenerator/PresupuestosCliente.php, Core/Lib/RandomDataGenerator/PresupuestosProveedor.php, Core/Lib/RandomDataGenerator/Proveedores.php, Core/Lib/RandomDataGenerator/Subcuentas.php
- Changed visibility in AbstractRandom for dataBase and added miniLog, avoid to re-define it on child classes
- All quantity for generation fixed to 50
- More documents can be generated with less time than before with this change, but SQL tab for debugbar cause lag when render the result page because have more than 5.000 SQL queries
=> Updated generate method to do it all in one transaction [Trello task 480]

Core/Model/Divisa.php, Core/Table/divisas.xml, Core/XMLView/SettingsDefault.xml
Se ha modificado la longitud de CODISO tanto en la documentación del modelo como en la función test() y en el XML de la base de datos. 
Se ha añadido a SettingsDefault.xml el checkbox ventasinstock.
=> Ampliar CODISO del modelo Divisa a 5 caracteres y adición de ventasinstock a SettingsDefault.xml

Core/App/AppInstaller.php, Core/Translation/en_EN.json
If _mod_rewrite_ is not enabled on Apache, custom routes aren't working and FS don't works.
**NOTE:** Added also a check for _mod_expires_ and _mod_php7_, but only show a info message without error.
=> Detection of missing mod_rewrite Apache module on installation

Core/Assets/JS/EditDashboardData.js, Core/Controller/EditDashboardData.php
This Edit controller requires and adicional parameter component.
- Added as default component Messages if it's not setted.
- From JS, use component setted on edit to use it as new component type
=> EditDashboardData error when no component set [Trello task 447]

Core/Model/Base/PurchaseDocument.php, Core/Model/Base/SalesDocument.php, Core/Table/albaranescli.xml, Core/Table/facturascli.xml, Core/Table/pedidoscli.xml, Core/Table/presupuestoscli.xml, Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditFacturaCliente.xml, Core/XMLView/EditPedidoCliente.xml, Core/XMLView/EditPresupuestoCliente.xml
Remove fields apartadoenv, apellidosenv, ciudadenv, coddir, codpaisenv, codpostalenv, nombreenv y provinciaenv:
- From Table, Model and XMLView
- From Core/Model/Base/SalesDocument
Minor fix on PhpDoc for getSubjectColumns
=> Removed shipping address fields from sales documents [Trello task 499]

Core/Model/Contacto.php
When recording the contact record, if the lastactivity field is empty, it contains an empty string instead of a null string. It is corrected in the test function.
=> Fix empty value for lastactivity

Core/App/AppInstaller.php, Core/Base/Cache/FileCache.php, Core/Base/FileManager.php, Core/Base/PluginDeploy.php, Core/Model/AttachedFile.php
- Default new folders permissions setted to 0770
- Replaced all mkdir calls with FileManager::createFolder
**Note:** This changes means that only user and group have full access, and nothing to others. This can generate problems if files and folder don't have a correct ownership, because by default new files are assigned to who create it.
If anyone have problems, can try with this:
A unified way to work in local with this permissions between us as owner and Apache with no problems (_Requires ACL enabled_), in my case I use it as Apache userdir to not work directly with Apache root folder, but this is not important, only for comfort and simulate a real case with other permissions than default in Apache root (isn't normal work in default apache root default on most hosting providers): …
=> Unified creation of folders with FileManager [Trello task 517]

Core/Controller/Wizard.php, Core/Data/Codpais/ESP/default.json
Now we can set pre-defined values for AppSettings based on default codpais code on Wizard page load.
**Note:** In this case default.json only includes default group, but supports pre-set all groups that we can need.
**Note 2:** Can be useful on save AppSettings generate a copy on MyFiles folder, and Wizard can force by default codpais data or the stored on MyFiles folder.
=> Updated Wizard to set default predefined settings [Trello task 511]

Core/Controller/ListLogMessage.php, Core/XMLView/ListLogMessage.xml, Core/XMLView/ListRoleAccess.xml
- Added support to delete logs based on search filter and not restricted by page limit, use the same filters as on list page
- Minor fix with double translate tag on ListRoleAccess modal group
=> Delete log messages based on search filter with and special action [Trello task 519]

Core/Lib/ExtendedController/ListFilter.php, Core/Lib/ExtendedController/ListView.php
The hasValue method is raised to public for use from views and controllers.
The getFilter($key) method that allows us to obtain the filter identified by the key is added. This method complements the existing getFilters () that returns the list of available filters of a view.
=> Add greater visibility to filters

Core/Base/DataBase/DataBaseSQL.php, Core/Base/DataBase/DataBaseTools.php, Core/Base/DataBase/MysqlSQL.php, Core/Base/DataBase/PostgresqlSQL.php
- Added return type on DataBaseSQL interface PHPDoc blocks
- Added support to IF NOT EXISTS on sqlCreateTable (optional)
- Added support for sqlDropTable with support for IF EXISTS (optional)
=> Minor improvements to DataBaseSQL

Core/Controller/ListAlmacen.php, Core/Table/transferenciasstock.xml, Core/XMLView/EditTransferenciaStock.xml, Core/XMLView/ListTransferenciaStock.xml
Added column observations on trasnferenciasstock xml of table definition, on EditTransferenciasStock and ListTrasnferenciasStock xml views.
Added filter of search to observaciones on its ListController.
=> Added observations transfer stock

Core/Controller/Wizard.php, Core/View/Wizard.html.twig
Required introduce email on Wizard with HTML and added function on Wizard controller to get and save the email. If the user has email, the view doesn´t show the input for the new password.
=> Required email user wizard

Core/Model/Asiento.php, Core/Model/Partida.php, Core/Model/Subcuenta.php, Core/Model/SubcuentaSaldo.php, package.json
Transaction control is eliminated since the Database library already performs that control. This simplifies the code in the models.
=> Fix Reduce the code in the recording process

Core/Lib/Widget/RowStatus.php
- Fixed calculation of the value indicated in the xml option of the view.
- Added the operator '!' for cases in which a value other than the one reported in the xml option of the view is desired.
=> Fix and Add option into Row Status

Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml
Remove column codejercicio from documentos tables and remove its foreign key that reference to ejercicios
=> Remove column codejercicio from documentos tables

Core/Lib/ExtendedController/GridView.php
When adding a new record in the master view of a grid view, the value of the link key with the detail view was not calculated correctly.
=> Fix error when new record

Core/Controller/ListAgente.php, Core/Model/Agente.php, Core/Table/agentes.xml, Core/XMLView/EditAgente.xml, Core/XMLView/EditCliente.xml, Core/XMLView/ListAgente.xml
Delete "apellidos" columns and all references. Now use standard "nombre" column for determine description of record.
=> Delete "apellidos" column from Agente Model

Core/Lib/ExtendedController/BaseView.php
Restructure columnForName and add columnModalForName.
This is necessary to be able to access the columns of the modal forms, for example to be able to load special values to select widgets.
=> Add column modal for name method

Core/Lib/Widget/WidgetTextarea.php
Added property rows on /Core/Lib/Widget/WidgetTextarea.php to specify the number of rows to the textarea element.
=> Added property rows to textarea widget to specify the number of rows.

Core/View/Master/PanelControllerBottom.html.twig
Now the PanelController template with bottom buttons only shows the buttons to change the tab if there are more than two defined views (the main one and a secondary one)
=> Modified panelcontroller buttom template

Core/Controller/DocumentReports.php, Core/Lib/DocumentReportsBase/DocumentReportsSource.php
He añadido la  opción de presupuestos de proveedor en el informe de documentos (controlador DocumentReports), y he puesto la fecha de inicio por defecto  a principio de año, en lugar de principio de mes.
=> facturascripts: task_55_add_supplier_budgets_to_DocumentReports_controller

Core/Controller/EditSecuenciaDocumento.php, Core/Controller/ListSecuenciaDocumento.php, Core/Model/SecuenciaDocumento.php, Core/Table/secuenciasdocumentos.xml, Core/XMLView/EditSecuenciaDocumento.xml, Core/XMLView/ListSecuenciaDocumento.xml
Added functionallity to personalize the numeration and code of sales and purchase documents.
- Create model SecuenciaDocumento.
- Create ListSecuenciaDocumento to show all sencuences.
- Create EditSecuenciaDocument to modify all information of a document.
- Create secuenciasdocuments.xml to create the corresponding table of secuences.
- Create ListSecuenciaDocumento.xml and EditSecuenciaDocumento.xml
=> Personalize numeration and code of sales documents

Core/Lib/Accounting/AccountingCreateTools.php
When creating a subaccount if the description is not reported, the description of the parent account is used.
=> Added automatic description

Test/Core/CustomTest.php, Test/Core/Model/AgenciaTransporteTest.php, Test/Core/Model/AgenteTest.php, Test/Core/Model/AlmacenTest.php, Test/Core/Model/AtributoTest.php, Test/Core/Model/ClienteTest.php, Test/Core/Model/FabricanteTest.php, Test/Core/Model/FamiliaTest.php, Test/Core/Model/FormaPagoTest.php, Test/Core/Model/ImpuestoTest.php, Test/Core/Model/ProveedorTest.php, Test/Core/Model/RoleTest.php, Test/Core/Model/SerieTest.php, Test/Core/Model/TarifaTest.php, Test/Core/Model/UserTest.php
Add primary column value test for invalid characters in models:
- Agenciatransporte
- Agente
- Almacen
- Atributo
- Cliente
- Fabricante
- Familia
- Formapago
- Impuesto
- Proveedor
- Role
- Serie
- Tarifa
- User
Console command:
`phpunit.phar phpunit.xml`
=> #215 - Add primary column value test

Core/Base/PluginDeploy.php
Soluciono un error silencioso en el método **linkFiles** de la clase **PluginDeploy**.
El método fallaba de manera silenciosa cuando se intentaba copiar un archivo que no poseía extension, por ejemplo los archivos LICENSE y changelog, esto debido a que la función **pathinfo** no retorna ninguna extensión para esos archivos.
También cambio el nombre de la variable local **$infoFile** a **$fileInfo** el nuevo nombre es mas preciso.
=> fix error when the files don't have a file extension.

Core/Data/Codpais/DOM/defaultPlan.csv
PYG subaccount added to Dominican Republic Accounting Plan
Added a subaccount to allow close a fiscal year linking it to the special account PYG
Subcuenta para PYG agregado al Plan de Cuentas de República Dominicana
Se agrego la subcuenta para poder cerrar el año fiscal y se enlazó esta cuenta con la cuenta especial PYG.
Pruebas
=> facturascripts: added PYG subaccount for fiscal year close DOM

Core/Lib/API/APIModel.php, Core/Model/Base/ModelCore.php
Cree un nuevo **getFieldsValues** en el ModelCore, este método retorna un array con los valores del modelo según los campos retornados por el **getModelFields**, la motivación para la creación de este método es que en la clase **APIModel** existe un error dado que en varios métodos y respuestas se realiza una conversión cruda de los modelos a arreglos de la forma `(array)$object` esto causa comportamiento inesperados para modelos que extienden otras clases o implementan traits.
Ahora el método **getFieldsValues** permitiría que nosotros podamos sobre escribirlo en los modelos para cambiar la data que se responde en el API si es necesario.
De igual forma es bastante útil y común poder acceder de forma directa a estos valores en facturascripts fuera del entorno del API, este método seria …
=> Remove raw array conversion on APIModel routines.

Core/Controller/ListPresupuestoCliente.php, Core/Data/Lang/ES/estados_documentos.csv, Core/XMLView/EditPresupuestoCliente.xml, Core/XMLView/ListPresupuestoCliente.xml
Método para revisar y  cambiar a estado caducado todos aquellos presupuestos de venta cuya fecha fin haya expirado, cada vez que accedemos al ListPresupuestoCliente .
- [ X] MySQL
Para poder probar, he creado primero el estado caducado en mi instalación de pruebas.
=> task#23 Added method to change status to expired to PresupuestoCliente

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListAlbaranProveedor.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPedidoProveedor.xml, Core/XMLView/ListPresupuestoCliente.xml, Core/XMLView/ListPresupuestoProveedor.xml
Added the supplies column to the xmlview files for quotes, orders, albaren, customer and supplier invoices.
=> Task 394 - Total supplies in xmlview

Core/Lib/ExtendedController/ListBusinessDocument.php, Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml
Hidden column of supply is added in budgets, orders, delivery notes and invoices from customers and suppliers.
A filter is also added to show only lines that are supplied.
-----
Se agrega una columna oculta de suministro en presupuestos, pedidos, albaranes y facturas de clientes y proveedores.
También se agrega un filtro para mostrar solo las líneas que se suministran.
=> Task 395 - Column supplied in xmlview

Core/View/Master/GridView.html.twig
When the master model don't have editable field the GridView set documentReadOnly on edit record.
=> Fix documentReadOnly when dont exists editable field

Core/Lib/Widget/RowStatus.php, Core/Lib/Widget/VisualItem.php, Core/View/Master/ListView.html.twig, Core/View/Master/ListViewMin.html.twig, Core/XMLView/ListAsiento.xml
Added the **title** attribute to the _options_ of the row status group.
Now, it's possible to indicate a text or translatable string into the user's language, an explanatory description of the reason why the row is colored.
You can consult the Accounting entries option of the Accounting menu to see the result, or consult the ListAsiento.xml file to see an example of how to use it.
=> Task #410: Add title option to row status

Core/Lib/ExtendedController/EditListView.php, Core/Lib/Widget/ColumnItem.php, Core/Lib/Widget/GroupItem.php, Core/View/Master/EditInLineView.html.twig
Now you have the ability to configure the EditListView in "inline form" mode.
**Example of use:**
```
$this->addEditListView('MyEditInLineView', 'MyModel', 'ingredients', 'fas fa-tasks');
$this->views['MyEditInLineView']->setEditInLine(true);
```
**Result display:**
=> Add new Edit View style

Core/Base/Debug/DebugBar.php
See details image: https://prnt.sc/w0pql5
En el caso de hacer un post con datos en array similares a:
``` <input type="text" name="properties[]" /> ```
Donde se envían muchas datos `clave -> valor` el render del debug bar falla.
=> Allow multiple cells bidimensional render (DebugBar)

Core/Model/Cliente.php
Cuando se hace la verificación del  documento de identidad en el método test() del Contacto falla por que llega el tipo de documento por defecto, mas no el que se seleccionó en la creación del cliente.
=> Contact method test fails before creating a new client

Core/Lib/ExportManager.php
Added the public method "_**getDoc()**_" to the **ExportManager** class, to allow obtaining the document to export from controllers.
=> Add getDoc method

Core/Lib/BusinessDocumentCode.php
When a new sequence is automatically created for a document type, it now takes the same length as previous exercises.
_Note: It's a minor change_
=> Task 530 - Assign sequence length

Core/Base/ControllerPermissions.php, Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/BusinessDocumentController.php, Core/Lib/ExtendedController/EditController.php, Core/Lib/ExtendedController/ListController.php, Core/Model/RoleAccess.php, Core/Table/roles_access.xml, Core/XMLView/EditRoleAccess.xml, Core/XMLView/ListPageRule.xml
Added filter and access control to information whose owner is the active user or user who has made the login.
The control has been added at the group level, creating a new attribute that allows the administrator to indicate if a controller allows to see all the information or only the proprietary information of the active user.
The controllers now have two methods to filter and / or control access to information.
- **checkOwnerData**: Indicates if the model data record is accessible by the active user.
- **getOwnerFilter**: Returns the condition in the form of DataBaseWhere to add to the call to obtain the information if you want to use the proprietary data control.
**These controls have been included** in the extended controllers: **ListController**, **EditController**, and …
=> Only owner data

Core/Lib/BusinessDocumentCode.php
Fix getNewNumber for BusinessDocument below initial sequence number.
Using the "usarhuecos" option with document sequences, it can happen that the next assigned document number is below the defined initial number of that sequence. This fix provides a simple solution.
Background: This happened to me after changing a sequence from one fiscal year to another (which is allowed), using higher document numbers than before. Later, gaps were found below the new initial number.
=> Fix getNewNumber for BusinessDocument below initial sequence number.

Core/Controller/DocumentStitcher.php
When the document that is grouped does not have lines, the extra line of information is not added
=> Fix extra line when document don't have lines

Core/Model/ProductoProveedor.php
Recalculate the cost price based on the last purchase price. Cost prices are now always calculated later after having saved the product cost by vendor.
**Note**: Due to the lack of correct information, I have not been able to perform a complete battery of tests on all possible existing calculations. A review with different databases is highly recommended to verify that the original problem has certainly been corrected.
=> Fix cost price calculation

Core/App/AppRouter.php
It allows downloading large files, by performing the download preparation directly in the output buffer, instead of using the PHP memory storage system.
=> Fix download large file

Core/Controller/ListProducto.php
The checkboxes that filter the blocked and public products have been changed by a single filter of type selectwhere.
=> Change filter status

Core/View/Master/ListController.html.twig
If the window width is 1024 or larger, the focus is automatically placed on the search input of the active tab.
=> Set focus to query search

Core/Controller/EditReportAmount.php, Core/Lib/Accounting/BalanceAmounts.php, Core/Lib/ExtendedController/EditReportAccounting.php
Fixed error when a subaccount was reported from or to but its complementary (from / to) was not reported.
Fixed the calculation so that it does not calculate accounts and subaccounts that are not in the range of the filter applied by the user.
=> Fixed filtering of subaccounts

Core/Lib/Export/PDFExport.php, Core/Lib/PDF/PDFDocument.php
Cuando exportas un documento (factura, albarán,etc.) y eliges un idioma al que traducir el documento PDF, la cabecera de la tabla con las líneas de productos no es traducida. Esta cabecera siempre es traducida con el idioma del usuario que está imprimiendo el documento.
=> [FIX] Error en traducción en documentos PDF

Core/Controller/EditPageOption.php, Core/Model/PageOption.php
Fixed problem loading display options.
The correct operation is:
- If a user is selected, its configuration is loaded, the configuration common to all users or if none of the above cases exist, the xml view is loaded.
- If all users are selected, the configuration common to all users is loaded or if it does not exist, the xml view is loaded.
=> Fix loadPageOption for selected user

Core/Controller/EditSettings.php
Refactored controller so that it loads the defaults view first and then the list of views for plugin configuration.
Additionally, the private methods have been moved to the end of the file, just after the protected methods.
=> Load first default settings

Core/Lib/PDF/PDFDocument.php
Al imprimir facturas en PDF, en el campo serie debe mostrar el nombre de la serie y no el código. Es decir, debe aparecer Serie: general, en lugar de Serie: A.
=> Tarea #583 - Mostrar el nombre de la serie en vez del código en los pdf.

Core/Lib/ExtendedController/ListView.php, Core/Lib/ListFilter/AutocompleteFilter.php, Core/Lib/ListFilter/BaseFilter.php, Core/Lib/ListFilter/CheckboxFilter.php, Core/Lib/ListFilter/NumberFilter.php, Core/Lib/ListFilter/SelectFilter.php
Cuando se cargaba un filtro favorito, al carga otro filtro favorito se sumaban los efectos de los filtros, en vez de quitar uno y poner el otro. Se ha corregido ese efecto, además se marcan todos los filtros como disabled cuando se tiene cargado un filtro favorito.
=> Tarea #565 - Corrección al cargar filtros favoritos.

Core/Lib/ReceiptGenerator.php
This change fixes the supplier receipt date and now the receipt date is the same as the invoice date. This also fixes the expiration time that now is generated from the invoice date instead of from the date the receipt was created.
=> fix supplier receipt date

Core/Model/Base/ModelClass.php
Añadido soporte de extensiones al método test de los modelos, se puede introducir un testBefore para ejecutar el código antes del test del modelo y otro al final del mismo método.
=> Añadido soporte de extensión al método test del ModelClass.php

Core/Lib/ExtendedController/ListViewFiltersTrait.php
Cuando se guarda un filtro si una de las opciones marcada para guardar su valor es 0 no se guardaba dicha opción, ahora con este cambio si se guarda.
[Tarea #685](https://facturascripts.com/roadmap/EditTask?code=685)
=> Tarea #685 - Corregido bug que impedía guardar filtros con valor 0.

Core/Controller/DocumentStitcher.php
Evitar juntar documentos cuanto el dtopor1 o el dtopor2 son diferentes. Se debe actualizar también la traducción "incompatible-document" una vez aprobado el pr.
=> Evitar juntar documentos con el descuento general diferente.

Core/Lib/Email/MailNotifier.php
Mostrar aviso de error cuando la notificación que se intenta usar no existe o no está activa.
[Tarea #672](https://facturascripts.com/roadmap/EditTask?code=672)
=> Tarea #672 - Notificar cuando la notificación de email no existe o no esta activa.

Core/Controller/EditFacturaCliente.php, Core/Controller/EditFacturaProveedor.php, Core/Controller/ListPresupuestoCliente.php, Core/Lib/Accounting/ClosingToAcounting.php, Core/Lib/ExtendedController/BusinessDocumentView.php, Core/Lib/ExtendedController/ListBusinessActionTrait.php, Core/Model/Base/TransformerDocument.php
Renombrar método getAvaliableStatus() a getAvailableStatus() tanto en la clase TransformerDocument como en todas las llamadas a este método.
=> Tarea #517 - Renombrar método getAvaliableStatus() a getAvailableStatus()

Core/Model/Base/JoinModel.php
Cuando se exporta un listado desde un JoinModel no sabemos los tipos de las columnas, esto hace que todas las columnas en un xls sean de tipo string. Con este arreglo obtenemos el tipo de cada columna para saber como formatear cada celda.
=> Tarea #781 - Solucionado bug al exportar en xls desde un JoinModel.

Core/Model/Producto.php, Core/Model/Variante.php, Core/XMLView/EditProducto.xml, Core/XMLView/EditVariante.xml
Now it is allowed to leave without informing the reference in the products and their variants. If not informed, the system calculates an automatic numerical code based on the last code used in that field.
=> Remove required reference code

Core/View/EditPageOption.html.twig
A user information text label has been added to the top of the window.
The label contemplates the translation system. For this it is necessary to incorporate the label (ES_es example):
- "page-option-info": "Desde aquí puedes modificar los campos visibles en este listado o formulario"
=> Add text info to EditPageOption view

Core/Base/AjaxForms/CommonLineHTML.php, Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Base/AjaxForms/PurchasesController.php, Core/Base/AjaxForms/PurchasesHeaderHTML.php, Core/Base/AjaxForms/PurchasesLineHTML.php, Core/Base/AjaxForms/SalesController.php, Core/Base/AjaxForms/SalesHeaderHTML.php, Core/Base/AjaxForms/SalesLineHTML.php, Core/Base/Contract/PurchasesLineModInterface.php, Core/Base/Contract/SalesLineModInterface.php, Core/View/Tab/PurchasesDocument.html.twig, Core/View/Tab/SalesDocument.html.twig
Se han quitado los padding-x en las columnas y border-radius de los inputs, además de poner todos los inputs y botones en tamaño sm, en los formularios de compras y ventas.
=> Tarea #783 - cambio diseño de los formularios de compras y ventas

Core/Base/AjaxForms/SalesController.php, Core/Base/AjaxForms/SalesModalHTML.php
Formulario de ventas. Cuando el usuario tiene marcado "solamente ver lo suyo" debe mostrar en el modal de clientes y el buscador de clientes solamente los clientes que tiene vinculador por codagente. Debe ocultar todos los demás.
[Tarea #834](https://facturascripts.com/roadmap/EditTask?code=834)
=> Tarea #834 - Mostrar solo sus clientes al crear formularios de venta.

Core/Base/AjaxForms/PurchasesController.php, Core/Base/AjaxForms/SalesController.php, Core/Model/Variante.php
Al hacer compras o ventas, al añadir productos escribiendo la referencia en el campo referencia, está autocompletando incluso productos que están bloqueados. Parece que no se está aplicando la restricción de:
No mostrar en búsquedas los productos bloqueados.
No mostrar en ventas los productos con se vende desmarcado.
No mostrar en compras los productos con se compra desmarcado.
[Tarea #948](https://facturascripts.com/roadmap/EditTask?code=948)
=> Tarea #948 - Filtrar productos al buscar en documentos de compra y venta

Core/Lib/ExtendedController/ListBusinessDocument.php
Ocultar filtros de usuario y agente en los listados de compras y ventas cuando el usuario solamente tiene permiso para ver lo suyo.
[Tarea #908](https://facturascripts.com/roadmap/EditTask?code=908)
=> Tarea #908 - Ocultar filtros de usuario y agente en los listados de compras y venta

Core/Base/ExtensionsTrait.php
He copiado la función pipe a pipeFalse y el break ahora solo se produce si $return === false.
=> Tarea #859

Core/Base/AjaxForms/CommonLineHTML.php, Core/Base/AjaxForms/SalesLineHTML.php, Core/Lib/PDF/PDFDocument.php, Core/Model/Base/SalesDocumentLine.php, Core/Table/lineasalbaranescli.xml, Core/Table/lineasfacturascli.xml, Core/Table/lineaspedidoscli.xml, Core/Table/lineaspresupuestoscli.xml, Core/Translation/es_ES.json
Añadir campo (checkbox) salto de página a las líneas de facturas, albaranes, pedidos y presupuestos de venta. Añadir también al formulario de edición los checkbox para los campos ya existentes mostrar_cantidad y mostrar_precio.
[Tarea #971](https://facturascripts.com/roadmap/EditTask?code=971)
=> Tarea #971 - Añadidas opciones de salto de línea, mostrar cantidad y mostrar precios

Core/Lib/CustomerRiskTools.php, Core/Model/Base/Receipt.php, Core/Model/ReciboCliente.php
Until now, if a user updated a customer's invoice receipt, the customer's risk remained the same. With this update the risk is updated. The risk calculation formula has also been changed in order to have a more realistic approximation of the risk. Now the formula is:
Risk = Cost of new orders + Cost of undelivered delivery notes + ( Amount of unpaid invoices - Amount of paid receipts of unpaid invoices).
=> Fix Customer's risk updated

Core/View/Tab/PreviewFiles.html.twig
Template with preview and direct download.
- add use of the trait, DocFilesTrait
- add the new document view in the createViews method, changing the standard template to the new one $this-> createViewDocFiles ('docfiles', 'Tab / PreviewFiles');
- add actions to add file, delete file, edit file and unlink file in execPreviousAction method.
- add data load data from the document view by calling the loadDataDocFiles method reporting the primary key of the primary model
=> Add new template for attached files

Core/Lib/Widget/BaseWidget.php
Permite usar parámetros adiciones en el onclick de los widget. Por ejemplo si queremos que al pinchar vaya a otro controlador pero dentro de una pestaña, pondriamos esto: onclick="EditCliente?activetab=direcciones". De este modo detecta que se esta usando el carácter '?' y en vez de ponerlo 2 veces como hace ahora lo pondría una vez, y el code iría separado con '&'.
=> Permite usar parámetros en el onclick de los widget.

Core/Base/Calculator.php
Si no devolvemos el total de la factura cuando llamamos a Calculator los Test fallan al comprobar el total contra el total de su asiento.
=> Solucionado bug al devolver el total calculado redondeado

Core/Model/Asiento.php, Test/Core/Model/AsientoTest.php
- Fixed sql ordering to return opening record first.
- Modified the test so that it creates two entries with the date of the first day of the year and assigns one as opening operation.
- Added check that the first entry when reading all entries is the opening entry.
=> Fix renumber method

Core/Base/AjaxForms/CommonLineHTML.php, Core/Base/AjaxForms/PurchasesLineHTML.php, Core/Base/AjaxForms/SalesLineHTML.php
Es necesario poder mostrar el número de línea en los documentos. PlantillasPDF lleva dicha opción, es muy difícil mandar un pdf al cliente con muchas páginas y que te diga, la línea 127 está mal y al ir al documento debes buscarla con Ctrl+f o contanto las líneas.
=> Mostrar número de línea en los documentos de compra y venta.

Core/Model/ProductoProveedor.php
In the cost prices by supplier and currency, the default currency of the application is established in the initialization of values.
=> Set default divisa to app default divisa

Core/Assets/JS/WidgetSelect.js, Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/PanelController.php, Core/Lib/Widget/WidgetSelect.php
En muchas ocasiones necesitamos que un widget select cargue los datos en base a los datos de otro widget. Por ejemplo cargar las provincias en base al país seleccionado.
Caso de uso en el XMLView de EDitContacto
```
<column name="province" numcolumns="2" order="140">
<widget type="select" fieldname="provincia" parent="codpais">
<values source="provincias" fieldcode="idprovincia" fieldtitle="provincia" fieldfilter="codpais"/>
</widget>
</column>
<column name="country" titleurl="ListPais" numcolumns="2" order="150">
<widget type="select" fieldname="codpais" onclick="EditPais" required="true">
<values source="paises" fieldcode="codpais" fieldtitle="nombre"/>
</widget>
</column>
```
Podemos ver que el widget de la provincia hace referencia al widget del país, además en los valores de la …
=> Añadir soporte al widget select para cargar datos en base a otro widget.

Core/Assets/JS/WidgetSelect.js
La variable waitCounter ya está declarada en los documentos de compra y venta, y al volverse a declarar en algún js de los que cargue el head da error. Por lo que se ha renombrado la variable del js de WidgetSelect.
=> La variable waitCounter ya está declarada.

Core/XMLView/EditCliente.xml
Eliminada la restricción de nivel a la columna agente en la edición de un cliente.
Removed the level restriction to the agent column in a customer edition.
=> Remove the level for agent column

Core/Lib/ListFilter/PeriodFilter.php, Core/Lib/ListFilter/PeriodTools.php
[Tarea #1886](https://facturascripts.com/roadmap/EditTask?code=1886)
Ahora el filtro periodo es más intuitivo al poner la fecha desde y hasta con >= e <=.
=> El filtro periodo ahora el hasta es <=

Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Lib/ExtendedController/ComercialContactController.php, Core/XMLView/ListReciboCliente.xml, Core/XMLView/ListReciboProveedor.xml
Tarea #813:
- Sustituir filtro en recibos, de Fecha a Vencimiento.
- Sustituir ordenación en recibos, de Fecha a Vencimiento.
- En la pestaña de Recibos de las vistas de Facturas de Clientes y de Facturas de Proveedores, he sustituido el filtro de Fecha por el de Vencimiento. También he intercambiado el identificador del filtro y el label, para que se interprete que el dato a filtrar en el Vencimiento. 
- En la pestaña de Recibos de la edición de Clientes y en la de Proveedores,  he incluido el filtro de Vencimiento.
- He cambiado la ordenación predetermina de Fecha por el de Vencimiento, que será mas apropiado ya que la fecha del recibo no aparece en esos dos listados y en esa dos vistas de edición.
=> Tarea #813

Core/Controller/EditUser.php, Core/Table/roles_access.xml, Test/Core/Model/RoleTest.php
- Se ha suprimido la FK entre el modelo RoleAccess y el modelo Page. Con esto se consigue que al eliminar las páginas al desactivar un plugin no desaparezcan los permisos de usuarios definidos.
- The FK between the RoleAccess model and the Page model has been removed. With this it is achieved that when deleting the pages when deactivating a plugin the defined user permissions do not disappear.
- (Discord) …
=> Task#1025 roles access

Core/Lib/PDF/PDFCore.php
En ocasiones necesitamos hacer un alto de página obligado al imprimir un pdf, hasta ahora no era posible. Ahora la función newPage() tiene un valor booleano para indicar que haga el salto de forma forzada.
Luego podemos hacer la llamada por ejemplo así:
`self::$pdf->newPage(self::$pdf->getOrientation(), true);`
=> Añadir opción de nueva página en el pdf de forma forzada.

Core/Base/Translator.php
Actualmente la función getAvailableLanguages() de la clase Translator solo devuelve los idiomas del core. Eso es un problema cuando los plugins añades idiomas, o se personalizan idiomas desde MyFiles, ya que no se podrían seleccionar. Con está solución se obtienen todos los idiomas disponibles.
=> Obtenemos los idiomas del core, plugins y MyFiles.

Core/Assets/JS/WidgetSelect.js
Al obtener el formulario donde se encuentra el select da error. Solo pasa al usar un EditListController, cambiando la forma en la que se obtiene el formulario corregimos el problema, y funciona tanto en un EditListController como en un EditController.
=> Corrección al obtener el formulario del WidgetSelect.

Core/View/Installer/Install.html.twig, package.json
- Actualizar a la versión 6 en el archivo package.json
- No hace falta hacer nada más porque la versión 6 es compatible con las versiones anteriores, tanto la v5 como la v4.
- **We've tried our hardest to make Version 6 backward compatible with Font Awesome 5 and Font Awesome 4 too! Whether you're using Kits, components, hosting things yourself, using Web Fonts, or SVG + JS, we've done a lot to translate icons in existing projects to Version 6 automagically.**
- https://fontawesome.com/docs/web/setup/upgrade/whats-changed#backward-compatibility
- Unicamente se ha eliminado la linea que hacia referencia al archivo `v4-shims.min.css` que ya no es necesario al ser la versión 6 compatible con la 4.
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has …
=> Tarea #1565 - Update Font Awesome Version 6

Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Base/AjaxForms/PurchasesHeaderHTML.php, Core/Base/AjaxForms/SalesHeaderHTML.php, Core/Model/Base/BusinessDocument.php, Core/Model/Empresa.php
Aplicado filtro a las formas de pago para que sólo muestre las formas de pago de la empresa del documento.
Aplicado recálculo del documento cuando se cambia el almacén.
Cuando se produce un cambio de almacén puede provocar un al cambio de empresa. Así:
- Al cambiar de almacén se actualizan los datos de empresa y sus formas de pago.
- Cuando el documento es nuevo, y no se ha creado la cabecera permite el cambio de almacén entre empresas
- Cuando el documento está creado, sólo se permite cambiar entre almacenes de la misma empresa
- (Plan de desarrollo) …
=> Corrección por filtro de empresa

Core/Model/Variante.php, Test/Core/Model/ProductoTest.php
Al eliminar una variante cuya referencia numérica (08314) era igual a la referencia del producto (8314) daba error.
Se ha corregido dicho problema y se ha añadido un test unitario para comprobar que no vuelve a suceder.
=> Tarea #1642 - Corrección al eliminar variante

Test/Core/Lib/Email/MailNotifierTest.php, Test/Core/Model/AttachedFileTest.php, Test/Core/ToolsTest.php
- He cambiado las barras de separación de directorios por la constante `DIRECTORY_SEPARATOR` en los tests que daban fallo en Windows para que los tests pasen en todos los sistemas operativos.
- He creado un "bypass" en el test del filtrado XSS ya que en Windows no es posible manejar archivos con caracteres especiales y por tanto siempre daba error este test.
- He eliminado el test que marqué como skiped y que intentaba testear el envío de notificaciones porque actualmente no es posible testear el envío de mails.
**Con estos cambios ya se puede testear cómodamente en cualquier sistema operativo y mejorar la experiencia de desarrollo.**
=> Refactor tests para que puedan correr en windows

Core/XMLView/ListCuentaBanco.xml
- En la vista ListCuentaBanco la columna para los gastos el nombre de campo tenía una 's' de más, por lo que no se mostraba correctamente el dato de la columna.
=> Corrige nombre de campo

Core/View/Installer/Install.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/MicroTemplate.html.twig
FontAwesome está usando el sistema de capas viejo, por lo que con la última versión 6 (la actual que tiene el core) no se pueden disfrutar de muchas de las opciones que tiene para efectos en los iconos. Solo hay que dejar de cargar los iconos con CSS y usar SVG+JS.
Información y comparación de las 2 formas
https://fontawesome.com/docs/web/dig-deeper/webfont-vs-svg
Instalación
https://fontawesome.com/docs/web/setup/host-yourself/svg-js
=> Cambiar la forma de cargar FontAwesome por SVG+JS.

Core/Html.php, Core/Tools.php, Test/Core/HtmlTest.php, Test/Core/ToolsTest.php, Test/__files/testTemplate.html.twig
- Se crea la función `bytes`  en la clase `Tools` que devuelve el tamaño de un archivo formateado de forma que sea fácilmente comprensible.
- Se crea la funcion `bytes` en el motor de plantillas Twig para que esta funcionalidad pueda ser usada en las plantillas.
- Se crean los tests unitarios para la función `bytes` de la clase `Tools`.
- Se crean los tests unitarios para la función `bytes` en el motor de plantillas Twig.
=> Tarea #2580 - Funcion bytes formatea el tamaño de un archivo.

Core/Model/Variante.php, Test/Core/Model/VarianteTest.php
- Se modifica el método `save()` del modelo Variante para que no se permitan guardar valores `null` en los campos coste, precio o margen. 
- Siempre que venga por algún motivo un valor null, se asignará el valor 0.0 automáticamente.
- Se realizan los tests unitarios correspondientes para comprobar esta funcionalidad.
=> Tarea #958 - En modelo Variante, no permitir valores nulos en coste, precio o margen.

Core/Base/AjaxForms/SalesController.php
- Establecer idioma en los documentos de ventas según el idioma del cliente.
- De esta forma:
-- Si **NO** elige el idioma en el menú `Avanzado de Imprimir` y el cliente **NO** tiene definido el idioma, se establece el idioma **por defecto**.
-- Si **NO** elige el idioma en el `menú Avanzado de Imprimir` y el cliente **SI** tiene definido el idioma, se establece el idioma del **cliente**.
-- Si se elige el idioma en el `menú Avanzado de Imprimir` y el cliente tiene definido el idioma, prevalece lo que se haya elegido en el menú y se establece el idioma que se haya elegido en el `menú Avanzado de Imprimir`.
=> Tarea #2130 - Establecer idioma en los documentos de ventas según el idioma del cliente.

Core/Model/Contacto.php, Test/Core/Model/ContactoTest.php
- He eliminado `idcontacto` de los campos de la búsqueda en el método `codeModelSearch()`  porque en Postgresql falla al no tratarse de un string y no es necesario que se encuentre este campo en las búsquedas.
- He completado los tests para todos los métodos de la clase hasta alcanzar el 100% de cobertura.
=> Completar tests del modelo contacto

Core/Controller/CopyModel.php, Core/Controller/EditProducto.php, Core/View/CopyProducto.html.twig
- He creado un botón en la vista Editar Producto para poder realizar una copia del producto.
- Este botón no se muestra en la vista de creación de un Producto.
- Se ha incluido una acción en el controlador que copia el modelo excepto algunos campos que son propios de cada producto, como por ejemplo, las ids, las referencias, el stock, campos de fecha.
- También se copian las variantes del producto quedando así copiado el producto con todas sus variantes y se generan referencias nuevas tanto para el producto como para las variantes y así evitamos errores de referencias duplicadas.
=> Tarea #1875 - Implementar funcion para poder copiar un producto.

Core/Controller/EditProducto.php, Core/Table/atributos.xml, Core/Translation/es_ES.json, Core/XMLView/EditAtributo.xml
- Filtrar valores de atributos en la vista EditVariables, según el combo seleccionado en la vista EditAtributo.
- Se ha modificado el método `loadCustomAttributeWidgets()` para añadir los valores del Select desde el controlador filtrando los valores de los atributos según el combo elegido.
- Se ha agregado el campo `numerocombo` en la tabla `atributos` para guardar el combo seleccionado en cada atributo.
- Se completa los textos de traducciones necesarios.
- Se añade la columna numerocombo a la vista EditAtributo para que permita elegir al combo que pertenece cada atributo.
- El único inconveniente que veo en este sistema es que si dos o mas atributos eligen el mismo combo, se muestran sus valores unos tras otros.
- Se recomienda que estudien la posibilidad de implementar …
=> Tarea #1292 - Filtrar atributos en selector de variables.

Core/Assets/JS/WidgetSelect.js, Core/Lib/ExtendedController/BaseController.php
Necesitamos saber cuando el widget es requerido o no, ahora se manda esa información en el ajax del js. En consecuencia el controlador puede devolver un array diferente dependiendo de cada caso.
=> Controlar el widget select parent cuando es required.

Core/Model/ProductoProveedor.php
- Ahora se aplica la tasa de conversión en la tabla de productos por proveedor igual que en los documentos de compra. Para calcular el precio de coste en euros se obtiene el valor en la moneda del proveedor y se divide por la tasa de conversión.
=> Corregir el cálculo del precio de coste

Core/XMLView/EditReciboCliente.xml, Core/XMLView/EditReciboProveedor.xml
Cuando se crea una recibo este lleva el idempresa del documento, pero el widgetSelect de las formas de pago está mostrando todas, y debe mostrar solo las formas de pago de la empresa del recibo.
=> Corregidas las formas de pago mostradas de los recibos

Test/Core/Model/EjercicioTest.php
Añadir un test unitario para el modelo Ejercicio, siguiendo el patrón del test de AgenciaTransporte.
Se añaden estos tests según indicaciones de la Tarea #1675.
- Comprobar que se puede crear un ejercicio (y que se crea abierto) y borrarlo.
- Comprobar que no se puede crear un ejercicio con fecha de inicio posterior a la fecha de fin.
- Comprobar que se puede crear un ejercicio para una fecha dada.
- Crear un ejercicio para 2099 y comprobar que si solicitamos un ejercicio para esa fecha, lo devuelve.
- Comprobar que se pueden crear dos ejercicios para la misma fecha pero distinta empresa.
=> Tarea #1675 - add test Ejercicio Model

Core/Lib/Widget/WidgetSelect.php, Core/Model/CodeModel.php
- Se añade la funcion setLimit(int) y getLimit() para poder establecer el nuevo límite y si no hay ninguno definido, entonces que devuelva 1000.
- He añadido un nuevo parámetro `limit` a la etiqueta values del widget select
=> Tarea #1993 - Ampliar limite 1000 metodo all()

Core/Lib/PDF/PDFDocument.php
Tarea #1787 Recupera la fecha de la Factura origen para mostrarla en el PDF de la Factura rectificada
- Localizo la factura origen mediante loadFromCode y añado la fecha junto al número de la factura origen en el PDF de la factura rectificativa.
=> Tarea #1787 Fecha Fact Origen en Fact Rectif

Test/Core/Model/ProductoImagenTest.php
- Añadir dataProvider para testear las JPG, PNG y GIF con un mismo test.
=> Tarea #2674 - Agregar dataProvider para testear JPG, PNG y GIF

Core/Lib/ExtendedController/DocFilesTrait.php, Core/Lib/ExtendedController/ListBusinessDocument.php, Core/Model/Base/BusinessDocument.php, Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml, Core/Translation/es_ES.json, Test/Core/Base/Lib/ExtendedController/DocFilesTraitTest.php
Añadir columna numdocs a albaranes, facturas, pedidos y presupuestos, para guardar el número de documentos adjuntos. Añadir también el correspondiente filtro a los listados:
- Filtro checkbox "tiene adjuntos".
- Al añadir un adjunto, aumentar el numdocs del modelo.
- Al eliminar un adjunto, reducir el numdocs.
- Creamos tests correspontientes
=> Tarea #707 - Agregar columna numdocs

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Lib/ExtendedController/ComercialContactController.php, Core/Lib/ExtendedController/ListBusinessActionTrait.php, Core/Lib/ExtendedController/ListBusinessDocument.php
[Tarea #511](https://facturascripts.com/roadmap/EditTask?code=511)
En vez de mostrar el botón solo en los listados de facturas de compras y ventas, se implemento de tal forma para mostrar el mismo botón dentro de la ficha del cliente y del proveedor. De este modo se consigue el mismo efecto de ambas partes.
=> Tarea #511 - Generar asientos de facturas sin asientos.

Core/View/Tab/EmailSentHtml.html.twig
En ocasiones los enlaces del html del email no se le añade el target="_blank", por lo que al abrirlo lo hace en la misma pestaña, sacándote del programa. Con este cambio cualquier enlace del email se abrirá en una nueva pestaña.
=> Abrir enlace en pestaña nueva desde la vista del email enviado

Core/View/Macro/Toasts.html.twig
Al mostrar un mensaje de "notice" junto con el toast no estaba cogiendo el estilo, ahora se pone el estilo de success.
=> Añadido el tipo notice al toast

Core/DbQuery.php, Test/Core/Base/Template/ModelTest.php
Implementamos un where dinámico para que se pueda incluir
el nombre del campo en el propio metodo where y así
acortar código.
ej. whereNombre(), whereCiudad()
=> add-dynamic-where

Core/Controller/SendMail.php
Cuando enviamos un email en blanco, al redirigir está fallando en factura.city, ya que pone una / delante y entonces elimina el código de la instancia.
[issue](https://factura.city/issues/654bbe1f546e9)
=> Corregido bug al redirigir SendMail

Core/Lib/Widget/GroupItem.php
Los modales que llevan un formulario dentro no se estaban enviado, con este cambio soluciona ese problema con el animateSpinner()
=> Corregido bug en los modales con animateSpinner

Core/Controller/EditRole.php, Core/Kernel.php, Core/View/Tab/RoleAccess.html.twig
Agrupa los permisos por el nombre del menú añadiendo una fila por cada uno de ellos permitiendo asignar y desasignar todos los permisos de una vez. En cada grupo, indica el número de permisos que tiene asignados así como el total de los disponibles. Si tiene todos los permisos asignados la fila se pone de color "success".
Enlace al video para ver como funciona: https://youtu.be/TxU4x28gLo4
- [ X ] He revisado mi código antes de enviarlo.
- [ X ] He probado que funciona correctamente en mi PC.
- [ X ] He probado que funciona correctamente con una base de datos vacía.
=> #2149 Permisos de grupos

Core/Html.php
La función de dump() en twig no funciona por que falta cargar la clase correspondiente.
=> Añadir soporte dump a twig

Core/Lib/Email/BaseBlock.php, Core/Lib/Email/BoxBlock.php, Core/Lib/Email/ButtonBlock.php, Core/Lib/Email/HtmlBlock.php, Core/Lib/Email/SpaceBlock.php, Core/Lib/Email/TableBlock.php, Core/Lib/Email/TextBlock.php, Core/Lib/Email/TitleBlock.php, Core/View/Email/NewTemplate.html.twig
Cuando renderizamos un email cada bloque tiene su estilo, pero el email tiene 2 secciones Main y Footer, por defecto es footer, pero en ocasiones queremos renderizar un bloque en el footer que tenga un estilo diferente. Con esto podemos indicar al renderizar el bloque si es para el Main (por defecto) o es para el Footer.
=> Necesitamos saber cuando estamos renderizando un bloque para el footer del email

Core/View/AdminPlugins.html.twig
- Se aplica un estilo similar al del listado de plugins de la web facturascripts.com.
- Se implementa un campo de búsqueda por nombre de plugin.
=> cambiar estilo listado plugins

Core/Tools.php, Core/Translator.php
Los clientes, proveedores y contactos pueden tener un idioma establecido o no. Si cogemos el modelo contacto y mandamos a traducir algo con el idioma del contacto, si antes comprobar si tiene idioma o no, se le esta pasando null a la clase Translator. Ahora la clase Translator admite null, y al recibir null coge el idioma por defecto del sistema. Pero de este modo nos quitamos el estar comprobando si el contacto tiene idioma o no. Más limpio y rápido.
=> Correcciones clase Translator, idioma a null

Core/Controller/EditAgente.php
El agente tiene su contacto, y en la páginda de EditAgente si vas a la pestaña Contacto aparecen los datos del contacto del agente, pero en el select de idioma no se están cargando los idiomas, este pr corrige ese problema.
=> En la página del agente el idioma no estaba apareciendo

Core/CrashReport.php
- Se incluye a la pagina de error el fragmento de código donde se encuentra el error y se marca de color rojo la línea donde se encuentra el error.
=> agregar fragmento de codigo con error

Core/Model/EstadoDocumento.php, Core/Translation/es_ES.json, Test/Core/Model/EstadoDocumentoTest.php
- No permitir crear estados predeterminados y no editables.
- Incluimos test para comprobar que no se puede guardar un estado predeterminado y no editable.
- Incluimos el mensaje de error al fichero de traducciones.
=> Tarea #957 - no permitir estado pred y no editable

Core/Lib/ListFilter/PeriodTools.php
- Añade dos opciones al selector de períodos: "Trimestre anterior" y "Trimestre actual"
- [ X ] He revisado mi código antes de enviarlo.
- [ X ] He probado que funciona correctamente en mi PC.
- [ X ] He probado que funciona correctamente con una base de datos vacía.
=> Añadir filtro de trimestre actual y anterior

Core/Controller/Wizard.php
- Se corrigio una llamada incorrecta a Tools:settings por Tool::settingsSet en las lineas 248, 252 y 253 en el archivo Wizard.php de los Controladores, esta configuración impedia que en el siguiente paso se llenaran los datos de configuración de un pais que se eligiera de forma diferente a España.
=> Corrección para la carga de información de otros paises

Core/Translation/es_ES.json, Core/View/AdminPlugins.html.twig
- Se crean dos listados en la vista de Plugins Instalados, un listado para Plugins Activados y otro para Plugins Desactivados.
- En el listado de Plugins Activados se ordena por el campo "orden" ascendentemente.
=> Separar listado plugins activos y no activos

Core/Base/DataBase/PostgresqlEngine.php
- Desde la versión 8.1 de PHP no se le puede pasar null al primer parametros de la función stripos.
- Ahora comprobamos si es null antes de invocar esta función.
- OJO que esto afecta solo cuando se usa Postgresql.
=> evitar pasa null parametros stripos

Core/Model/Base/JoinModel.php
En la última del core los JoinModel están fallando porque no se comprueba si existe la tabla en el JoinModel.
=> Corregido bug al comprobar las tablas en los JoinModel

Test/config-scrutinizer.php
- para probar si esto ralentiza los test del scrutinizer
=> debug a false para los tests

Core/Controller/ApiRoot.php, Core/Controller/EditApiKey.php
- Estoy desarrollando un plugin donde estoy añadiendo un endpoint a la api, pero la api key para usar este plugin quiero que solo tenga acceso de lectura al controlador expuesto. Actualmente tienes que poner "acceso completo" para que se pueda acceder al recurso de un plugin.
- Actualmente no aparece el recurso "custom" del plugin en el controlador EditApiKey ya que solo recupera los recursos del directorio Lib/API y de los modelos por el metodo getResourcesFromFolder de la clase APIModel. y por tanto no agrega los recursos añadidos por los plugins con el metodo ApiRoot::addCustomResource('xxxx');
- Por lo que hemos cambiado la propiedad $custom_resources a publica para poder acceder desde el EditApiKey y que aparezcan en el listado de permisos de recursos.
- De esta forma para una apikey …
=> agregar-custom_resources-a-EditApiKey

Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Base/AjaxForms/PurchasesController.php, Core/Base/AjaxForms/SalesController.php, Core/View/Tab/PurchasesDocument.html.twig, Core/View/Tab/SalesDocument.html.twig
- En el formulario de edición de facturas, en el botón impagado, cuando marcamos pagado, debería mostrar un modal donde podamos seleccionar la forma de pago y la fecha de pago (por defecto hoy). De esta forma podemos pagar con una forma de pago y fecha distinta a la actual, en un solo paso.
=> Tarea #2972 - agregar modal fecha y forma de pago

Core/Controller/EditRole.php, Core/View/Tab/RoleAccess.html.twig
- Actualmente en la pagina de asignar los roles, aparecen las paginas desordenadas y las que tienen submenu no aparecen agrupadas.
- Hemos ordenado el array $rules para que se ordene primero por nombre del menú, segundo por el nombre del submenu y por ultimo por el nombre de la página. De esta forma aparecen agrupadas las paginas que tiene el mismo submenu.
=> Tarea #3396 - agrupar paginas con el mismo submenu

Core/Lib/Vies.php, Core/Model/Agente.php, Core/Model/Cliente.php, Core/Model/Contacto.php, Core/Model/Empresa.php, Core/Model/Proveedor.php
En ocasiones necesitamos llamar al VIES y obtener solo el código de respuesta sin mostrar el mensaje, como el caso de Ticketbai.
=> Evitar mostrar el mensaje de respuesta del vies

Core/Base/AjaxForms/SalesLineHTML.php, Core/View/Tab/SalesDocument.html.twig
- $("#salesFormLines").sortable("option", "items", "> .fs-line");
con esto limitamos que los elementos ordenables dentro de #salesFormLines sean las líneas.
- $("#salesFormLines").sortable("option", "cursor", "move");
con esto mostramos el cursor del ratón con una cruz de movimiento cuando se están ordenando las líneas
- $("#salesFormLines").sortable("option", "cancel", "null");
- $("#salesFormLines").sortable("option", "cancel", ".titles");
con estas dos líneas evitamos que al pulsar sobre un input se habilite para poder escribir sin dejarnos ordenar. también evitamos que se pueda seleccionar la linea de titulos.
- $("#salesFormLines").sortable("option", "axis", "y");
con esto permitimos que se muevan las líneas solo en el eje y
- $("#salesFormLines .fs-line").css('cursor', 'grab');
- …
=> corregir ordenar lineas documentos

Core/Http.php
En ocasiones necesitamos poder enviar archivos en nuestras llamadas post, para eso necesitamos adjuntar el array con los datos, pero no debemos convertirlo. Con este cambio solucionamos el problema y damos la posibilidad de enviar CURLfile()
=> Permitir enviar archivos desde la clase Http

Core/Controller/ApiExportFacturaCliente.php, Core/Kernel.php
- Necesitamos poder generar el PDF de una factura desde la API. Para ello hay que añadir el endpoint ExportFacturaCliente a la API. Este endpoint debe cargar la factura indicada, generar el PDF y devolverlo.
=> Tarea #324 - agregar end point API ExportFacturaCliente

Core/Lib/OpenAi.php
Pequeña mejora para obtener los archivos guardado en openAI sin tener que estar comprobando en cada uso el parámetro data, la función ya devuelve el array de archivos preparado.
=> Mejora para devolver los archivos guardados en openAI

Core/Controller/Installer.php
- El instalador puede que no detecte la zona horaria y se quede en blanco, por lo que fallará después.
- Hemos incluido valores por defecto, para que en el caso que lleguen los valores del formulario en blanco, tome los valores por defecto y no genere errores en un futuro.
=> Tarea #1835 - agregar valores por defecto en instalador

Core/Lib/Widget/WidgetFile.php
El widgetFile ya recoge todos los archivos cargados desde el html, pero no existía la posibilidad de decirle que es un html file múltiple, con este cambio añadimos la posibilidad, ya que el guardado de archivos múltiples ya está implementado pero no se podía usar.
=> Permite crear un widget file múltiple

Core/Model/Producto.php, Test/Core/Model/ProductoTest.php
- Actualmente no se detectaba que existían cambios en una referencia de una variante cuando se comparaba por ejemplo `01 != 001`, y por lo tanto no se actualizaba la referencia en el producto.
- Usando la función `strcmp()` se comparan los dos string incluyendo los ceros a la izquierda.
=> Bug comparacion con ceros a la izquierda

Core/View/Macro/Toasts.html.twig
Es necesario añadir este nuevo tipo al Toast para cuando le pasamos directamente el mensaje del controlador que pueda interpretar correctamente el nivel.
=> Añadido nuevo tipo al Toast para las notificaciones

Core/Base/Calculator.php, Core/Controller/EditCliente.php, Core/Model/Cliente.php, Core/Table/clientes.xml, Core/XMLView/EditCliente.xml
[Tarea #2262](https://facturascripts.com/roadmap/EditTask?code=2262)
Cuando un cliente tiene un regimen exento el iva de las líneas en los documentos debe ser 0, no null. Además si el iva de la línea es 0, debería tener una excepción de iva, que se puede configurar en el producto, pero ahora también en el cliente.
=> Tarea #2262 - Añadida excepción de iva al cliente e impuesto 0 cuando es exento

Core/Lib/Widget/WidgetLibrary.php
- Al usar el WidgetLibrary carga todas las imágenes que se encuentren en la biblioteca en el modal aumentando la carga de la página.
- Usando lazy loading solo se cargan las imágenes cuando se el modal es visible y se van mostrando las imágenes. 
- De esta forma se evita cargar las imágenes en cada request si no es necesario hacer uso del Widget.
=> agregar lazy loading al WidgetLibrary

Core/View/Master/MenuBgTemplate.html.twig, Core/View/Master/MenuBghTemplate.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/PanelController.html.twig, Core/View/Master/PanelControllerTop.html.twig, Core/View/Tab/DocFiles.html.twig
Este cambio no afecta en nada que pueda fallar, pero si un plugin añade un gancho al twig y en su plugin ese gancho dentro tiene una variable llamada "item" igual a la variable del gancho del core eso es un problema ya que se suplantan, de este modo la variable del core tiene un nombre menos común y menos problemática.
=> Renombrada la variable para los ganchos de twig

Core/Model/Contacto.php
Corregido el problema donde, al crear un cliente o proveedor a partir de un contacto nuevo, no se estaba considerando el campo tipoidfiscal. Esto ocasionaba errores en la creación de clientes desde el módulo TPV. Ahora se garantiza que el tipoidfiscal se registre correctamente en todos los casos.
=> Fix: Contacto no incluye tipoidfiscal para clientes y proveedores nuevos

Core/Assets/JS/Custom.js, Core/Assets/JS/EditListView.js, Core/Assets/JS/ListView.js, package.json
La dependencia de bootbox de npm tiene una vulnerabilidad desde hace años que no van a solucionar según su creador, ya que no la considera una vulnerabilidad. Con este  cambio se usa el modal directamente de bootstrap.
=> Sustituido bootbox por el modal de bootstrap

Core/Tools.php, Test/Core/ToolsTest.php
Hay que corregir la función Tools::folder(). Esta función devuelve la carpeta de trabajo, y si le pasas carpetas como parámetro, las concatena. El problema es que si esas carpetas empiezan o terminan por /, les añade la barra igualmente al concatenar, por lo que terminas con una ruta con barras duplicadas. Debe quitar las barras al principio o final de las carpetas antes de concatenas.
=> Tarea #3506 - eliminar barra al inicio y al final

Core/Lib/Widget/WidgetSelect.php
El widgetSelect está guardando bien los datos, pero al pintar y marcar el option selected falla. No lo hace bien cuando el value del modelo, osea el dato que guarda es un booleano, ya que debe convertir el booleano a string para poder hacer correctamente la comparación. Este cambio es necesario cuando se introdujo la opción de múltiple.
=> Corregido bug al marcar el selected en el widgetSelect

Core/Model/Join/TarifaProducto.php
Desde EditTarifa la columna de nuevo precio de la tarifa no muestra nada, proque la columna que no existe en el modelo se debe añadir al joinModel para poder calcularla.
=> Corregido bug al mostrar el nuevo precio de la tarifa

Core/Controller/ApiRoot.php, Core/Controller/ApiUploadFiles.php, Core/Kernel.php
- Permite subir varios archivos a la vez o uno solo por la API.
- Los guarda en el directorio MyFiles y en la base de datos 
- devuelve un array con los campos del modelo AttachedFile de los archivos subidos.
- siempre, ya se envie uno o varios archivos, como nombre de parametro será `files[]`
=> add api endpoint uploadFiles

Core/DbQuery.php, Test/Core/DbQueryTest.php
- Los métodos max() y min() de la clase DbQuery devuelven siempre un float, pero en ocaciones queremos operar con cadenas, fechas o bien horas, por lo que hay que añadir los métodos maxString() y minString() que no hagan esta conversión a float que hacen los métodos max() y min().
=> Tarea #3501 - add maxString and minString

Core/Controller/ApiCreateFacturaRectificativaCliente.php, Core/Controller/ApiRoot.php, Core/Kernel.php
- Añadir un endpoint a la API para crear facturas rectificativas. Se le debe pasar por parámetro el id de la factura a rectificar, la fecha, el motivo y las cantidades de las líneas (si no se asignan cantidades, se debe asumir que es completa)
- Me queda la duda si estos campos tienen que ser opcionales, requeridos o el valor la factura anterior: codserie, nick y observaciones.
- Lo he implementado copiando el método \FacturaScripts\Core\Controller\EditFacturaCliente::newRefundAction() y adaptandolo a la API.
=> Tarea #3851 end point crear factura rectificativa

Core/Lib/API/APIModel.php
Cambios en el método setError() clase APIModel para devolver un status 404 en el caso de no encontrar el registro.
=> Devolver Status 404 en los métodos GET PUT DELETE

Core/View/Master/MicroTemplate.html.twig
- agregar padding a las alertas del login
ANTES:
DESPUÉS:
=> agregar padding a las alertas del login

Core/Assets/JS/WidgetAutocomplete.js
- actualizar valor del input en tiempo real sin strictmode
- ahora cuando el autocomplete se configura para que no sea estricto y se puedan añadir valores que no se encuentran en las opciones del select hay que pulsar sobre la opción que aparece por defecto cuando no encuentra ningún valor. esta opción el mismo valor que se ha escrito como busqueda. si no se pulsa sobre ese valor no se actualiza el valor y por tanto no se guardan los datos.
- para evitar este comportamiento y que el usuario pueda cambiar con tab o cambiar de foco a otro input conservando los valores introducidos como busque se ha implementado la actualización del valor del input en tiempo real siempre que strict=false.
=> actualizar valor del input en tiempo real sin strictmode

Core/Controller/EditProducto.php, Core/Controller/ListCliente.php, Core/Lib/Widget/WidgetDatalist.php, Core/Lib/Widget/WidgetSelect.php, Core/Model/AtributoValor.php, Core/Model/Base/ModelClass.php, Core/Model/Variante.php
Se actualizó el uso de `CodeModel::ALL_LIMIT` por `CodeModel::getLimit()` en varias clases para mejorar la flexibilidad del límite de registros. Además, se incrementó el límite de registros a 9999 en `EditProducto` para el select de atributos. También se actualizaron los años en los encabezados de copyright.
=> "Reemplaza ALL_LIMIT por getLimit en CodeModel"

Core/Lib/Widget/WidgetAutocomplete.php
- se estaba obteniendo el parámetro strict desde el child/values.
- ahora se obtiene desde la etiqueta del widget tal y como se indica en la documentación.
=> bug strict autocomplete

Core/View/Macro/Toasts.html.twig
- Se ha añadido un pequeño margen inferior para que no se encuentre pegado el final de la pagina.
- Se ha actualizado las clases a bootstrap 5.
- Se ha añadido un spinner que se mueve cuando se muestra el toast de carga
ANTES:
AHORA:
el spinner se mueve!!
=> actualizar spinner y toast

Core/Base/Controller.php
Ensure that users who have been deactivated are immediately logged out and cannot continue to navigate the application.
=> Fix: Prevent disabled users from browsing

Core/Lib/ExtendedController/ProductImagesTrait.php
Al parecer, al subir una imagen no se revisa la existencia de myFiles. Este parche soluciona ese problema.
=> Parche emergente para el bug de no poder subir imágen en product image.

Core/Lib/Widget/WidgetMoney.php, Core/Lib/Widget/WidgetNumber.php
Añadido un parámetro opcional a las columnas que usan widgets de tipo numérico (number y money) con el nombre de totals. Este parámetro permite indicar si se desea el cálculo de total de la columna en las vistas List.
Por defecto si no se indica se establece el actual estado:
- Los widgets number no calcula totales
- Los widgets money calcula totales
Si se informa true o false, se puede añadir o desactivar el cálculo de totales tanto porque se desee incluir el total o porque se desee desactivar el calculo por defecto.
<column name="quantity" display="right" order="150">
<widget type="number" fieldname="cantidad" totals="true"/>
</column>
<column name="price" display="right" order="170">
<widget type="money" fieldname="pvpunitario" totals="false"/>
</column>
Toda modificación debe haber …
=> Añadido parámetro totals

Core/View/Installer/Redir.html.twig
actualmente se pierde el botón cuando se cambia el tamaño de la pantalla. se ha modificado el tamaño y alineado de la imagen para que siempre se vea el botón.
https://github.com/user-attachments/assets/006ff71f-3148-4cdc-9062-e077186c73e3
=> corregir las dimensiones de la imagen

Core/Lib/ExtendedController/ListView.php
- En los listados ahora mantenemos los filtros si cambiamos de pagina.
=> Tarea #1918 - mantener filtros entre paginas
