NeoRazorX/facturascripts

composer.json, index.php
Asi evitas cargar cada clase con un require o include
=> Evitar cargar manual mente los componentes de FacturaScripts\Base

composer.json, i18n/es_ES.json, index.php, src/Models/Usuario.php, src/controller/usuario_test.php, view/usuario_test.html
Agregue el sistema orm con eloquent(illuminate/database 5.4 con soporte para php 5.6), lo probe con una base de datos ya existente de facturascripts funciona correctamente, agregue un ejemplo de consulta y de actualización, tambien se puede usar para generar un sistema de migraciones para la base de datos
=> Sistema orm con eloquent

Core/Translation/ca_ES.json, Core/Translation/de_DE.json, Core/Translation/en_EN.json, Core/Translation/es_ES.json, Core/Translation/fr_FR.json, Core/Translation/gl_ES.json, Core/Translation/it_IT.json
He creado los idiomas principales en España a falta del euskera que no lo controlo y el italiano y el francés.
=> Creación de idiomas

Core/Model/fsAccess.php, Core/Model/fsPage.php, Core/Model/fsRol.php, Core/Model/fsRolAccess.php, Core/Model/fsRolUser.php, Core/Model/fsUser.php
Sustituir $this->db x $this->database
Formatear nombres de los métodos a Camel Case.
Los mensajes se generan ahora con $this->miniLog->info(), warning(), critical(), etc...
Añadir clase en el namespace
Añadir uses de los clases
=> Sustituir $this->table_name x $this->tableName

Core/Base/PluginManager.php
Tarea: https://trello.com/c/cKDssDD0/19-optimizar-la-funci%C3%B3n-core-base-pluginmanagerdeploy
En la descripción en Trello preguntaba sobre que hago con el parámetro que he añadido en deploy, por eso estaba en "Revisar y aprobar", ya que puse el enlace para poderlo ver antes de hacer el commit.
=> Cambias para optimizar deploy

Core/Base/DataBase.php, Core/Base/DataBaseUtils.php, Core/Base/DatabaseEngine.php, Core/Base/Model.php, Core/Base/Mysql.php, Core/Base/Postgresql.php
Nuevo gestor de conexión a bases de datos, basado en el que existía. Añadido gestión de transacciones, aplicación de clases, separación y revisión de código.
=> Nuevo gestor de bases de datos

Core/Base/DataBase/DataBaseUtils.php, Core/Base/DataBase/Mysql.php, Core/Base/DataBase/Postgresql.php
- Había comparaciones contra tipo int
- Había conversiones explícitas a bool
=> Corregidas comparaciones estrictas con constantes que son de tipo string

Core/Table/empresa.xml, Core/Table/series.xml
No hay nada de código.
Simplemente cambios en los xml
=> Modificaciones a codserie 4 dígitos

Core/Base/DataBase/Mysql.php, Core/Base/DataBase/Postgresql.php
Corrige la creación de campos autonuméricos en MySQL y la ejecución de sentencias en PostgreSQL.
=> Corrección ejecución de sentencias

Core/Base/IPFilter.php
Creo que así se vería mejor.  No modifiqué el algoritmo.
=> Refactoring a la clase IPFilter

Core/Controller/AdminHome.php, Core/Model/AgenciasTrans.php, Core/Table/agenciastrans.xml, Core/View/AdminHome.html
Creación de una tabla de Agencias de Transportes
=> Creación de la tabla de agencias de transporte

Core/Model/GrupoClientes.php, Core/Model/Impuesto.php, Core/Model/LineaAlbaranCliente.php, Core/Model/LineaAlbaranProveedor.php, Core/Model/LineaFacturaCliente.php, Core/Model/LineaFacturaProveedor.php, Core/Model/LineaIvaFacturaCliente.php, Core/Model/LineaIvaFacturaProveedor.php, Core/Model/LineaTransferenciaStock.php, Core/Model/Partida.php, Core/Model/Proveedor.php, Core/Model/RegularizacionIva.php, Core/Model/RegularizacionStock.php, Core/Model/Stock.php, Core/Model/Subcuenta.php, Core/Model/SubcuentaCliente.php, Core/Model/SubcuentaProveedor.php, Core/Model/Tarifa.php, Core/Model/TerminalCaja.php, Core/Model/TransferenciaStock.php
=> Merge origin/master

Core/App/CronClass.php, Core/App/PluginClass.php
Entiendo que ambas deben de heredar en un futuro de Globals y que deberán de contener las particularidades referentes a las classes de tipo Cron y Plugin respectivamente, por lo que tendrán que ser ampliadas en un futuro.
=> Clases abstractas CronClass y PluginClass.

Core/Base/ExtendedController/WidgetItem.php, Core/XMLView/ListDivisa.xml
Corrección para que aplique correctamente el número de decimales y el pintado de options.
Ver ejemplo en ListDivisas
=> - Correcciones en visualización del formato number

Core/Base/ExtendedController/ListController.php, Core/View/Master/ListController.html, Documentation/ListController.md, Documentation/XMLViews.md
Se ha cambiado el botón de imprimir por un botón split que permite
tener una acción por defecto (imprimir) y un menú desplegable con
multiples opciones (imprimir, exportar xls, exportar csv)
=> - Sustituido botón de imprimir por un button split

Core/App/AppController.php, Core/Base/DataBase.php, Core/Base/ExtendedController/BaseView.php, Core/Base/ExtendedController/ColumnItem.php, Core/Base/ExtendedController/EditController.php, Core/Base/ExtendedController/EditView.php, Core/Base/ExtendedController/ListView.php, Core/Base/ExtendedController/PanelController.php, Core/Base/ExtendedController/WidgetItem.php, Core/Base/MenuItem.php, Core/Base/NumberTools.php, Core/Controller/EditFamilia.php, Core/Controller/EditTarifa.php, Core/Controller/PanelCliente.php, Core/Model/Base/Factura.php, Core/Model/Base/ModelTrait.php, Core/Model/Base/Persona.php, Core/Model/Tarifa.php, Core/View/Macro/BaseController.html, Core/View/Master/PanelController.html, Core/XMLView/EditCliente.xml, Core/XMLView/EditTarifa.xml, Core/XMLView/ListTarifa.xml, Documentation/XMLViews.md
Se actualiza las vistas de Tarifas con los últimos cambios.
Se corrigen el tratamiento de los ‘double precision’ en el Trait de
modelos a la hora de cargar los datos.
Se modifica la modificación de Clientes como prueba del funcionamiento
del PanelController.
=> - Correcciones en Tarifas y mejora del PanelController

Core/Base/ExtendedController/PanelController.php, Documentation/PanelController.md
Añadida documentación para el PanelController
=> - Mejora en la documentación

Core/Base/DataBase/DataBaseWhere.php, Core/Base/ExtendedController/BaseView.php, Core/Base/ExtendedController/EditListView.php, Core/Base/ExtendedController/PanelController.php, Core/Base/ExtendedController/RowItem.php, Core/Base/ExtendedController/WidgetItem.php, Core/Model/DireccionCliente.php, Core/Model/Settings.php, Core/View/Macro/BaseController.html, Core/XMLView/SettingsDefault.xml, Core/XMLView/SettingsPlantillaspdf.xml, Documentation/XMLViews.md
- Añadida la posibilidad de insertar nuevos registros desde las vistas
EditListView.
- Eliminado el campo “hidden” con nombre “primarykey” que se usaba para
identificar el registro que se guardaba. Ahora se usa el campo devuelto
por el modelo como primaryKey. Esto obliga a que el campo definido como
PrimaryKey de los modelos estén incluidos en la vista XML. Si no se
desea visualizarlos usar display=‘none’ para que se use como oculto.
=> - Mejora en PanelController

Core/Base/ExtendedController/ColumnItem.php, Core/Base/ExtendedController/EditController.php, Core/Base/ExtendedController/WidgetItemCheckBox.php, Core/Controller/EditAlmacen.php, Core/Controller/EditEjercicio.php, Core/Controller/EditSerie.php, Core/Lib/CSVExport.php, Core/Model/PageOption.php, Core/Translation/en_EN.json, Core/Translation/es_ES.json, Core/View/Master/EditController.html, Core/View/Master/PanelController.html, Core/XMLView/EditAlmacen.xml, Core/XMLView/EditEjercicio.xml, Core/XMLView/EditSerie.xml
- Completada tarea CSVExport, mantiene mucho estilo de código con XLSExport, para simplificar añadir cosas comunes.
- Completada tareas de EditAlmacen, EditEjercicio y EditSerie.
- Arreglos de algunas traducciones más, y más strings añadidas.
- En getPanelFooter() Si la cadena está vacía, se devuelve '' en lugar de la traducción de vacío.
- Modificado estilo del CheckBox en el Widget, para que sea igual que en los listados.
- En PageOption.php ocultados posibles errores con @, ya que es una situación controlada porqué devuelve false. Cuando hay controlador y todavía no hay XML, no saca errores.
- Cambiados los estilos de los botones atrás/recargar/marcar de "btn-light" por "btn-outline-secondary", no parecían botones visualmente.
=> Completadas 4 tareas, algunas mejoras más para la internacionalización y nuevo estilo del Widget de Checkbox

Documentation/EditController_EN.md, Documentation/EditController_ES.md, Documentation/ListController_EN.md, Documentation/ListController_ES.md, Documentation/PanelController_EN.md, Documentation/PanelController_ES.md, Documentation/Translations_EN.md, Documentation/Translations_ES.md, Documentation/XMLViews_EN.md, Documentation/XMLViews_ES.md
- Añadida leve explicación acerca de las traducciones.
=> Correcciones en la negrita de la Documentation

Core/Base/ExtendedController/WidgetItem.php, Core/Base/ExtendedController/WidgetItemCheckBox.php, Core/Model/Base/ModelTrait.php
Fixed recording of boolean fields
Fixed readonly property in WidgetItemCheckbox
=> Checkbox Corrections and Properties

Core/Base/ExtendedController/ListController.php, Core/Base/ExtendedController/ListView.php, Core/Controller/ListAlbaranCliente.php, Core/View/Macro/BaseController.html, Core/View/Master/ListController.html
Added the possibility of choosing the operator to use in the filters of
type datepicker
=> New filter system "from-to" in datepicker filters

Core/Controller/EditEstadoDocumento.php, Core/Controller/ListEstadoDocumento.php, Core/Model/EstadoDocumento.php, Core/Model/PageOption.php, Core/Table/estados_documentos.xml, Core/Translation/en_EN.json, Core/Translation/es_ES.json, Core/XMLView/EditEstadoDocumento.xml, Core/XMLView/ListEstadoDocumento.xml
Creación inicial del modelo EstadoDocumento y los controladores ListEstadoDocumento y EditEstadoDocumento con sus traducciones respectivas.
=> Creado modelo EstadoDocumento y controladores asociados.

install.php
Se agregó la funcion getUserLanguage para detectar el idioma del navegador y la función installerMain se le agregó que si no esta la variable fs_lang que use el valor de getUserLanguage()
=> fs2018: Tarea de detectar el idioma del usuario

Core/Base/ExtendedController/ListController.php, Core/Base/ExtendedController/ListView.php, Core/Controller/ListAlbaranCliente.php, Core/View/Macro/BaseController.html, Core/View/Master/ListController.html
Added possibility to filter by text
=> New TextInput type filter

Core/Controller/EditSubcuenta.php, Core/Model/Divisa.php, Core/Model/Subcuenta.php, Core/XMLView/EditSubcuenta.xml, Core/XMLView/ListSubcuenta.xml
editsubaccount xml is created and the test event of the model is modified to recalculate the idcuenta.
modified currency description for better understanding.
=> added view editsubaccount

README.md
- Add badge PR welcome (make friendly to new githubbers which wish send a pull request)
- Mark as project based in Symfony 3 (useful for spiders and search)
- Put a nice throughput graphic that aims to donations or patreon showing the hard work for contributors
=> Improve Readme with more badges

Core/Controller/PanelArticulo.php, Core/XMLView/EditArticulo.xml, Core/XMLView/ListArticulo.xml
Se añade PanelArticulo se modifica EditArticulo.xml para poder editar el stock fisico del articulo y se modifica ListArticulo.xml para que cuando hagan clic en alguno nos lleve a PanelArticulo.
=> PanelArticulo

Core/Controller/EditBalance.php, Core/Controller/EditCuenta.php, Core/Controller/EditProveedor.php, Core/XMLView/EditBalanceCuenta.xml, Core/XMLView/EditBalanceCuentaA.xml, Core/XMLView/EditCuentaBancoProveedor.xml
- Change EditCuenta from EditController to PanelController 
- Add EditLIstView to supplier controller
- Add view EditBalanceCuenta to EditBalance
=> Add EditLIstView to supplier controller,Add view EditBalanceCuenta to EditBalance, Change EditCuenta from EditController to PanelController 

Core/Controller/EditProveedor.php, Core/XMLView/EditProveedorArticulo.xml, Core/XMLView/ListArticuloProveedor.xml
Añadido el campo "refproveedor" en la vista para que no de errorees.
=> Articulos de proveedor.

Core/Controller/EditEpigrafe.php, Core/Controller/EditGrupoEpigrafes.php, Core/Controller/EditSubcuenta.php, Core/XMLView/ListEpigrafe.xml
- Change EditGrupoEpigrafes to PanelController
- Change ListEpigrafes to show idgrupo instead codgrupo
- Change EditSubcuenta to PanelController
=> - Change Editepigrafe to PanelController, Change ListEpigrafes to show idgrupo instead codgrupo, Change EditSubcuenta to PanelController

Core/XMLView/EditCuentaBancoCliente.xml
PR con la vista XML que faltó en el PR anterior
=> fs2018: Tarea de Añadir vista EditListView a EditCliente

Core/Controller/EditGrupoClientes.php
Convertir EditGrupoclientes en un PanelController, añadida otra vista con los clientes asociados.
=> Convertir EditGrupoclientes en un PanelController

Core/Model/ArticuloProveedor.php, Core/Model/CuentaBanco.php, Core/Model/Epigrafe.php, Core/Model/GrupoClientes.php, Core/Model/GrupoEpigrafes.php, Core/Model/Provincia.php, Core/Model/Rol.php
(copy the format in CuentaEspecial).
Only found 6 occurrences.
=> Update URL function in all models that use it, to use the simpler way

Core/App/AppAPI.php
Allows to use on API:
- For filters:
&filter[field1]=value1&filter[field2]=value2
To get a DataBaseWhere[] like array(2) { ["field1"]=> "value1" ["field2"]=> "value2" }
If has bad format, reassigned to empty array.
- For sort:
&sort[field1]=value1&sort[field2]=value2
To get an assoc array(2) { ["field1"]=> "value1" ["field2"]=> "value2" }
If has bad format, reassigned to empty array.
- For operation: by default use AND for any filter not specified.
&operation[field1]=value1&operation[field2]=value2
To get an assoc array(2) { ["field1"]=> "value1" ["field2"]=> "value2" }
If has bad format, reassigned to empty array.
=> Added param filter and sort as array, and operation

Core/Controller/EditDashboardCard.php, Core/Model/DashboardCard.php, Core/Table/dashboardcards.xml, Core/XMLView/EditDashboardCard.xml
- Created table structure dashboardcards.xml
- Created model DashboardCard
- Created XML view to edit DashboardCards and controller EditDasboardCard
=> Create DashboardCard model, to store the data of the cards to be displayed in the Dashboard.

Core/Controller/EditFamilia.php, Core/Translation/es_ES.json
Y añadir una vista (ListView) con el listado de artículos 
de esa familia.
=> Convertir EditFamilia en un PanelController, sin renombrar.

phpunit.xml
For run it: phpunit --configuration phpunit.xml
=> Enabled de PHPUnit Test.

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php
- Add ListFacturaCliente, ListAlbaranCliente, ListPedidoCliente and ListPresupuestoCliente to EditCliente.
- Add ListFacturaProveedor, ListAlbaranProveedor and ListPedidoProveedor to EditProveedor.
- Added the needed filters to loadData.
=> Task 185 & 186 add Lists to documents in EditCliente/EditProveedor

Core/Controller/EditAtributo.php, Core/XMLView/EditAtributoValor.xml
EditAtributo modified to be a PanelController in order to allow AtributoValor values. EditAtributoValor.xml XMLView created.
=> EditAtributo, converted from EditController to PanelController

Core/XMLView/EditArticulo.xml
Se agregó el xml en un grupo de 12 columnas para el campo observaciones
=> FS2018: Agregar campo observaciones a EditArticulo.xml

Core/Base/PluginManager.php
Se agregó una función privada scanFolders para revisar recursivamente una carpeta y devolver los archivos internos para aplicar en linkFiles()
=> FS2018: Modificar PluginManager::deploy() para recursividad

Core/Base/PluginManager.php
Se corrigió la busqueda, se agregó un comprobador de carpetas internas y se agregó el comprobador del nombre de la clase
=> FS2018: Corregir busqueda recursiva de directorios en PluginManager

Core/Base/ExtendedController/EditController.php, Core/Base/ExtendedController/PanelController.php, Core/Model/PageOption.php, Core/Model/Settings.php
Delete unused action insert
Translate Settings comments
=> Fix minor issues

Core/App/App.php, Core/App/AppAPI.php, Core/App/AppController.php, Core/App/AppCron.php, Core/App/AppSettings.php
- Refactorized Core/App/AppAPI method processResource.
=> PHPBlocks translations and added missing blocks.

Core/Base/DataBase/DataBaseEngine.php, Core/Base/DataBase/DataBaseSQL.php, Core/Base/DataBase/DataBaseTools.php, Core/Base/DataBase/DataBaseWhere.php, Core/Base/DataBase/Mysql.php, Core/Base/DataBase/MysqlSQL.php, Core/Base/DataBase/Postgresql.php, Core/Base/DataBase/PostgresqlSQL.php
- Some minor changes suggested by PHP-CS.
=> PHPBlocks translations and add some missing blocks for Core/Base/DataBase.

Core/Assets/CSS/datepicker.css, Core/Assets/CSS/phpdebugbar.custom-widget.css, Core/Assets/JS/datepicker.js, Core/Assets/JS/megasearch.js, Core/Assets/JS/phpdebugbar.custom-widget.js, Core/Base/DebugBar/TranslationCollector.php, Core/Lib/Import/CSVImport.php
- All others files on Core: Assets reformated.
- Some minor changes suggested by PHP-CS.
=> PHPBlocks translations and add some missing blocks for Core/Lib/Import.

Core/XMLView/EditAgenciaTransporte.xml, Core/XMLView/EditImpuesto.xml
core/xmlview/editagenciatransporte.xml
=> Añadir los campos telefono, web y activo a

Core/Lib/Export/CSVExport.php, Core/Lib/Export/ExportInterface.php, Core/Lib/Export/PDFExport.php, Core/Lib/Export/XLSExport.php
- Added some suggestions from PHP-CS.
=> Added new translations and missing PHPDoc blocks to Core/Lib/Export.

Core/Base/AssetManager.php, Core/Base/Cache.php, Core/Base/Controller.php, Core/Base/CronClass.php, Core/Base/DataBase.php, Core/Base/DivisaTools.php, Core/Base/IPFilter.php, Core/Base/MenuItem.php, Core/Base/MenuManager.php, Core/Base/MiniLog.php, Core/Base/NumberTools.php, Core/Base/Pagination.php, Core/Base/PluginManager.php, Core/Base/Translator.php, Core/Base/Utils.php, Core/Lib/ExportManager.php
- Added some suggestions from PHP-CS.
- Minor fix on PHPDoc var on Core/Lib/ExportManager.php
=> Added new translations and missing PHPDoc blocks to Core/Base.

Core/XMLView/EditSubcuenta.xml
impuesto, debe, haber y saldo se muestren en la línea de abajo, 
en lugar de en un bloque a ala derecha.
=> Mejorar diseño de core/xmlview/EditSubcuenta.xml para que divisa,

Core/Translation/en_EN.json, Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditPedidoCliente.xml, Core/XMLView/EditPresupuestoCliente.xml
como está en editAlbaranCliente.xml
Añadir todas las columnas faltantes a editPedidoCliente.xml, 
como está en editAlbaranCliente.xml
Además modificado vista de EditAlbaranCliente.xml para que este 
igual a las dos anteriores.
=> Añadir todas las columnas faltantes a editPresupuestoCliente.xml,

Core/App/AppAPI.php, Core/Base/DataBase/DataBaseTools.php, Core/Base/DataBase/DataBaseWhere.php, Core/Base/DataBase/Postgresql.php, Core/Controller/EditDashboardData.php, Core/Lib/RandomDataGenerator/ModelDataGenerator.php, Core/View/Macro/BaseController.html
- Added some suggestions from PHP-CS.
- Some little minor fixes on html (broken functionallity with the blank space)
=> - Added new missing PHPDoc blocks to some Core files.

Core/Base/ExtendedController/DocumentController.php, Core/Controller/Dashboard.php, Core/Controller/EditDashboardData.php, Core/Controller/EditFabricante.php, Core/Lib/Dashboard/BaseComponent.php, Core/Lib/Dashboard/ComponentInterface.php, Core/Lib/Dashboard/MessagesComponent.php, Core/Lib/Dashboard/TasksComponent.php, Core/Lib/Export/CSVExport.php, Core/Lib/Export/PDFExport.php, Core/Lib/Export/XLSExport.php
- Added new missing PHPDoc blocks or minor fixes to some Core files.
- Added some suggestions from PHP-CS.
- Some little minor fixes
=> More PHPDoc fixes from a clean repo.

Core/Base/ExtendedController/ColumnItem.php, Core/Base/ExtendedController/RowItem.php, Core/Base/ExtendedController/RowItemButtons.php, Core/Base/ExtendedController/RowItemFooter.php, Core/Base/ExtendedController/VisualItemLoadEngine.php, Core/Base/ExtendedController/WidgetButton.php, Core/Base/ExtendedController/WidgetItem.php, Core/Base/ExtendedController/WidgetItemNumber.php, Core/Base/ExtendedController/WidgetItemRadio.php, Core/Base/ExtendedController/WidgetItemSelect.php, Core/Model/PageOption.php
The load of visual elements is restructured by xml and json, and errors are corrected by changing the structure and application of new objects such as buttons, modal forms and footer panels
=> Refactoring PageOptions model and error correction

Core/Base/MenuManager.php, Core/Controller/EditRol.php, Core/Model/PageRule.php, Core/Model/RolAccess.php, Core/Model/User.php, Core/XMLView/ListPageRule.xml, Core/XMLView/ListRolAccess.xml
Added process of automatic insertion of page access permissions by group role
=> Add automatic insertion of page access by group role

Core/View/Master/ListController.html, Core/XMLView/ListAlbaranCliente.xml
Añadido para pruebas a ListAlbaranCliente.XML
=> ListController añadir Action y Modal a pie de página

Core/Lib/Export/CSVExport.php
- Completed generateTablePage function in CSVExport to load data to a csv file
=> fs2018: Task #230 Complete generateTablePage() function in CSVExport

Core/Model/User.php
- Traslated PHPDoc blocks on Core/Model/U*.
- Replaced references to vars with 0, 1, ... to var names on translatable strings.
=> Require approve PR 211

Core/Model/RegularizacionIva.php, Core/Model/RegularizacionStock.php, Core/Model/Rol.php, Core/Model/RolAccess.php, Core/Model/RolUser.php
=> Traslated PHPDoc blocks on Core/Model/R*.

Core/Model/GrupoClientes.php, Core/Model/GrupoEpigrafes.php
=> - Traslated PHPDoc blocks on Core/Model/G*.

Core/Model/Dashboard.php, Core/Model/DashboardData.php, Core/Model/DireccionCliente.php, Core/Model/DireccionProveedor.php, Core/Model/Divisa.php
=> Traslated PHPDoc blocks on Core/Model/D*.

Core/Model/Balance.php, Core/Model/BalanceCuenta.php, Core/Model/BalanceCuentaA.php
=> Traslated PHPDoc blocks on Core/Model/B*.

Core/Model/AlbaranCliente.php, Core/Model/AlbaranProveedor.php, Core/Model/ApiKey.php, Core/Model/Articulo.php, Core/Model/ArticuloCombinacion.php, Core/Model/ArticuloPropiedad.php, Core/Model/ArticuloProveedor.php, Core/Model/ArticuloTraza.php, Core/Model/Asiento.php, Core/Model/Atributo.php, Core/Model/AtributoValor.php
- Traslated PHPDoc blocks on Core/Model/A*.
- Replaced references to vars with 0, 1, ... to var names on translatable strings.
=> Require approve PR 211:

Core/Lib/Accounting/Ledger.php
El array se genera en el modelo Partida
=> Generar Libro Mayor.

Core/View/Macro/Forms.html
Added simpleInput and simpleSelect.
Usage example (twig):
{% import "Macro/Forms.html" as forms %}
{{ forms.simpleInput('testID', 'testNAME', value, 'text', i18n.trans('test label'), i18n, 'search', {'onChange': 'this.form.submit()'}) }}
{{ forms.simpleSelect('testID', 'testNAME', value, allValues, i18n.trans('test label'), i18n, NULL, {'onChange': 'this.form.submit()'}) }}
=> Task 'Create several macros (twig) for inputs and selects in core/view/macro/utils.html'

Core/Controller/DocumentReports.php, Core/View/DocumentReports.html
- Auto-filter by day/month/year.
- Removed date selector action.
- Deleted unneeded code added for initial sample.
=> Task 222: Modify documentReports.

Core/Base/DataBase.php, Core/Base/DataBase/DataBaseEngine.php, Core/Base/DataBase/DataBaseWhere.php, Core/Base/DataBase/Mysql.php, Core/Base/DataBase/Postgresql.php, Core/Base/ExtendedController/EditController.php, Core/Base/ExtendedController/EditView.php, Core/Base/ExtendedController/PanelController.php, Core/Model/Base/ModelTrait.php
A new operator has been added for regular expressions in the WHERE clause.
Now when calculating the new code, if a CAST to INTEGER is forced, a WHERE clause is added with a regular expression that forces the numerical values only.
=> Added calculation of code when add new record

Core/XMLView/ListProvincia.xml
Incorrect use of option and not needed here.
=> Fix suggested by José Antonio Cuello.

Core/Controller/EditEjercicio.php
subcuentas, cuentas y epígrafes sean ListView.
=> Modificar el controlador EditEjercicio para que las vistas de

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Controller/EditSubcuenta.php, Core/XMLView/EditSubcuentaCliente.xml, Core/XMLView/EditSubcuentaProveedor.xml
un cliente y un ejercicio con una subcuenta.
La vista debe ser de tipo EditListView, y se debe crear también 
su xmlview
Hay que hacer lo mismo en EditProveedor, 
con el modelo SubcuentaProveedor.
=> El modelo a utilizar es SubcuentaCliente, este modelo relaciona a

docker-compose.yml
Simplemente se levanta con 
`docker-compose up`
incluye Apache y Mysql User root Pass: passwd
=> Soporte para Docker

Core/Controller/AccountingReports.php, Core/Lib/Accounting/AccountingBase.php, Core/Lib/Accounting/BalanceSheet.php, Core/Lib/Accounting/ProffitAndLoss.php
=> Balance de Situación mejorado

Core/Base/PluginManager.php, Core/Controller/AdminHome.php
- Modificación Controlador AdminHome para simplificar código
=> - Unificar PluginManager con utilidades de descompresión y configuración

Core/Lib/ExtendedController/WidgetItem.php, Core/Lib/ExtendedController/WidgetItemFileChooser.php, Documentation/EN/XMLViews.rst, Documentation/ES/XMLViews.rst
Now you can indicate the maximum length of characters to a text type widget
=> Added maxlength property

Core/View/AccountingReports.html.twig, Core/View/AdminHome.html.twig, Core/View/Dashboard.html.twig, Core/View/DocumentReports.html.twig, Core/View/EditPageOption.html.twig, Core/View/Error/AccessDenied.html.twig, Core/View/Error/ControllerNotFound.html.twig, Core/View/Error/DbError.html.twig, Core/View/Error/TemplateError.html.twig, Core/View/Error/TemplateNotFound.html.twig, Core/View/Login/Login.html.twig, Core/View/Macro/BaseController.html.twig, Core/View/Macro/DocumentController.html.twig, Core/View/Macro/Forms.html.twig, Core/View/Macro/ListFilter.html.twig, Core/View/Macro/Utils.html.twig, Core/View/Master/DocumentController.html.twig, Core/View/Master/EditController.html.twig, Core/View/Master/ListController.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/MicroTemplate.html.twig, Core/View/Master/PanelController.html.twig, Core/View/Master/PanelControllerBottom.html.twig, Core/View/Master/PanelControllerTop.html.twig, Core/View/MegaSearch.html.twig, Core/View/Randomizer.html.twig, Core/View/Wizard.html.twig
Replaced all extends, import, from, and some strings refering to 'path/to/file.html' to 'path/to/file.html.twig'
=> Fixes for previous twig changes

Core/View/Macro/TasksComponent.html.twig
Now the text is displayed in standard color and type of task is marked by colored left edge.
=> Modified identification system in TaskComponent

Core/Base/PluginDeploy.php, Core/Base/PluginManager.php, Core/Controller/AdminHome.php, Core/Lib/DocumentCalculator.php, Core/Lib/Export/CSVExport.php, Core/Lib/Export/PDFExport.php, Core/Lib/Export/XLSExport.php, Core/Lib/ExtendedController/DocumentView.php
- Added some missing or uncompleted PhpDoc blocks.
- Removed calls to Base\Utils as Trait.
- Removed some "/// TODO: Uncomplete" from completed methods.
- Solved a pending TODO that can occur on very strange cases (bad user manipulation).
=> Minor changes

Core/Base/Controller.php, composer.json, config/bundles.php, config/routes/annotations.yaml
First small merge for continue transition with Symfony Controllers
=> Symfony controller

.gitignore, composer.json, config/bundles.php, config/packages/dev/monolog.yaml, config/packages/prod/monolog.yaml, config/packages/test/monolog.yaml, config/packages/translation.yaml, config/services.yaml, phpunit.xml.dist
Enable monolog for future use via controllers using symfony bridge
=> Enable monolog symfony bridge and config

Core/Controller/Dashboard.php, Core/Controller/DocumentReports.php, Core/View/Dashboard.html.twig, Core/View/Macro/InfoStateComponent.html.twig, Core/View/Macro/MessagesComponent.html.twig, Core/View/Macro/TasksComponent.html.twig
Fix parent constructor call into Dashboard and Document Report controllers
=> Fix constructor error

Core/Controller/ListAgente.php, src/Controller/AgentController.php
This is a quick fix for issue #299
=> <bugfix> Fix the use of list reserver keyword error

Core/Lib/Accounting/AccountingPlanImport.php
Modificado para unificar la importación de epígrafes en la tabla cuentas
=> Accountplanimport

Core/App/AppInstaller.php
=> <bugfix> Fix issue #310 with create folder

Core/Assets/JS/accountingEntry.js, Core/Controller/EditAsiento.php
Now check that new subaccount change of last subaccount calculate for minor AJAX calls.
Now not refresh data account if editing any column.
=> Fix load account data when editing

Test/bootstrap.php
Little change to fix execution on Travis for any user, not only to NeoRazorX Travis related account.
=> Fix for travis

Core/Lib/AssetManager.php
Fix the error when running on local server to try to load files by local file path and not by url
=> Issue on path at load local files

Core/Assets/JS/accountingEntry.js, Core/Assets/JS/gridController.js, Core/Controller/EditAsiento.php, Core/Lib/ExtendedController/BaseView.php, Core/Lib/ExtendedController/GridDocumentInterface.php, Core/Lib/ExtendedController/GridView.php, Core/Model/Asiento.php, Core/Model/Partida.php, Core/Model/Subcuenta.php, Core/Table/partidas.xml, Core/View/Macro/BaseController.html.twig, Core/XMLView/EditAsiento.xml
- Now can save accounting entries lines.
- New event manager for controle events in GridController.js
- Restructure Partidas table for controller user order
- Restructure visibility of i18n attribute in BaseView
=>  New version Accounting Entry & Minors Fixes

Core/Table/familias.xml
When the user delete a family, change to null field "madre" of childs famililys though foreign key
=>  On family delete update child families (Pull revision)

Core/Lib/ExtendedController/WidgetItem.php
Supress Id tag in standardEdiHTMLWidget
=> Widgetitem. Supress id.

Core/Assets/JS/EditAsiento.js, Core/Assets/JS/gridController.js, Core/Controller/EditAsiento.php, Core/Lib/ExtendedController/PanelController.php, Core/Lib/ExtendedController/WidgetButton.php, Core/View/EditAsiento.html.twig, Core/View/Macro/BaseController.html.twig, Core/View/Master/GridController.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/PanelController.html.twig, Core/XMLView/EditAsiento.xml, Core/XMLView/EditPartida.xml
Add onclick event to actions buttons
Refactorize accounting entries and generalize code
=>  Update Accounting Entries & WidgetButton fixed

Core/Controller/Randomizer.php, Core/View/Randomizer.html.twig
To have an easy way to see the total generated items per model.
=> Added total counter to each generate button

Core/Base/MenuManager.php
Solved by @NeoRazorX on Slack.
=> Fix: Added needed params to obtain the correct list of pages for the user.

Core/Lib/RandomDataGenerator/Articulos.php, Core/Model/Articulo.php, Core/Model/Stock.php, Core/Table/articulos.xml, Core/Table/stocks.xml, Core/XMLView/EditArticulo.xml, Test/Core/Model/ArticuloTest.php, Test/Core/Model/StockTest.php
Remove certain inherited fields that have no use.
=> Elimination of legacy fields without use in tables Articulos and Stocks.

Core/Assets/JS/EditAsiento.js, Core/Assets/JS/gridController.js, Core/View/Macro/BaseController.html.twig, Core/View/Master/GridController.html.twig, Core/XMLView/SettingsEmail.xml, package.json
Now when entering an accounting subaccount, the columns with the data of the previous entries and with the data obtained from the subaccount are filled in.
=>  New accounting entries version. Add initial data to new entries

Core/Table/contactosclientes.xml, Core/Table/contactosproveedores.xml
Founded testing https://github.com/shawe/FS2018_order_xml_tables
=> Fixed: Updated tags from table definitions

Core/Model/GrupoClientes.php, Core/Table/contactosclientes.xml, Core/Table/contactosproveedores.xml, Core/Table/gruposclientes.xml, Core/Translation/en_EN.json, Core/XMLView/EditGrupoClientes.xml, Core/XMLView/ListGrupoClientes.xml
- Added madre column to table.
- Added select field for views.
- Avoided to set a circular mother group families.
=> Trello task 318: Added support multi-level customer groups.

Core/Model/Base/ModelClass.php
Now the loop is not performed by searching the field configuration data.
=> Optimize newCode function

package.json
=> Upgrade bootStrap 4 to BootStrap 4.1.0

Core/View/DocumentReports.html.twig, Core/View/EditAsiento.html.twig, Core/View/Master/BusinessDocumentController.html.twig, Core/View/Master/GridController.html.twig, Core/View/Master/ListController.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/MicroTemplate.html.twig, Core/View/Master/PanelController.html.twig, Core/View/MegaSearch.html.twig, Core/View/Randomizer.html.twig, Core/View/SendMail.html.twig
Seems that PhpStorm have some problem parsing blocks when have this old name, founding false positive problems and breaking code with autoformat.
=> Renamed from Twig javascript to javascripts, to avoid problems in PhpStorm

Core/Assets/JS/EditAsiento.js, Core/Assets/JS/gridController.js, Core/Controller/EditAsiento.php, Core/Lib/ExtendedController/GridView.php, Core/Lib/ExtendedController/WidgetButton.php, Core/XMLView/EditPartida.xml
Add clone process.
Fix resave accounting entry when save button is pressed.
Fix reload url when save data.
Add save ok message when clone or save document process it's ok.
=> Add Clone accounting entry

Core/Lib/ExtendedController/ListController.php, Core/Model/PageOption.php
Now you can implement the same xml view several times, identifying each of the common views with the suffix '-'.
The data load of the ListController is also separated from a protected loadData method that allows the data load of the listview views to be customized.
=> View the same view multiple times

Core/Controller/SendMail.php
This function removes .pdf files older than one hour (3600 seconds) generated by the SendMail Controller.
=> Trello task 332 (Complete function removeOld() from Core/Controller/SendEmail.php)

Core/APIResource/Base/APIResourceClass.php, Core/APIResource/Calculate.php, Core/App/AppAPI.php, Core/Base/PluginDeploy.php
=> API Extended

Core/Controller/EditAttachedFile.php, Core/Controller/ListAttachedFile.php, Core/Model/AttachedFile.php, Core/Table/attached_files.xml, Core/Translation/en_EN.json, Core/XMLView/EditAttachedFile.xml, Core/XMLView/ListAttachedFile.xml
Added edit and list controller
=> Added model class to manage attached files

Core/Model/Base/ModelClass.php
also fix some posible checks for data providing from API that always was string
=> Added basic and generic test for all models

Core/Lib/Export/PDFExport.php, Core/Translation/en_EN.json
- Added methods insertHeader and insertFooter
- Added as comment samples for use top center, top right, bottom left and bottom center
- Added method getCompanyName, if id is received, return its name, if not returns default company name
- Moved some values to constant
=> Inserts on header and footer details on generate PDF (Trello task 324)

Core/XMLView/EditConceptoPartida.xml
Referenced names in the footer were changed, this change fixes the issue
=> Changed 'title' and 'label' in EditConceptoPartida footer to match new names

Core/App/AppInstaller.php, Core/Controller/AdminPlugins.php, Core/View/AdminPlugins.html.twig
- Added constant FS_HIDDEN_PLUGINS to config.php generation
- Additional added that can be getted from request, with default empty array and imploded with "|"
- Added method to AdminPlugins controller to return all installed plugins removing the hidden ones
**Note:** New warning added to PHP, from now it only affects in all config in development.
> Warning: Use of undefined constant FS_HIDDEN_PLUGINS - assumed 'FS_HIDDEN_PLUGINS' (this will throw an Error in a future version of PHP)
- `Added` (non-breaking change which adds functionality)
=> Added posibility to hide plugins (Trello trello task 341)

Core/Controller/ListAlbaranCliente.php, Core/Controller/ListAlbaranProveedor.php, Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Controller/ListPedidoCliente.php, Core/Controller/ListPedidoProveedor.php, Core/Controller/ListPresupuestoCliente.php, Core/Controller/ListPresupuestoProveedor.php, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml
Add views to Panel controller of documents to show lines and filters to filter by lines of documents.
- `Added` (non-breaking change which adds functionality)
=> Add tab to document list to be able to search by lines.

Core/View/Macro/BaseController.html.twig
Add footers card information when is a ListView
=> Add HTML File include into footer row

Core/View/Master/PanelControllerBottom.html.twig
Add footers card information when is a ListView
=> Add footer cards to ListViews into PanelControllerButtom

Core/Controller/EditCliente.php, Dinamic/Lib/ExtendedController/BaseView.php
Added list view on EditCliente to show the last lines of receipts about his customer.
=> Added ListLineaFacturaCliente on EditCliente Controller

Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml
Added red color to pvptotal when cost is smaller than 0
=> Added red color to pvptotal when cost is smaller than 0

Test/Core/Base/FileManagerTest.php
=> Added initial tests to FileManager

Core/Model/Cuenta.php, Core/Model/Ejercicio.php, Core/Model/Subcuenta.php
Fix error when test process call to clear method
=> Fix Clear error into test

Core/Lib/ExtendedController/WidgetButton.php, Core/XMLView/EditCliente.xml
Now the function tag can be used to indicate the method of controller that calculates a button of the statistical row.
=> Change action tag for function tag into row statistics

Core/Controller/SendMail.php, Core/View/SendMail.html.twig
Added input to upload a file on SendEmail and improve the code on SendEmail controller adding a new funtion to get emails. 
The function improve reading about code.
=> Add optin attachment

Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/PanelController.php, Core/View/Master/ListController.html.twig
Moved Settings options to BaseController and implement into ListController.
Trello task:
https://trello.com/c/AMGvVmtV/353-cambiar-listcontroller-para-que-en-lugar-de-usar-la-propiedad-icons-use-settings-como-panelcontroller-y-mover-settings-a-basecon
=> Add Settings to ListController

Core/Controller/EditAsiento.php
Create macros in the autocomplete of seats concepts in entry seats module
- [ X] MySQL
=> Create macros in the autocomplete of seats concepts in entry seats module

Core/Assets/JS/EditAsiento.js, Core/Controller/EditArticuloProveedor.php, Core/XMLView/EditAgenciaTransporte.xml, Core/XMLView/EditAlbaranProveedor.xml, Core/XMLView/EditArticuloProveedor.xml, Core/XMLView/EditAtributoValor.xml, Core/XMLView/EditDivisa.xml, Core/XMLView/EditFacturaProveedor.xml, Core/XMLView/EditPartida.xml
Change incorrect columns name for names with correct translate.
=> Fix colums name to correct translation

Core/XMLView/EditRoleAccess.xml, package.json
Translate title into widget select pages.
=> Fix roles rules

Core/Controller/SendMail.php
Added original name to attachments files on SendEmail Controller.
=> Send files attachment with its original names

Core/App/AppInstaller.php, Core/Base/PluginManager.php, Core/View/AdminPlugins.html.twig, Test/config-scrutinizer.php, Test/config-travis.php
- **Core/App/AppInstaller:** Reads FS_DISABLE_ADD_PLUGINS/FS_DISABLE_RM_PLUGINS values from POST or sets to false
- **Note:** FS_DEBUG can be moved to same new foreach to group by default type
- **Added:** *@noinspection* to phpinfo because its willfully here, don't analyze it (for code analyzers like [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), [php-md](https://phpmd.org) and others to avoid warnings with false "forgotten debug statement")
- **Added:** Fix for second chmod parameter forced to int as expected (Solve scrutinizer bug)
- **Core/Base/PluginManager.php:** Disable install/remove function if respective constants are setted to true
- **Added** missing PhpDoc argument
- **Removed** unnecessary use because it's on same namespace
- **Removed** unnecessary blank …
=> Added support for constants FS_DISABLE_(ADD/RM)_PLUGINS

Core/Controller/SendMail.php, Core/View/SendMail.html.twig
If modelClassName exists and have property class codproveedor, search on **proveedores**
If modelClassName not exists or have property class codcliente, search on **clientes**
=> Added support to send emails to suppliers

Core/Controller/ListCliente.php, Core/Controller/ListProveedor.php, Core/Translation/en_EN.json, Core/XMLView/ListDireccionCliente.xml, Core/XMLView/ListDireccionProveedor.xml
The address view in clients and suppliers has been added to be able to search by their descriptions, addresses and countries.
=> View address added customers and suppliers

Core/Controller/EditCliente.php, Core/XMLView/EditCliente.xml
Suppress statistic button in EditCliente->Accounting Risk
=> Accounting Risk

Core/Assets/JS/PanelController.js, Core/Lib/ExtendedController/PanelController.php, Core/View/Master/PanelController.html.twig
Separated the JavaScript code from the Panel Controller template to a separate file.
Add Settings variable to JS
=> Add settings variable and JS external file

Core/Controller/EditDiario.php, Core/Controller/ListAsiento.php, Core/Model/Asiento.php, Core/Model/Diario.php, Core/Table/asientos.xml, Core/Table/diarios.xml, Core/XMLView/EditAsiento.xml, Core/XMLView/EditDiario.xml, Core/XMLView/ListAsiento.xml, Core/XMLView/ListDiario.xml
It allows grouping accounting entries in journals
=> Add grouping by journal to accounting entries

Core/Controller/ListCliente.php, Core/Controller/ListProveedor.php
Added select filter of provinces, cities and countries on ListCliente and ListProveedor controller.
=> Added Filter select on ListCliente and ListProveedor controller

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php
Modified function calcSupplierInvoicePending to calculate over non-payment invoice on EditProveedor and EditClient controller.
=> Calc over unpaid receipt

Core/Lib/Export/PDFExport.php, Core/Model/Base/InvoiceTrait.php, Core/Translation/en_EN.json
Minor visual improvements to match invoice style.
=> Changed style for PDF generation of business documents

Core/Lib/ExtendedController/ListController.php, Core/XMLView/EditPartida.xml, Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml, Core/XMLView/ListPartidaImpuesto.xml, Core/XMLView/ListPartidaImpuestoResumen.xml
Specify on method addOrderBy that fields param is only array.
If that param is not an array the program throw error.
=> Add order by only array

Core/XMLView/EditPartida.xml, Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml, Core/XMLView/ListPartidaImpuesto.xml, Core/XMLView/ListPartidaImpuestoResumen.xml
Change name tag of xml from %-surcharge or pct-surcharge to only surcharge.
=> Change name tag of xml

Core/App/AppAPI.php, Core/Lib/API/APIModel.php, Core/Lib/API/Base/APIResourceClass.php
Modification of API for inclusion of X-Auth-Token token and support of PUT and POST according to the standard.
=> Modification of API for use according to the standard.

Core/Controller/EditRegularizacionImpuesto.php, Core/Model/RegularizacionImpuesto.php, Core/Model/Subcuenta.php, Core/View/Master/PanelController.html.twig
In PanelController  on select event don't assign the key value on the correct inputtext html control.
Example: EditRegularizacionImpuesto. Select key subaccount from credit and debit subaccount.
EditRegularizacionImpuesto. Search key of account, should search key of subaccount.
- [ X] MySQL
=> Autocomplete issue in PanelController

Core/Lib/Export/PDFExport.php
Added delibery section on print documents when direccionenv is fill.
=> Added delibery section when direccionenv is fill

Core/Controller/ListApiKey.php, Core/Controller/Wizard.php
Show message api disable when the option "enable_api" is false
=> Show api disable message

Core/Controller/EditRegularizacionImpuesto.php
Order alphabetizing all method and move each code to corresponding method.
=> Refactoring load data edit regularizacion impuesto

package.json
Upgrade handsontable version to 4.0. 
Need run 'npm install handsontable' to apply upgrade to FS Developer folder
=> Upgrade handsontable version

Core/Lib/Export/PDFExport.php
Added surcharge and irpf when print a document.
New branch to solved problem with dinamic files.
=> Added surcharge and irpf when print a document

Core/Controller/Wizard.php
Auto-enable all available log types to be stored
=> [Trello Task 415] Updated Wizard for auto-enable store logs

Core/Lib/ExtendedController/GridView.php
Add new type column to cell of GridView
=> Add Select column type to GridView

Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditFacturaCliente.xml, Core/XMLView/EditPedidoCliente.xml, Core/XMLView/EditPresupuestoCliente.xml
Change value tag name, move codecountry to last position and added select widget of country.
=> Change country xml

Core/Lib/Export/PDFExport.php
Added function to get name of divisa using code and use it instead of code.
=> Added function to get name of divisa using code

Core/Model/Variante.php, Core/Table/variantes.xml
Added xml to define the article table definition and added its corresponding model.
=> Create model and table article

Core/Model/Contacto.php
Added password on contact model.
=> Added password on contact model

Core/Lib/Export/PDFCore.php
- Based on https://github.com/NeoRazorX/facturacion_base/blob/master/extras/fs_pdf.php#L146
- Logo placed at Top Right to not loose lines (not tested with another logos)
=> Added support to print logo on PDF files

Core/Controller/Wizard.php
- Because Wizard can be re-accessed, I added to condition described "and not yet enabled", to not re-insert existing unique key values and also avoid miss access to new added pages
**NOTES:**
- [Core/Controller/EditUser.php L79](https://github.com/NeoRazorX/facturascripts/blob/master/Core/Controller/EditUser.php#L79), needs limit to 0 and not to 500
- [Core/Model/RoleUser.php L79](https://github.com/NeoRazorX/facturascripts/blob/master/Core/Model/RoleUser.php#L79), needs after $filter this: "_, ['pagename' => 'ASC'], 0, 0_", if not is returning first 50 pages only
=> Update Wizard controller to create role with full access to all pages that are not in admin menu [Trello task 408]

Core/Controller/EditArticulo.php, Core/Model/Articulo.php, Core/Model/Variante.php, Core/Table/variantes.xml, Core/Translation/en_EN.json, Core/XMLView/EditVariante.xml
- Added dependency on Articulo to Variante, and Variante to AtributoValor (to not have missing required table dependencies)
- Updated constraint on delete product, propagate the deletion
- Added new strings
=> Added XMLView/EditVariante.xml and added to EditArticulo controller [Trello task 440]

Core/Base/FileManager.php
Exclude .DS_Store in scanFolder function
=> Exclude .DS_Store in scanFolder function

Core/Model/CronLog.php, Core/Table/cronlogs.xml
- Allow store what plugin was executed and when
=> Added table and model for cronlogs [Trello task 456]

Core/Lib/Export/PDFCore.php, Core/Lib/Export/PDFDocument.php, Core/Lib/Export/PDFExport.php
Pass functions directly called in PDFExport to PDFDocument.
=> Create class pdf document

Core/Model/Subcuenta.php
Order method and properties on subcuenta model
=> Order model subcuenta

Core/Controller/Wizard.php, Core/View/Wizard.html.twig
Check on Wizard controller if user and password are admin and show two inputs to specify the new password and a box info.
=> Wizard password

Core/Base/CronClass.php, Core/Model/CronJob.php, Core/Table/cronjobs.xml, Core/Translation/en_EN.json
- Added methods isTimeForJob and jobDone to Core/Base/CronClass.php
- Rename cronlog to cronjob
=> Update table and model CronLog to specify cron jobname (Trello task 469)

Core/Data/Lang/ES/almacenes.csv
Added column idempresa on almacenes.csv and assign idempresa on default data.
=> Specify idEmpresa

Core/Lib/Export/PDFExport.php
Create function to combine address depend of parameters on PDFExport.
=> Create function to combine address.

Core/Model/DocTransformation.php, Core/Table/doctransformations.xml
Create table and model to storage all transformations of a document, for example the transformation of a aprobed order to delivery note.
=> Create table and model for doc transformation

Core/Controller/EditFacturaCliente.php, Core/Controller/EditFacturaProveedor.php
Adding accounting entries in EditFacturaCliente and EditFacturaProveedor controllers.
=> Modify EditFacturaCliente and EditFacturaProveedor controllers

Core/Controller/Randomizer.php, Core/Translation/en_EN.json
- Message to notify user that is still working, and how to stop it
=> Added message to Randomizer when is generating more items (Trello task 474)

Core/Controller/EditImpuestoZona.php, Core/Controller/ListImpuesto.php, Core/Model/ImpuestoZona.php, Core/Model/Retencion.php, Core/XMLView/EditImpuestoZona.xml, Core/XMLView/ListImpuestoZona.xml
The Zonas tab is added to the ListImpuesto controller to show the ImpuestoZona model.
The EditImpuestoZona controller is added for the maintenance of the ImpuestoZona model.
=> Taxes. Adding Zonas tab (Task 479)

Core/Model/ImpuestoZona.php, Core/XMLView/EditImpuestoZona.xml, Core/XMLView/ListImpuestoZona.xml
Fix default value for priority and select for country, province and tax.
=> Fix default values and select fields in ImpuestoZona

Core/Controller/DocumentStitcher.php, Core/Translation/en_EN.json, Core/View/DocumentStitcher.html.twig
- From a document, using the dropdown for change status, send model and codes to DocumentStitcher
- Load de document/s by model and codes values to render a list of documents/lines to select the lines, each document lines are grouped in a card that contains a table with all lines
NOTE: The selected lines can generate a new document, maybe this part will be rewrited in another related task.
=> Added controller and view for DocumentStitcher [Trello task 466]

Core/Model/Producto.php, Core/XMLView/EditProducto.xml, Core/XMLView/SettingsDefault.xml
Se ha añadido el widget ventasintock a EditProductos.xml y se ha modificado el modelo Productos para que ventasinstock recupere el valor de las preferencias de la app
=> Añadido ventasinstock al modelo productos y a EditProducto.xml

Core/Controller/EditCliente.php, Core/Controller/ListContacto.php, Core/Model/Contacto.php, Core/Table/contactos.xml, Core/XMLView/EditContacto.xml
Add field codcliente to contactos table.
Add widget select to edit view contacto.
Add contactos list view to cliente edit view.
---
**Things that have detected or interesting to apply**
- The client select widget only shows 50 records so the client can not be selected correctly.
- Perhaps the widget to select the client can be changed by an autocomplete.
- Add customer filter in Contacto list view.
---
**Tested**
=> Add codcliente to Contacto model

Core/Controller/EditDashboardData.php, Core/View/Macro/MessagesComponent.html.twig, Core/View/Macro/TasksComponent.html.twig, Core/XMLView/EditDashboardData.xml
Modify Dashboard page to permit insert task and Messages
MySQL
=> Insert task an messages in Dashboard

Core/Controller/EditTransferenciaStock.php, Core/Model/LineaTransferenciaStock.php, Core/Model/TransferenciaStock.php, Core/Table/lineastransferenciasstock.xml, Core/Table/transferenciasstock.xml, Core/XMLView/EditLineaTransferenciaStock.xml, Core/XMLView/EditTransferenciaStock.xml, Core/XMLView/ListTransferenciaStock.xml
Rename idtransferhead for idtrans and delete unnecesary method install on model.
Added creaction of model variante because lineatransferenciastock table need it
So, added return on method install on model LineaTransferenciaStock
=> Fixed transfer stock

Core/Lib/RandomDataGenerator/Contactos.php
- Fixed error with codagente and codcliente
- Fixed randomIp
=> Fixes generation with empty database [Trello task 496]

Core/Controller/ListImpuesto.php, Core/XMLView/EditImpuestoZona.xml, Core/XMLView/ListImpuestoZona.xml
Taxes are configured to be able to select country and province for each defined tax.
A visual readjustment is made.
New ordering areas of the tax zones are included.
=> Fix EditImpuestoZona.xml (Trello Task 489)

Core/Controller/ListTransferenciaStock.php, Core/Model/TransferenciaStock.php, Core/XMLView/EditTransferenciaStock.xml
Added method clear on model TransferenciaStock to assing actual date and time.
Sepecify that warehouse origin and warehouse destination are required. Added condition that them can´t be equals.
And, added filters autocomplete for users and date filter to date.
=> Added functions on model and filters on controllers to Transfers stock

Core/Lib/RandomDataGenerator/AbstractRandomPeople.php, Core/Lib/RandomDataGenerator/Contactos.php
- Added null coalesce to avoid crash when is and empty array
- Fixed property from agentes array
- Updated generation of emails to reduce duplicates
=> Error on contact random generation [Trello task 496]

Core/Model/Contacto.php, Core/Table/contactos.xml, Core/XMLView/EditContacto.xml
- Changed email as not required
- Added domenvio and domfacturacion (default value to false)
=> Update Contacto [Trello task 500]

Core/Model/Contacto.php, Core/Table/contactos.xml, Core/XMLView/EditContacto.xml
=> Removed fields domenvio and domfacturacion

Core/Model/Base/BusinessDocumentLine.php, Core/Table/lineasalbaranescli.xml, Core/Table/lineasalbaranesprov.xml, Core/Table/lineasfacturascli.xml, Core/Table/lineasfacturasprov.xml, Core/Table/lineaspedidoscli.xml, Core/Table/lineaspedidosprov.xml, Core/Table/lineaspresupuestoscli.xml, Core/Table/lineaspresupuestosprov.xml, Core/XMLView/BusinessDocumentLine.xml, Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml
Added servido field to all lineas*.xml table files (except lineastransferenciasstock.xml)
Added servido field to model BusinessDocumentLine.php.
Added servido field to all lineas*.xml view files (deprecated, can be removed?)
Added servido field to BusinessDocumentLine (it replaces the previous)
TODO: The calculations are made on quantity, not over served.
=> Add column served (servido) in document lines. (Trello task 504)

Core/Model/FormaPago.php, Core/Table/formaspago.xml, Core/XMLView/EditFormaPago.xml, Core/XMLView/ListFormaPago.xml
Modify model FormaPago and table for storage expiration with more options.
Added two attributes "tipovencimiento" and "vencimiento" on model and its corresponding columns on table and xml views.
=> Modify model FormaPago to changed method for define period of expiration

Core/Lib/Export/PDFExport.php, Core/XMLView/EditAlbaranCliente.xml, Core/XMLView/EditFacturaCliente.xml, Core/XMLView/EditPedidoCliente.xml, Core/XMLView/EditPresupuestoCliente.xml
- Fixed minor related issue on views Edit*Cliente.xml, where idcontactenv was never used by mistake
=> Updated PDFExport to show address from a contact for shipping address [Trello task 513]

Core/Model/User.php
- Old password can be used to login and re-hash with new encription method.
=> Add support for old login hash

Core/Controller/ListLogMessage.php, Core/XMLView/ListCronJob.xml
Create ListCronJob with all columns necesaries and added function to create tab cron on ListLogMessage controller
=> Added tab crons to view all cronjobs.

Core/Lib/BusinessDocumentTools.php
the method to obtain the detail by tax of a document is raised to be able to use it from different places of the application.
=> Modif getSubtotals: private to public function

Core/Controller/ListCuenta.php
Added select filter on ListCuenta to filter by Specials accounts.
=> Added select filter on ListCuenta

Core/Base/DataBase/Postgresql.php
Set date format to recommended Postgrest documentation.
Fix date error in Postgresql 9.6
=> Fix date format in Postgresql to ISO

Core/Model/Asiento.php, Core/Model/Partida.php, Core/Model/Subcuenta.php, Core/Model/SubcuentaSaldo.php, package.json
Update same packages to last versions
=> Update Packages version

Core/Model/Asiento.php, Core/Model/Familia.php, Core/Model/Partida.php, Core/Model/Subcuenta.php, Core/Model/SubcuentaSaldo.php, Core/Table/familias.xml, Core/XMLView/EditFamilia.xml, package.json
Added accounting sub-accounts to the family model to be able to account for product families.
=> Add Subaccount to Family Model

Core/Controller/ListAsiento.php, Core/Model/Asiento.php, Core/Model/Partida.php, Core/Model/Subcuenta.php, Core/Model/SubcuentaSaldo.php, Core/Table/asientos.xml, Core/XMLView/EditAsiento.xml, package.json
The statistical field "channel" has been added in the entry of accounting entries. At the moment, account balances are not calculated per channel, but the entries can be filtered by the channel.
=> Add Channel to Accounting Entry

Core/Model/Base/ModelClass.php
Added event before on ModelClass when saveInsert and saveUpdate.
=> Added event before on ModelClass when saveInsert and saveUpdate

Core/Lib/Widget/BaseWidget.php, Core/Lib/Widget/ColumnItem.php, Core/Lib/Widget/GroupItem.php, Core/Lib/Widget/RowActions.php, Core/Lib/Widget/RowFooter.php, Core/Lib/Widget/RowStatistics.php, Core/Lib/Widget/RowStatus.php, Core/Lib/Widget/VisualItem.php, Core/View/Master/GridView.html.twig
An html identifier is applied to the groups, columns and widgets if it is specified in the xml view declaration.
=>  Add id property to Items and Widgets

Core/Assets/JS/GridController.js, Core/Lib/ExtendedController/GridView.php, Core/Lib/Widget/BaseWidget.php, Core/Lib/Widget/WidgetNumber.php, Core/Lib/Widget/WidgetSelect.php, Core/View/Master/GridController.html.twig, Core/View/Master/GridView.html.twig
- **Add getType function to BaseWidget**: 
_Lets you know the class of the widget_
- **Add method for get datasource data**:
_Obtains the configuration of the datasource used in obtaining data_
- **Fix load Autocomplete columns data for GridViews**
- **Fix minor errors in GridView templates and JS**
- **Fix default step configurarion for numbers and money widgets**:
_Without the value of the step only allows integer values not accepting currency values._
=> Fix multiple errors in GridView, Autocomplete and Numbers Widgets

Core/Lib/ExtendedController/GridView.php, Core/Lib/Widget/WidgetAutocomplete.php, Core/Lib/Widget/WidgetSelect.php
- **Add strict property**:
_Added the strict property for the GridView columns, thus allowing an autocomplete column to be filled with values that are not in the list._
- **Fix autoload values of autocomplete widget**:
_Datasource values are not loaded now during the creation of the Autocomplete widget._
=> Add property and fix Autocomplete Widget

Core/Lib/Widget/GroupItem.php
Add a div class row to render correctly columns
=> Fix render modal dialog

Core/Assets/JS/EditAsiento.js, Core/Controller/EditAsiento.php, Core/View/EditAsiento.html.twig, Core/View/EditAsientoGridView.html.twig, Core/XMLView/EditConceptoPartida.xml, Core/XMLView/EditPartida.xml
Modifications to make the entry of accounting entries work with the new refactoring of the extended controllers.
=> Fix Accounting Entry to refactored extended controllers

Core/Lib/Widget/RowFooter.php, Core/Model/Base/ModelView.php, Core/View/Master/EditListView.html.twig, Core/View/Master/EditView.html.twig, Core/View/Master/GridView.html.twig, Core/View/Master/ListView.html.twig
- **Fix ModelView load data from ListView**
- **Add controller to row header/footer render**:
_A pointer to the controller is added in the call to render the row of type header and footer so that it can be used in groups of type html_
=> Fix and new options for render rows

Core/Lib/Accounting/AccountingGenerator.php, Core/Lib/Accounting/InvoiceToAccounting.php, Core/Model/FacturaCliente.php, Core/Model/FacturaProveedor.php
Added library for the automatic creation of accounting entries based on an array of data.
Added library for the automatic creation of accounting entries of purchase and sale invoices.
Linking the InvoiceCustomer and InvoiceSupplier models through the recording methods with the invoice posting library.
> This a beta versión. Need a better link between the library and the recording methods.
=> Invoice accounting

Core/Lib/API/APIModel.php
Fix issues with PUT/GET methods
- Updated getResource()
- Default code is params[0] or null, only POST don't set this value, then we can't assume that is setted
- PK code is replaced only when method is not POST
- Now don't check if need to exec listAll (this must do it doGET)
- Updated doGET()
- If params are empty, we want a list of items
- Updated listAll()
- Removed unneeded checks
=> Some fixes on APIModel

Core/Controller/EditRegularizacionImpuesto.php, Core/Model/PartidaImpuestoResumen.php, Core/View/Block/PartidaImpuestoResumen.html.twig
Fixed the code to work with the new refactoring of the Extended Controller
=> Fix VAT Regularization to refactored extended controllers

Core/Controller/ListCliente.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ListFilter/CheckboxFilter.php, Core/Lib/ListFilter/SelectWhereFilter.php
- **CheckBoxFilter**:
_Now, optionally, you can report a DataBaseWhere array to filter the data if the checkbox is not selected._
- **SelectWhereFilter**:
_Added new option selection filter (Input Select) that allows to establish a DataBaseWhere filter for each of the options._
**Tested**
=> Add default where to checkbox filter and new Select Where Filter

Core/App/AppAPI.php
Cuando se lanza una petición a la api ya sea por la función fetch de javascript o las librerías axios o http de angular primero se lanza una petición con el método OPTIONS con el cual se verifican los headers Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers  para posteriormente realizar la petición ya sea GET, POST, PUT o DELETE, con este if regresamos inmediatamente la información de los headers sin datos de los recursos ya que si la petición sigue su curso normal esta será bloqueada por no contar con el token de acceso .
La primer petición con método OPTIONS se realiza automáticamente y no se adjuntan los headers de la petición final (Token, Content-Type ... etc)
=> Solucionar peticion javascript a la api con el metodo OPTIONS

Core/Base/DataBase/DataBaseWhere.php
Now encloses logical conditions of type OR in parentheses to respect precedence.
=> Add logical grouping

Core/Lib/ExtendedController/ListView.php, Core/Lib/ListFilter/AutocompleteFilter.php, Core/Lib/ListFilter/BaseFilter.php, Core/Lib/ListFilter/CheckboxFilter.php, Core/Lib/ListFilter/DateFilter.php, Core/Lib/ListFilter/NumberFilter.php, Core/Lib/ListFilter/SelectFilter.php, Core/Lib/ListFilter/SelectWhereFilter.php
=> Add showfilters calculate to filters

Core/Controller/EditAgente.php, Core/Controller/EditApiKey.php, Core/Controller/EditAtributo.php, Core/Controller/EditBalance.php
- Extends from EditController including respective changes
=> Modify EditAgente, EditApiKey, EditAtributo and EditBalance [Trello task 542]

Core/Controller/ListAlbaranCliente.php, Core/Controller/ListAlbaranProveedor.php, Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Controller/ListPedidoCliente.php, Core/Controller/ListPedidoProveedor.php, Core/Controller/ListPresupuestoCliente.php, Core/Controller/ListPresupuestoProveedor.php
Disable button new and delete on Lines list into controllers: ListFacturaCliente, ListFacturaProveedor, ListAlbaranCliente, ListAlbaranProveedor, ListPedidoCliente, ListPedidoProveedor, ListPresupuestoCliente and ListPresupuestoProveedor.
=> Disable button new and delete on lines lists

Core/Lib/Widget/BaseWidget.php, Core/Lib/Widget/RowStatus.php, Core/Lib/Widget/VisualItem.php
The calculation of the color to apply to the object is centralized based on a declaration of option label of the xml view
=> Add Method to calculate color from a xml option configuration

Core/Controller/EditCuenta.php, Core/Controller/EditGrupoClientes.php, Core/Controller/EditSubcuenta.php
· Extend of EditController on EditCuenta, EditGrupoCliente and EditSubcuenta.
· Return string 'Cuenta' on method getModelClassName().
· Delete the first $this->addEditView() on three controllers.
=> Convert EditCuenta, EditGrupoCliente and editSubcuenta to edit controllers

Core/XMLView/ListLineaFacturaCliente.xml
Remove columns albarán and served on LineaFacturaCliente.xml view
=> Remove columns albarán and served on LineaFacturaCliente.xml view

Core/XMLView/ListLineaFacturaProveedor.xml
Delete column albarán and served on ListLineaFacturaProveedor,
=> Remove colum albarán and served

package.json
Update Font Awesome (free) to version 5.4.1
Update Handsontable to version 5.0.2
=> Update packages versions

Core/Lib/Accounting/AccountingPlanImport.php
Problem with the length of the subaccount. Compared account length with the length of the subaccount declared in the fiscal year. Then I did not create subaccounts
MySQL
=> Issue correction when importing accounting plan

Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml
Added foreign key to relationate with warehouse on tables: albaranescli, albaranesprov, facturascli, facturasprov, pedidoscli, pedidosprov, presupuestoscli  and presupuestosprov.
=> Added foreign keys onwith relationate with warehouse

Core/Table/pages.xml, Core/Table/pages_options.xml
Increase field name of table pages and pages_options to 40 characters.
=> Increase field name of table pages and pages_options to 40 characters

Core/Table/lineasalbaranescli.xml, Core/Table/lineasalbaranesprov.xml, Core/Table/lineasfacturascli.xml, Core/Table/lineasfacturasprov.xml, Core/Table/lineaspedidoscli.xml, Core/Table/lineaspedidosprov.xml, Core/Table/lineaspresupuestoscli.xml, Core/Table/lineaspresupuestosprov.xml, Core/Table/lineastransferenciasstock.xml
Added Foreign key on lines table reference to impuestos table.
=> Added Foreign key on lineas table reference to impuestos

Core/Controller/ListAgente.php
Changed the status filter (suspended) from checkbox type to select where type
=> Change filter status in ListView Agents

Core/Controller/ListProveedor.php
Changed the status filter (suspended) from checkbox type to select where type
=> Change filter status in ListView Suppliers

Core/Controller/EditEmpresa.php, Core/Controller/ListFormaPago.php, Core/Model/CuentaBanco.php, Core/Table/cuentasbanco.xml, Core/XMLView/EditCuentaBanco.xml, Core/XMLView/EditEmpresa.xml, Core/XMLView/ListCuentaBanco.xml
Add company field to bank accounts.
Add filter company to list view bank accounts.
Add bank accounts tab to edit company
=> Add bank acount and company link

Core/Controller/EditEmpresa.php, Core/XMLView/EditAlmacen.xml, Core/XMLView/ListAlmacen.xml
The tab with the data from the warehouse is added to the company's file to facilitate the process of creating and consulting data, especially when a new company is registered.
=> Add tab of warehouse to the company card

Core/Controller/ListFormaPago.php, Core/Data/Lang/ES/almacenes.csv, Core/Data/Lang/ES/formaspago.csv, Core/Model/FormaPago.php, Core/Table/cuentasbanco.xml, Core/Table/formaspago.xml, Core/XMLView/EditEmpresa.xml, Core/XMLView/EditFormaPago.xml, Core/XMLView/ListFormaPago.xml
Add company to Payment Methods
Delete the bank account of the payment method
Restructure Edit Company view
=>  Add company to Payment Methods

Core/Assets/JS/ListView.js, Core/Lib/ExtendedController/BaseView.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/ListView.php, Core/Model/PageFilter.php, Core/Table/pages_filters.xml, Core/View/Master/ListView.html.twig
New filter recording system applied in ListView type views.
The ability to record and select the applied filters has been added.
=> Save Filters Values

Core/Controller/ListPedidoCliente.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/ListView.php, Core/Lib/ListFilter/BaseFilter.php, Core/Lib/ListFilter/PeriodFilter.php, Core/Lib/ListFilter/PeriodTools.php
A new widget is added for the introduction of periods of dates that simplifies the process by selecting the period from a list of predefined options.
See ListPedidoCliente for example
=> Add new Period Widget

Core/Controller/Wizard.php, Core/View/Wizard.html.twig
Added three new fields on Wizard.html.twig to set the new values.
Get the new values on the Wizard Controller to then storage with the other relevant data.
=> Change the name, address and zip code of the business. 

Core/View/Master/GridView.html.twig
=> Fix Delete GridView

Core/Controller/ListAsiento.php
Modify ListAsiento Controller.
Quit filter date and include filter period in ListAsiento
MySQL
=> add filter period date in ListAsiento

Core/XMLView/ListRegularizacionImpuesto.xml
Changed id accounting column widget to autocomplete
=> Modify id accounting widget type

Core/Controller/EditEmpresa.php
Add where filter to load exercise tab
=> Fix company exercise list

Core/Assets/JS/WidgetAutocomplete.js, Core/Lib/ExtendedController/BaseController.php
Now WidgetAutocomplete show a no select item with "no value" text when query don't have results.
=> Add no result to WidgetAutocomplete

Core/Controller/EditFormaPago.php, Core/Data/Lang/ES/formaspago.csv, Core/Model/FormaPagoEjercicio.php, Core/Table/formaspago.xml, Core/Table/formaspagoejercicios.xml, Core/XMLView/EditFormaPago.xml, Core/XMLView/EditFormaPagoEjercicio.xml
=> Restructure Payment Method

Core/Controller/EditAgente.php, Core/Controller/ListAgente.php
=> Modif agent menu option

Core/Lib/ExportManager.php
Permit add options in exportManager from controller.
MySQL
=> Permit add options in array $options for new methods of export values

Core/Model/Base/ModelView.php
Due to the improvements in ListView, EditView and the management of their models it was necessary to correct minor errors for the operation of read-only models (ModelView).
It has been used to reorder the methods alphabetically.
=>  Fix ModelView minor errors

Core/Model/Base/ModelView.php
Expanded the scope of ownership database and clear method
=> Minor update. Database Property and Clear Method

Core/Lib/BusinessDocumentCode.php, Core/Model/Base/BusinessDocument.php, PULL_REQUEST_TEMPLATE.md
Now bussines document new code are generated on BussinesDocumentCode.
=> Added BussinesDocumentCode class.

Core/Lib/ExtendedController/ListController.php
The addition of a filter is grouped in a unique protected method to be able to customize the filters in inherited classes.
=> Add Filter Base Method

Core/XMLView/EditVariante.xml
Fix update error by idvariante = ''
idvariante isn't string
=> Minor Fix on Edit Variant XML View

Core/Lib/Accounting/InvoiceToAccounting.php, Core/Model/Asiento.php, Core/Model/Base/BusinessDocument.php, Core/Model/Ejercicio.php
Modified the getByDate method by loadFromDate. Now the method loads the exercise data on the existing model for the indicated date. It is necessary that the exercise model has the company identifier on which the search is carried out.
Corrected the calls to old method in business documents and accounting entry.
Changed the "abierto" method to "isOpened"
=> Change getByDate by loadFromDate

Core/Model/Ejercicio.php
Reorder loadFromDate method into model
=> Put correct alphabetic order

Core/Lib/ExtendedController/ListBusinessDocument.php
idcontactofact and idcontactoenv
Create autocomplete filters for listdocument controller by idcontactofact and idcontactoenv fields.
=> Create new filters in ListBilling

Core/Data/Lang/EN/cuentasesp.csv, Core/Data/Lang/ES/cuentasesp.csv, Core/Data/Lang/eu_ES/cuentaesp.csv, Core/Model/CuentaBanco.php, Core/Table/cuentasbanco.xml, Core/XMLView/EditCuentaBanco.xml, Core/XMLView/ListCuentaBanco.xml
The special account for bank charges is added.
The bank expense account is added to the bank accounts of the company.
The sub-account widget is modified in the edition of bank accounts so that it is autocomplete and thus can be searched by account and by description.
The sub-account and sub-account columns for bank charges are added to the list view of bank accounts.
=> Added Bank charges

Core/Controller/ListAsiento.php, Core/Lib/ExtendedController/GridView.php, Core/XMLView/EditAsiento.xml
Fixed update balance of subaccounts.
Fixed can select exercise in new account entry
=> Fix Accounting Entry

Core/Controller/EditEjercicio.php, Core/Lib/Accounting/AccountingPlanExport.php, Core/XMLView/EditEjercicio.xml
Añadido **botón exportar** en los ejercicios, para exportar la lista de cuentas y subcuentas en formato xml
- [X ] MySQL
=> facturascripts: task_35_add_export_button_to_edit_exercice

Core/Model/Serie.php, Core/Table/series.xml, Core/XMLView/EditSerie.xml
Add fields idserie and iddiario en series model, table and xmlview
=> Modify series

Core/Data/Codpais/ESP/impuestos.csv
Added defaults values for IGIC
=> Addded IGIC on csv impuestos

Core/Table/series.xml
Fixed minor error on series.xml table because the foreign key contraint was into other constraint.
=> Fixed minor error on series.xml table declaration.

Core/Controller/ListSecuenciaDocumento.php
Added filters select for business, exercises and series
=> Added filters for business, exercises and series

Core/Controller/DocumentStitcher.php, Core/View/DocumentStitcher.html.twig
He añadido un campo para introducir la fecha del documento a generar si quiero que sea distinta de la fecha actual. 
- [ X] MySQL
=> facturascripts: task56_Add_date_field_to_DocumentStitcherController

Core/Lib/ExtendedController/ListBusinessDocument.php, Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPresupuestoCliente.xml
Se agrego el botón para agrupar documentos en:
- ListAlbaranCliente
- ListPedidoCliente
- ListPresupuestoCliente
=> Task 120: Completado

Core/Controller/EditSerie.php
Se agrego el listado de secuencias de documentos relacionadas a la serie que se esta editando.
=> Task 121: Completado

Core/Lib/ExtendedController/ListBusinessDocument.php
=> Task 120: Correcion de errores.

Core/Lib/PetitionTools.php
Se creo la clase PetitionTools para generar una cadena aleatoria, que sirva como token para usar en los formularios que lo necesiten para evitar peticiones duplicadas.
=> Implemented PetitionTools Class 

Core/Model/Base/ModelView.php
A new masterModel property is added that allows you to establish which is the main model on which the addition, modification and deletion operations will be performed.
=> Added master model

Core/Model/Base/ModelView.php
In the deletion actions it is necessary to calculate the data load sql based on the primary key of the master model.
=> Fix loadFromCode and delete actions

Core/Controller/DocumentStitcher.php, Core/Lib/BusinessDocumentGenerator.php, Core/Model/Base/ModelView.php
Modificada clase core/lib/BusinessDocumentGenerator 
para asignar las properties al nuevo documento generado. 
Y core/controller/DocumentStitcher para
con properties incluir fecha y asignar esa fecha al nuevo documento.
=> Task#119: Modify class core/lib/BusinessDocumentGenerator

Core/Model/Base/ModelView.php
The masterModel property stops being static. It is necessary that each ModelView instance has its own master model.
Fixed minor errors in the code
=> Fix static masterModel

Core/Model/Asiento.php
=> Fix id journal name

Core/Lib/Accounting/AccountingAccounts.php, Core/Lib/Accounting/AccountingCreateTools.php
created a new class to group the automatic creation of accounting sub-accounts.
The AccountingAccounts class is restructured to use the new class when it is necessary to register a subaccount.
=> Accounting create tools

Core/Lib/Accounting/AccountingAccounts.php, Core/Lib/Accounting/AccountingCreateTools.php, Core/Lib/BusinessDocumentTools.php
The tax percentages have been added in the return array of the method that calculates totals for taxes
=> Add percentages of taxes in totals by taxes

Core/Lib/Accounting/AccountingAccounts.php, Core/Lib/Accounting/InvoiceToAccounting.php
- Add Tax subaccounts gets
- Add added the posting of document linens by tax
=> Task 110 - Add added the posting of document linens by tax

Core/Model/Retencion.php, Core/Table/impuestos.xml, Core/Table/retenciones.xml, Core/XMLView/EditRetencion.xml
- Add subaccount to retention
Add new fields to table and model
Add columns to edit view
- Fix subacounts tax
=> Add subaccount to retention and minor fix

Core/XMLView/EditPartida.xml
Fixed the translation string for the show and modification button in the tax register book
=> Fix vat register translate

Core/Lib/Accounting/AccountingAccounts.php, Core/Lib/Accounting/InvoiceToAccounting.php, Core/Model/Retencion.php
Added posting of withholdings based on the percentage applied in the document.
Now you can customize the posting sub-account for each percentage
=>  Add IRPF percentaje Accounting

Core/Lib/Accounting/AccountingClass.php, Core/Lib/Accounting/InvoiceToAccounting.php
Generic methods of the InvoiceToAccounting class are carried to the AccountingClass parent class according to the recommendations of Scrutinizer.
=> Class simplification according to Scrutinizer

Core/Controller/EditEjercicio.php, Core/Lib/Accounting/AccountingPlanExport.php
Modified  AccountingPLanExport and EditEjercicio to export Accountin Plan to CSV.
If the code exercise does not have accounts, it sends an error message
- [X ] MySQL
=> Task# 135 Modify AccountingPLanExport for export to CSV

Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/clientes.xml, Core/Table/empresas.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml, Core/Table/proveedores.xml, Core/XMLView/EditEmpresa.xml
=> Task #139, #155, #143

Core/Lib/ExtendedController/EditController.php
A method has been added to get the name of the main view from the EditController class and its descendants.
=> Generalized the obtaining of the name of the main view

Core/XMLView/ListCliente.xml
Rename field name for id fiscal into ListCliente view
=> Fix id fiscal column

Core/Model/Base/ComercialContact.php, Core/Model/Base/Contact.php, Core/Model/Cliente.php, Core/Model/Empresa.php
The tipoidfiscal attribute is raised to a higher level. Now it is implemented in the Contact class.
=> Restructure type id fiscal number

Core/Controller/Base/EditDocHistoryController.php, Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Lib/ExtendedController/EditDocHistoryController.php
A new class is created that includes the methods to show data of purchase and / or sale documents in an edit controller.
The EditCliente and EditProveedor are refactored to use the new class.
=> Add EditDocHistoryController Class

Core/Lib/ExtendedController/EditDocHistoryController.php
Fix error bugs from EditDocHistoryController
=> Fix scrutinizer bugs

Core/Controller/ListAsiento.php, Core/Model/Asiento.php, Core/XMLView/ListAsiento.xml
Modificada la función renumerar del modelo asiento para poder especificar un codejercicio. Si se especifica, se renumera solamente los asientos de ese ejercicio, si no, se renumeran todos.
=> Task#38 Modify renumber function in the asiento.php model 

Core/Controller/EditLiquidacionComision.php, Core/Lib/CommissionCalculate.php, Core/Model/LiquidacionComision.php, Core/Model/ModelView/LiquidacionComisionFactura.php, Core/XMLView/ListLiquidacionComisionFactura.xml
Add Calculate Commission Library Class
Add calculation commission to settlement
=>  Add Calculate Commission Library Class

Core/Controller/EditLiquidacionComision.php, Core/Lib/InvoiceGenerator.php, Core/Model/Agente.php, Core/Model/LiquidacionComision.php, Core/Model/ModelView/LiquidacionComision.php, Core/Table/agentes.xml, Core/Table/liquidacionescomisiones.xml, Core/XMLView/EditAgente.xml, Core/XMLView/EditComision.xml, Core/XMLView/ListLiquidacionComision.xml
- Rename table liquidacioncomision to liquidacionescomisiones
- Add new methods and link to product table from agent table
- Add new class for generate invoice documents
=>  Added generation of auto settlement invoice

Core/Controller/ListCliente.php, Core/Controller/ListProveedor.php
Add filters retentions, series and payment-method to ListCliente and ListProveedor Controllers
=> Task#145: Add new filters to ListCliente and LIstProveedor controllers

Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml
Added Foreign Key on salesDocuments and PurchaseDocuments.
=> Added Foreign Key on salesDocuments and PurchaseDocuments

Core/Controller/ListLogMessage.php
Added plugin filter to Facturascripts/Core/Controller/ListLogMessage.php
=> task #170 Add plugin filter to cronjobs list.

Core/Controller/EditCronJob.php, Core/Controller/EditCuentaBanco.php, Core/Controller/EditLogMessage.php
Replaced Edit + getModelClassName() by getMainViewName() in EditControllers
=> task #178 Replaced in the editcontrollers

Core/Controller/EditAgente.php, Core/XMLView/EditAgente.xml
Add stadistics agent's total outstanding invoices to EditAgent Controller
=> Add agent's total outstanding invoices

Core/Model/IdentificadorFiscal.php, Core/Table/idsfiscales.xml, Core/XMLView/EditIdentificadorFiscal.xml, Core/XMLView/ListIdentificadorFiscal.xml
Tax identification code is added for the integration of electronic invoicing.
=> Optional code of the fiscal identifier

Core/Lib/FiscalNumberValitator.php
Added functionallity to validate cif, nif and nie.
=> Create class to validate the fiscal numbers

Core/Controller/ListLogMessage.php
Added and change filter datePicker for filter period on controller ListLogMessage to ListLogMessage view, ListEmailSent view and ListCronJob view.
=> Added filter period on logs views

Core/Data/Codpais/ARG/default.json, Core/Data/Codpais/CHL/default.json, Core/Data/Codpais/COL/default.json, Core/Data/Codpais/DOM/default.json, Core/Data/Codpais/ECU/default.json, Core/Data/Codpais/MEX/default.json, Core/Data/Codpais/PAN/default.json, Core/Data/Codpais/URY/default.json, Core/Data/Lang/ES/idsfiscales.csv
Se añadió los tipos de id fiscal para Argentina, Chile, Colombia, República Dominicana, Ecuador, México, Panamá y Uruguay. También se añadió el tipo fiscal RNC para República dominica.
- [ x] MySQL
=> Task #200 to #204

Core/Lib/Accounting/VatRegularizationToAccounting.php
Refactorize to use new class SubAccountTools
=> Fix vat regularization accounting

Core/Lib/RegimenIVA.php
Constants are created for the different possible values for a global use in the application.
=> Generalization of the keys in constants

Core/Controller/EditAsiento.php, Core/Lib/ExtendedController/GridView.php
Corrected the problem of duplication of balances when the seat was re-recorded.
=> Fix duplicate amounts

Core/Assets/JS/EditAsiento.js, Core/Assets/JS/GridView.js, Core/Lib/AccountingEntryTools.php, Core/Lib/SubAccountTools.php, Core/Model/Impuesto.php, Core/View/Master/GridView.html.twig
- Add vat calculator of subaccount
- Fix view bugs
=> Accounting entry

Core/Data/Codpais/ECU/provincias.csv
Se soluciona el código de la provincia de **Chimborazo.**
Daba error al momento de iniciar la instalación con Ecuador como país por defecto
- [ X] MySQL
=> Fix codiso province

README.md
Where is the translation handled btw? Would be nice to have this on Hosted Weblate.
=> Spelling: PHP, JavaScript

Core/Lib/ExtendedController/GridView.php
Sobrescribo el método export en la clase **GridView** en el que ahora se agrega la data cargada durante el load del **GridView** (the **gridData**) ahora el export agrega un tabla con las filas de partidas cargadas.
=> Tarea #208: Add GridView export method to add the grid data view

Core/Base/DivisaTools.php
=> Added function transform to convert an amount to corresponding value.

Core/Model/Base/ModelView.php
Add exists method to ModelView.
=> Fix exists() error

Core/App/AppController.php, Core/Base/Controller.php, Core/Base/ExtensionsTrait.php, Core/Base/InitClass.php, Core/Base/PluginDeploy.php, Core/Base/ToolBox.php, Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/ListController.php, Core/Lib/ExtendedController/PanelController.php, Core/Model/Base/ModelClass.php, Core/Model/Base/ModelCore.php, Core/Model/Base/ModelTrait.php
Added full extension support for all controllers, models and XML files.
=> Extensions

Core/Lib/Widget/BaseWidget.php
Add to BaseWidget the method setCustomValue to fixed a value to columns not depend of field model.
I have only been able to verify that the field values continue to function correctly.
The solution applied should meet the requirements of the task.
=> #36 - Add custom value to Widgets for modal case

Core/Controller/EditUser.php, Core/XMLView/EditUser.xml
- Add level 99 to the level, admin and active fields into xml view.
- Modified permissions for loading, editing and deleting data
Tested into
=> Task #281 - Fix edit user permissions

Core/Controller/EditAgente.php, Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Lib/ExtendedController/ComercialContactController.php
Add email sent list view to customer and supplier edit view.
=> Task #286 - Add email sent list view

Core/Model/EstadoDocumento.php, Core/Table/estados_documentos.xml, Core/XMLView/EditEstadoDocumento.xml
=> Añadida columna icon a EstadoDocumento y a las tablas relacionadas

Core/Lib/Widget/WidgetAutocomplete.php
Added public method that allows you to set a custom text for the selected value of a widget autocomplete.
=> Add selected custom text to Autocomplete widget

Core/Base/PluginDeploy.php
Fix load xml when extension add columns from same group name.
=> Fix extension xml view load

Core/Controller/EditAtributo.php, Core/Controller/ListAtributo.php, Core/Model/AtributoValor.php, Core/Table/atributos_valores.xml, Core/XMLView/ListAtributoValor.xml
- Add new file orden to xml table
- Add new column to xml views
- Add new field to model
- Add new sort option to list view
=> Add sort number to attributes values

Core/Lib/BusinessDocumentTools.php
=> Use constant VAT Regime

Core/Model/Partida.php, Core/Model/Subcuenta.php
- Removed balance update method in SubCuenta model
- Modified subaccount balance update process in the Partida model
=> Fix update balance process

Core/Lib/Widget/WidgetTime.php
Add Widget Time to widget list options.
=> Task #333 - Create WidgetTime

Core/Controller/ListFormaPago.php, Core/XMLView/EditFormaPago.xml, Core/XMLView/ListCuentaBanco.xml, Core/XMLView/ListFormaPago.xml
- Reorder Edit XML View
- Display company column in List XML View
- Minor fixes into List Controller
=> Reorder fields and minor fixes

Core/XMLView/EditAgenciaTransporte.xml
Remove numcolumns from phone column.
=> Update Edit View AgenciaTransporte

Core/Model/Producto.php, Core/Table/productos.xml, Core/XMLView/EditProducto.xml, Core/XMLView/ListProducto.xml
Added  fechaalta column to products.
=> task#337 Added  fechaalta column to products.

Core/Lib/ExtendedController/BaseController.php, Core/Lib/Widget/RowFooter.php
Now it can be indicated when adding an action button from the controller if desired in a particular footer by adding the attribute 'row' with value of the group name. If the 'row' attribute is not indicated, the button is added to the 'actions' group.
=> Add button to footer row

Core/Controller/EditPageOption.php, Core/View/EditPageOption.html.twig
The possibility of configuring whether a column is read-only has been included
=> Add Read Only column to Options View configuration

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListAlbaranProveedor.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPedidoProveedor.xml, Core/XMLView/ListPresupuestoCliente.xml, Core/XMLView/ListPresupuestoProveedor.xml
Modificados los XMLView de los listados de facturas, albaranes, pedidos y presupuestos para añadir como ocultas (display="none") las columnas cifnif, irpf, neto, totaliva, totalrecargo y totalirpf.
=> Task # 354

Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Lib/ExtendedController/ListBusinessDocument.php
Añadido botón a los listados de facturas (ListFacturaClient y ListFacturaProveedor) para pasar las facturas seleccionadas a estado "completado". Y creada la action en ListBussinesDocument
Falta añadir a translations "complete-action" : "Completar documento"
=> task#350 complete-action button in ListFacturaClient and ListFacturaProveedor

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListAlbaranProveedor.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPedidoProveedor.xml, Core/XMLView/ListPresupuestoCliente.xml, Core/XMLView/ListPresupuestoProveedor.xml
Añadir oculta (display="none") la columna de empresa con un widget select a los listados de facturas, albaranes, pedidos y presupuestos, de clientes y proveedores.
=> task#357 Añadida columna empresa(display=none) a listados de Business Documents

Core/Lib/ExtendedController/GridView.php
Inicialize detail model data when is a new record.
=> Fix save detail in GridView

Core/View/DocumentStitcher.html.twig
Botones para seleccionar todas las cantidades de las líneas o ninguna.
=> task#293 Añadidos botones todo/nada en el template del DocumentStitcher

Core/Table/albaranescli.xml, Core/Table/albaranesprov.xml, Core/Table/facturascli.xml, Core/Table/facturasprov.xml, Core/Table/partidas.xml, Core/Table/pedidoscli.xml, Core/Table/pedidosprov.xml, Core/Table/presupuestoscli.xml, Core/Table/presupuestosprov.xml, Core/Table/productosprov.xml, Core/Table/recibospagoscli.xml, Core/Table/recibospagosprov.xml
para todas las tablas con columna coddivisa
- [ X] MySQL
=> task#360 Añadidas claves ajenas a divisas 

Core/Lib/Widget/WidgetPercentage.php
Añadir widget porcentaje. Como el widget number pero que al listar (el método show()) añade %.
=> Tarea #362

Core/View/Email/NewTemplate.html.twig
lo he probado en Outlook 365 y en gmail y se ve correctamente.
=> Task#353 Modificada la plantilla del email para que se visualice correctamente en outlook.

Core/Lib/ExtendedController/EditController.php, Core/View/Master/PanelController.html.twig
=> The print button is displayed according to view settings

Core/Controller/EditReportBalance.php, Core/Lib/Accounting/IncomeAndExpenditure.php, Core/Model/ReportBalance.php, Dinamic/Lib/Accounting/IncomeAndExpenditure.php
**Nota:**
This balance draws data from the accounts of group 8 and 9. These groups are analytical, and optional, so I have data to perform real tests.
=> Add Income and Expenditure balance

Core/Lib/ExtendedController/EditReportAccounting.php, Core/XMLView/EditReportAmount.xml
=> Add title and header options to balance

Core/Controller/ListCliente.php, Core/Controller/ListProveedor.php
=> task#386 Added "Régimen de IVA" filter to ListCliente and ListProveedor

Core/XMLView/ListLineaAlbaranCliente.xml, Core/XMLView/ListLineaAlbaranProveedor.xml, Core/XMLView/ListLineaFacturaCliente.xml, Core/XMLView/ListLineaFacturaProveedor.xml, Core/XMLView/ListLineaPedidoCliente.xml, Core/XMLView/ListLineaPedidoProveedor.xml, Core/XMLView/ListLineaPresupuestoCliente.xml, Core/XMLView/ListLineaPresupuestoProveedor.xml
Modificados todos los xmlviews de listados de líneas de albaranes, facturas, pedidos y presupuestos para cambiar el tipo de widgets de descuentos, iva, recargo e irpf por el nuevo tipo de widget "percentage".
- [X ] MySQL
- [X ] Database with random data
=> task#389 Modificados los campos correspondientes a widget  "percentage" en listados de línea 

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListAlbaranProveedor.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPedidoProveedor.xml, Core/XMLView/ListPresupuestoCliente.xml, Core/XMLView/ListPresupuestoProveedor.xml
=> task#391 Modificados los widgets de descuentos e irpf en los listados de documentos a tipo "percentage".

Core/Assets/JS/BusinessDocumentView.js
Modified BusinessDocumentView.js to set values for docsubtype and docoperation selects.
This task basically is to enable the change in the sales and purchase invoice document 
Se habilitó el poder colocar valores en los selectores de subtipo de documento y en operación del documento, tanto para facturas de compra y venta.
Se habilitó los selectores en una clase extendida de EditFacturaCliente y EditFacturaProveedor
Se usaron las siguientes combinaciones:
[x] Prueba 1
- $showDocSubType = true;
- $showDocOperation = true;
Ambos selectores detectados y ambos llenados correctamente con los valores actualizados
[x] Prueba 2
- $showDocSubType = false;
- $showDocOperation = true;
Selector de DocOperation detectado y llenado correctamente con los valores actualizados
[x] Prueba 3
- …
=> Task #403: Modified BusinessDocumentView.js to set more values

Core/Lib/ExtendedController/BaseView.php, Core/View/Master/ListView.html.twig, Core/View/Master/ListViewMin.html.twig
Changes in Task-176
Modify files to implement task 176
=> Facturascripts Task-176

Core/Model/Base/PaymentRelationTrait.php
Añadido trait Core/Model/Base/PaymentRelationTrait.php con la propiedad codpago y el método getPaymentMethod().
=> tarea #397 Added trait Core/Model/Base/PaymentRelationTrait.php

Core/Lib/PDF/PDFDocument.php
The lineHeaders property was added and the constructor was created to specify the columns of the table. This way you can inherit from PDFDocument and add the new columns that you want to show in the constructor.
--------
Se añadio la propiedad lineHeaders y se creó el constructor para especificar las columnas de la tabla. De este modo se puede heredar de PDFDocument y añadir las nuevas columnas que se quieran mostrar en el constructor.
=> Task 418 - Added lineHeaders property

Core/Data/Codpais/ECU/ciudades.csv
Tarea #292
Se añade ciudades de Ecuador.
- [ x] MySQL
- [ x] Clean database
=> Add ciudades files for Ecuador.

Core/Lib/Export/XLSExport.php
He probado con el excel del listado de facturas de cliente
=> task#421 Corregido el formato de las celdas numéricas al exportar a excel

Core/Controller/EditProducto.php, Core/XMLView/ListProductoProveedor.xml
Add model insert to ListProductoProveedor into EditProducto controller that link current product to an exist supplier.
=> Task #416: Add model insert to EditProduct

Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Lib/ExtendedController/ListBusinessDocument.php, Core/XMLView/SettingsDefault.xml
and the delivery notes, invoices, etc. only shows the currency filter with multicurrency  = true
- [ X ] MySQL
- [ X ] Database with random data
=> Task#369 Added multicurrency checkbox in default settings

Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php
- [X ] MySQL
- [X ] Database with random data
=> Task#424 Added checkbox filter to invoice lists to filter invoices without accounting entries

Core/Controller/EditPageOption.php, Core/Lib/Widget/WidgetMoney.php, Core/View/EditPageOption.html.twig
=> task#428 Added decimals column to EditPageOption

Core/View/Master/BusinessDocumentView.html.twig
- Now, if the parents or children are more than 1 element, they are shown in a modal dialog.
=> Cambio en la forma de mostrar documentos padres e hijos

Core/Lib/Accounting/AccountingCreation.php
=> #434 - Fix auto create accounting

Core/Lib/Import/CSVImport.php
Summary:
Added code for execute an update when the insert return error.
Resumen
Se ha agregado la funcionalidad ON CONFLICT DO UPDATE SET.
=> Tarea #466

Core/Lib/Accounting/PaymentToAccounting.php, Core/Model/User.php, Core/Table/users.xml, Core/XMLView/EditUser.xml, Core/XMLView/ListUser.xml
1. En el archivo /Core/Table/User se ha añadido la columna creationdate tipo DATE aceptando NULL.
2. En la función Clear de Core/Model/User.php he añadido "$this->creationdate = \date(self::DATE_STYLE);".
3. En Core/XMLView/EditUser.xml he añadido en el último grupo el XML relativo al control de entrada de fecha en modo solo lectura.
4. En Core/XMLView/ListUser.xml he añadido el XML relativo a la columna de fecha de alta en formato texto con su traducción correcta.
=> Tarea #453

Core/Model/Almacen.php
=> Modified the Almacen model to remove $idecompany and use the CompanyRelationTrait instead

Core/View/Tab/DocFiles.html.twig
This fix is needed for 'delete-file' action to work
- [X ] MySQL
=> fix setting the right AttachedFileRelation id value in form > input hidden "id"

Core/Controller/ListProducto.php
Added stock filters by minimum and maximum quantity to:
- List of Products
- List of Variants
- Stock List
=> Add stock filters

index.php
Manually checked and all test ok
=> Changed the PHP version check to be PHP 7.1 or later

Core/Data/Lang/ES/estados_documentos.csv, Core/Data/Lang/eu_ES/estados_documentos.csv
This new status generates a sales invoice directly from Budgets and Customer Orders without going through delivery notes.
=> Task 492 - Add "Invoice" status to quotes and sales orders

Core/Controller/EditRetencion.php
Add Customers and Suppliers tabs to the EditRetention controller to show customers and suppliers with that retention. Remove the buttons New and delete.
=> Task 498 - Add Customers and Suppliers tabs to the EditRetention controller

Core/Model/Cliente.php, Core/Model/Proveedor.php
=> Modified the CLIENTE and PROVEEDOR models: codeModelSearch() method excludes customers/providers with fechabaja not null.

Core/XMLView/EditEjercicio.xml
Modificado a https://facturascripts.com/publicaciones/plan-contable-442
=> Modificado el enlace de ayuda  en la importación del Plan Contable

Core/Lib/Accounting/AccountingClosingBase.php, Core/Lib/Accounting/AccountingClosingClosing.php, Core/Lib/Accounting/AccountingClosingOpening.php, Core/Lib/Accounting/AccountingClosingRegularization.php, Core/Lib/Accounting/AccountingCreation.php
Corrected error when creating the opening accounting entry if the subaccount with balance does not exist in the destination fiscal exercise.
=> Fix error opening error

Core/Lib/Accounting/AccountingClosingBase.php, Core/Lib/Accounting/AccountingClosingClosing.php, Core/Lib/Accounting/AccountingClosingOpening.php, Core/Lib/Accounting/AccountingClosingRegularization.php, Core/Lib/Accounting/AccountingCreation.php
Refactored the code to simplify the understanding of the process and its structure.
Fixed duplication of subaccounts creation. Now before duplicating the subaccount, check that it does not exist in the destination accounting exercise.
=> Fix Accounting Opening

Core/Controller/EditBalance.php
Now the detail of accounts included in an accounting balance is displayed "in line" editing mode.
=> Task #529 - Set edit in line into edit balance controller

Core/Controller/EditImpuesto.php
=> task#497 Added a products tab to the EditImpuesto controller

Core/Controller/EditSubcuenta.php, Core/Model/Join/PartidaAsiento.php, Core/Model/Partida.php, Core/XMLView/ListPartidaAsiento.xml
Two buttons have been added to the edition of an accounting subaccount to be able to dotted or not the entry accounting lines belonging to the subaccount.
=> Add dotted system

Core/Controller/EditImpuesto.php, Core/Controller/ListImpuesto.php
Removed tab for taxes by zones. Now this option is integrated in the edition controller of each tax.
=> Refactor Tax Zone

Core/Controller/ListProducto.php, Core/Model/Base/JoinModel.php, Core/Model/Join/StockProducto.php, Core/Model/Join/VarianteProducto.php, Core/XMLView/ListStock.xml, Core/XMLView/ListVariante.xml
Modify model Stock and Variante from ListProducto controller to new JoinModel class.
Add search and order by product description.
Modify filters to new model class status.
=> Task 507 - Add product description to ListProducto

Core/Controller/ListAsiento.php
Fix having clause with alias field.
Fix search fields by int field type.
=> Issue#3650: Fix PostgreSQL database errors into ListAsiento controller

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Lib/ExtendedController/ComercialContactController.php
Added function in ComercialContactController to verify that the length of the customer / supplier subaccount is the same as that of the last fiscal year of the company. If the length is not the same, it shows a warning.
Added calls to the function in EditCliente and EditProveedor,
- [ X] MySQL
=> Tarea #501 Comprueba longitud de la subcuenta de Cliente/Proveedor

Core/Data/Codpais/DOM/default.json, Core/Data/Codpais/DOM/defaultPlan.csv, Core/Data/Codpais/DOM/divisas.csv, Core/Data/Codpais/DOM/retenciones.csv
Update Dominican Republic localization csv files
- Added the Accounting Plan special accounts missed
- Added initial configuration when activating Dominican Republic as country
=> Update Dominican Republic localization csv files

Core/Controller/ListCuenta.php, Core/XMLView/ListSubcuenta.xml
Added debit and credit columns to list view.
Added numerical filters of greater and less than for debit, credit and balance columns.
Removed the check filter to filter by subaccounts with balance due to being redundant with the new filters.
Filter reorganization so that all numeric filters are in the same row.
=> Add columns and filter for debit, credit and balance

Core/Lib/PDF/PDFDocument.php
=> Cambios realizados.

Core/Lib/ExtendedController/DocFilesTrait.php
Added parameter in the call to create the view of attached files to be able to indicate which view template we want to use.
=> add template param

Core/Lib/CustomerRiskTools.php, Core/Model/Base/SalesDocument.php
Recalculate customer risk when customer code is changed.
=> Fix issue 3665

Core/Lib/Accounting/AccountingAccounts.php, Core/Lib/Accounting/AccountingClass.php, Core/Lib/Accounting/InvoiceToAccounting.php, Core/Model/Familia.php, Core/Model/Join/PurchasesDocIrpfAccount.php, Core/Model/Join/PurchasesDocLineAccount.php
Added, when posting the supplier invoice entry, the possibility of using the accounting subaccount for irpf withholdings on purchases reported in the product file.
The tests have been carried out based on the list of accounts and subaccounts established in Spain.
=> Accounting of irpf by product subaccount

Core/Controller/Dashboard.php, Core/View/Dashboard.html.twig
Added Dashboard according to base template. New enhancements:
- News list has been added. 
- Visualization of the statistical data relative to the current month and its two previous months.
> **This is a working version but not a complete one.**
=> Add Dashboard

Core/Controller/EditReportAmount.php, Core/Controller/EditReportBalance.php, Core/Controller/ListReportAccounting.php, Core/Lib/Accounting/BalanceAmounts.php, Core/Lib/Accounting/BalanceSheet.php, Core/Lib/ExtendedController/EditReportAccounting.php, Core/Model/Base/ReportAccounting.php, Core/Model/ReportAmount.php, Core/Model/ReportBalance.php, Core/Model/ReportLedger.php
Now when printing the balance, if the subaccount has no amount in debit or credit, it is not printed.
=> remove no-amount lines

Core/Controller/EditReportLedger.php
Added warning message, when the exercise is not found for the indicated date period.
=> Add warning

Test/Core/Model/StockTest.php
You can create stock of an existing product.
Deleting the product clears the stock.
Unable to create non-existent product stock.
When deleting the stock of a product, the product has stock 0.
The stock of a variant is the sum of the stock of all warehouses
When there is reserved quantity, the available stock is less than the quantity.
=> Add test for stock model

Core/Lib/Widget/WidgetNumber.php, Dinamic/Lib/EmailTools.php
Cambiar a public step, max y min en los widget number para poder personalizarlos desde el controlador.
=> Tarea #568

Core/Model/Ciudad.php, Test/Core/Model/CiudadTest.php
=> Task #558: Test cities

Test/Core/Model/CuentaEspecialTest.php
Add test to CuentaEspecial model.
=> Task #554: Test account special

Test/Core/Model/CuentaTest.php
=> Task #528: Test account

Core/Controller/EditAsiento.php, Core/Lib/Accounting/AccountingFooterHTML.php, Core/Lib/Accounting/AccountingHeaderHTML.php, Core/Lib/Accounting/AccountingLineHTML.php, Core/Lib/Accounting/AccountingModalHTML.php, Core/View/Master/btnLoading.html.twig, Core/View/Tab/AccountingEntry.html.twig
Añade un nuevo diseño a los asientos, eliminando el handsontable y mostrando un efecto de carga en los botones al hacer acciones.
=> Nuevo formulario de asientos.

Test/Core/AccountImportTest.php, Test/Core/Model/AccountImportTest.php
Added test to check the import of the accounting plan of Spain.
=> Add test for accounting csv import

Core/View/Tab/RoleAccess.html.twig
En el listado de roles cuando marcamos la columna de "mostrar solo registros del usuario" entonces marcamos también la columna de "mostrar". Si desmarcamos la columna de "mostrar" desmarcamos la columna de "mostrar solo registros del usuario" si esta marcada.
=> Tarea #577 roles

Core/Lib/Widget/WidgetSelect.php
El id se esta recogiendo en la clase padre VisualItem pero no se estaba mostrando, este PR lo que hace es pintar dicho id en el select.
=> Añadido el atributo id al select.

Core/Controller/ListCliente.php
Ocultar las pestañas de direcciones y cuentas bancarias en ListCliente cuando el usuario solo puede ver lo suyo.
=> Tarea #576 - Ocultar pestañas de direcciones y cuentas bancarias en ListCLiente

Core/Controller/ListAlbaranCliente.php, Core/Controller/ListAlbaranProveedor.php, Core/Controller/ListFacturaCliente.php, Core/Controller/ListFacturaProveedor.php, Core/Controller/ListPedidoCliente.php, Core/Controller/ListPedidoProveedor.php, Core/Controller/ListPresupuestoCliente.php, Core/Controller/ListPresupuestoProveedor.php
Ocultamos las pestañas de las líneas de los documentos de compra y venta cuando el usuario solo puede ver lo suyo.
=> Tarea #575 - Ocultar líneas de venta y compra cuando el usuario solo ve lo suyo.

Core/Controller/ListLogMessage.php
Añade una opción nueva de ordenación por IP en los logs.
=> Poder ordenador los logs por IP.

Core/Base/Migrations.php
Todos los productos donde su columna bloqueado sea NULL se establece a 0.
=> Tarea #579 - Marcar los productos bloqueado a 0 donde bloqueado sea null.

Test/Core/Model/DivisaTest.php
Se ha creado un test para la Divisa, para comprobar la inserción de datos.
=> Test de Divisa

Test/Core/Model/ProvinciaTest.php
Test para el modelo Provincia.
=> Tarea #559 - Test modelo provincia.

Core/Table/secuencias_documentos.xml, Core/XMLView/EditSecuenciaDocumento.xml
Se aumento el patrón de las secuencias de 30 a 50 caracteres.
=> Tarea #584 - Aumentar patrón de las secuencias a 50 caracteres.

Test/Core/Model/FabricanteTest.php
Se añadió la comprobación del test para el modelo Fabricante.
=> Tarea #556 - Test para el modelo Fabricante.

Core/App/AppInstaller.php
Crea la base de datos si no existe.
=> Tarea #571 - Crea la base de datos si no existe.

Core/Assets/JS/Custom.js, Core/View/Master/ListView.html.twig
=> Nuevo estilo de filtros por botones.

Core/Lib/ExtendedController/BaseController.php
Filter and check owner data by user and user agent.
=> Add user and agent auto filter

Core/Controller/Updater.php, Core/XMLView/SettingsDefault.xml
Se añade una opción en el panel de control para permitir las actualizaciones del Core o de plugins beta, por defecto esta desactivado.
=> Instalaciones beta

Core/Model/Asiento.php, Test/Core/LogErrorsTrait.php, Test/Core/Model/AsientoTest.php
[Tarea #673](https://facturascripts.com/roadmap/EditTask?code=673)
=> Tarea #673 - Crear log audit y comprobar en el test que crea el log.

Core/Data/Lang/ES/fabricantes.csv, Core/Data/Lang/ES/familias.csv, Test/Core/Model/FabricanteTest.php, Test/Core/Model/FamiliaTest.php
[Tarea #634](https://facturascripts.com/roadmap/EditTask?code=634)
=> Tarea #634 - Eliminar familias y fabricantes por defecto.

Core/View/Master/ListView.html.twig
Mostrar la palabra "nuevo" en el botón + de los listados, solo en versión xl.
[Tarea #682](https://facturascripts.com/roadmap/EditTask?code=682)
=> Tarea #682 - Mostrar palabra "nuevo" en el botón + de los listados.

Core/Lib/Widget/WidgetFile.php
Añadido margen mb-1 al label de widget file como el resto de widgets.
[Tarea #686](https://facturascripts.com/roadmap/EditTask?code=686)
=> Tarea #686 - Añadido margen al label.

.scrutinizer.yml, composer.json, index.php
[Tarea](https://facturascripts.com/roadmap/EditTask?code=638)
=> Tarea #638 - Cambiada la versión mínima de php 7.1 a 7.2

Core/Controller/EditEmailNotification.php
Remove buttons:
- Add new record
- Delete record
=> Remove buttons from EditEmailNotification

Test/Core/Model/FacturaClienteTest.php
[Tarea #681](https://facturascripts.com/roadmap/EditTask?code=681)
=> Tarea #681 - Comprobar que se crea el log audit al crear la factura.

Test/Core/Model/AsientoTest.php
Add test for create account entry.
Add test for modify on closed exercise.
=> Add test to accounting entry model

Core/Lib/AjaxForms/AccountingFooterHTML.php, Core/Lib/AjaxForms/AccountingLineHTML.php, Core/View/Tab/AccountingEntry.html.twig
Se actualiza el diseño de EditAsiento para que sea igual a los nuevos formularios de compras y ventas.
[Tarea #696](https://facturascripts.com/roadmap/EditTask?code=696)
=> Tarea #696 - Cambio en el diseño del formulario de EditAsiento

Core/Model/Empresa.php, Test/Core/Model/EmpresaTest.php
Al crear una empresa solo con el nombre comprobar que se crea su almacén. Y el modelo empresa devolver true solo en caso de haber creado el almacén y su forma de pago.
=> Tarea #582 - Comprobar que se crea el almacén al crear una empresa 

Core/Assets/JS/ListView.js
Al pulsar el botón imprimir en una pestaña de un list controller, se debe imprimir en otra pestaña.
[Tarea](https://facturascripts.com/roadmap/EditTask?code=625)
=> Tarea #625 - Abrir la impresión de listados en una nueva pestaña.

Core/Model/Partida.php, Core/Table/partidas.xml
=> Task #713 Eliminadas las columnas debeme y haberme de las partidas.

Core/Model/Join/StockProducto.php
Se estaba creando una agrupación  en dicho modelo que no es correcta para la vista que tiene asociada.
[Tarea #701](https://facturascripts.com/roadmap/EditTask?code=701)
=> Tarea #701 - Eliminada la agrupación y la suma del total del modelo Join\StockProducto

Core/Controller/CopyModel.php, Core/Controller/EditFacturaCliente.php, Core/Controller/EditFacturaProveedor.php, Core/Lib/Accounting/InvoiceToAccounting.php, Core/Lib/BusinessDocumentGenerator.php, Core/Model/LiquidacionComision.php
Todas las llamadas a recalcular los documentos han sido sustituidas por la nueva clase Calculator.
[Tarea #623](https://facturascripts.com/roadmap/EditTask?code=623)
=> Tarea #623 - Sustituir llamadas a BusinessDocumentTools por Calculator

Core/Base/Controller.php, Core/Lib/ExtendedController/BaseController.php
Moved validateFormToken method to parent class. Controller.
=> Move validate token to parent controller

Core/Assets/JS/Custom.js, Core/View/Master/MenuTemplate.html.twig
=> Version 2022

Core/Base/AjaxForms/AccountingLineHTML.php
- editasiento, el ojo de laq descripciónlo pasamos la subcuentya, y la derscripción la ponemos label de la subcuenta
- donde va la descripción ahi va el concepto input editable
- en el modal otro input tipo texto que se llama documento
- redondear el descuadre a 2 deciamles al añadir una subcuenta en el haber
=> Tarea #777 - Mostrar partida y documento en los asientos.

Core/Model/AlbaranCliente.php, Core/Model/AlbaranProveedor.php, Core/Model/FacturaCliente.php, Core/Model/FacturaProveedor.php, Core/Model/PedidoCliente.php, Core/Model/PedidoProveedor.php, Core/Model/PresupuestoCliente.php, Core/Model/PresupuestoProveedor.php
Añade pipe extensión al crear una línea sin producto en presupuestos, pedidos, albaranes y facturas de compra y venta
=> Añade pipe extensión al crear una línea sin producto

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListAlbaranProveedor.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPedidoProveedor.xml, Core/XMLView/ListPresupuestoCliente.xml, Core/XMLView/ListPresupuestoProveedor.xml
Añadidas las columnas de almacén, serie, ejercicio y divisa a todos los listados de compras y ventas, y la columna forma de pago a los listados de facturas de compras y ventas.
=> Tarea #774 - Añadidas las columnas nuevas a los listados de compras y ventas.

Core/Controller/EditContacto.php
Mover el código para convertir un contacto en cliente o en proveedor a funciones independientes. Y comprobar los permisos del usuario en esas funciones.
[Tarea #893](https://facturascripts.com/roadmap/EditTask?code=893)
=> Tarea #893 - Separar las acciones de convertir un contacto en cliente o proveedor.

Core/Controller/SendMail.php, Core/View/SendMail.html.twig
[Tarea #928](https://facturascripts.com/roadmap/928)
=> Tarea #928 - Añadir token al mandar emails.

Core/View/Tab/PurchasesDocument.html.twig, Core/View/Tab/SalesDocument.html.twig
Alto automático al escribir la descripción de los productos en los documentos de compra y venta.
[Tarea #895](https://facturascripts.com/roadmap/EditTask?code=895)
=> Tarea #895 - …Alto automático descripción lineas de venta/compra

Core/Model/EmailSent.php
[Tarea #769](https://facturascripts.com/roadmap/EditTask?code=769)
=> Limitar a 5000 caracteres el body de los emails al guardar en la BD.

Core/Base/AjaxForms/PurchasesHeaderHTML.php, Core/Base/AjaxForms/SalesHeaderHTML.php
Los detalles del modal se estaban pintando dos veces y eso provocaba que no guardase bien los datos al mandar el ajax.
[Tarea #927](https://facturascripts.com/roadmap/EditTask?code=927)
=> Tarea #927 - Arreglar el modal de detalles al crear documentos de compra y venta.

Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Controller/DocumentStitcher.php
[Tarea #1035](https://facturascripts.com/roadmap/EditTask?code=1035)
=> Tarea #1035 - Quitar opción de agrupar o partir facturas.

Core/Data/Lang/ES/cuentasesp.csv
=> Task #626. Crear nueva cuenta especial

Core/Controller/EditCliente.php, Core/Controller/EditProveedor.php, Core/Controller/EditUser.php, Core/Model/Base/Contact.php, Core/Model/Base/GravatarTrait.php, Core/Model/User.php
[Tarea #949](https://facturascripts.com/roadmap/EditTask?code=949)
=> Tarea #949 - Añadido gravatar a usuarios, proveedores y clientes.

Core/Base/DataBase/DataBaseEngine.php, Core/Base/DataBase/DataBaseQueries.php, Core/Base/DataBase/DataBaseTools.php, Core/Base/DataBase/DataBaseWhere.php, Core/Base/DataBase/MysqlEngine.php, Core/Base/DataBase/MysqlQueries.php, Core/Base/DataBase/PostgresqlEngine.php, Core/Base/DataBase/PostgresqlQueries.php
Rename yopli2k author data
Change copyright year to 2022
=> Rename Author and change copyright year

Test/Core/Model/BalanceCuentaATest.php, Test/Core/Model/BalanceCuentaTest.php
[Tarea #1045](https://facturascripts.com/roadmap/1045)
=> Tarea #1045 - Test balances.

Core/Model/Base/SalesDocument.php, Core/Model/Base/SalesDocumentLine.php, Core/Table/albaranescli.xml, Core/Table/facturascli.xml, Core/Table/lineasalbaranescli.xml, Core/Table/lineasfacturascli.xml, Core/Table/lineaspedidoscli.xml, Core/Table/lineaspresupuestoscli.xml, Core/Table/pedidoscli.xml, Core/Table/presupuestoscli.xml
Add coste field to sales lines document.
Add totalcoste field to sales document.
=> Add cost fields to sales lines/documents

Core/View/Tab/AccountingEntry.html.twig, Core/View/Tab/PurchasesDocument.html.twig, Core/View/Tab/SalesDocument.html.twig
El orden de la líneas solo se estaba estableciendo al mover las líneas, ahora se guarda el orden al guardar el documento.
=> Corregido el orden de las líneas al guardar el documento.

Core/Controller/EditProducto.php, Core/Model/Base/ProductImageFilesTrait.php, Core/Model/Join/ProductImage.php, Core/Model/ProductImage.php, Core/Table/productosimagenes.xml, Core/View/Tab/ProductImage.html.twig
Added the facility to assign images to products. You can add one or multiple images at once, as well as assign them to the entire product or to a specific variant.
- Added the table productosimagenes, the ProductImage model and a join model that joins the model with the models that manage the attached files.
- Added view to add new images and view the product images.
- Added to the product edition controller a new tab with the product images.
- Added a trait with the insert/delete images actions.
=> Task #647 - Product Images

Core/Lib/ExtendedController/PanelController.php, Core/View/Master/PanelControllerLeftBottom.html.twig
Adds a new template where an editing view is displayed at the top and at the bottom a set of selectable views from a vertical panel on the left.
Add after inserting the views the template to 'leftbottom'.
Example:
```
protected function createViews()
{
parent::createViews();
$this->setTabsPosition('leftbottom');
[ ... ]
}
```
=> Add new panel controller template

Test/Core/Base/CalculatorTest.php, Test/Core/Lib/AccountingCreationTest.php, Test/Core/Model/AgenteTest.php, Test/Core/Model/AlbaranClienteTest.php, Test/Core/Model/AlbaranProveedorTest.php, Test/Core/Model/ClienteTest.php, Test/Core/Model/ContactoTest.php, Test/Core/Model/CuentaBancoClienteTest.php, Test/Core/Model/CuentaBancoProveedorTest.php, Test/Core/Model/FabricanteTest.php, Test/Core/Model/FacturaClienteTest.php, Test/Core/Model/FacturaProveedorTest.php, Test/Core/Model/IdentificadorFiscalTest.php, Test/Core/Model/PedidoClienteTest.php, Test/Core/Model/PedidoProveedorTest.php, Test/Core/Model/PresupuestoClienteTest.php, Test/Core/Model/PresupuestoProveedorTest.php, Test/Core/Model/ProductoTest.php, Test/Core/Model/ProveedorTest.php, Test/Core/Model/ReciboClienteTest.php, Test/Core/Model/ReciboProveedorTest.php, Test/Core/Model/TarifaTest.php
Al ejecutar los test estos crean datos los cuales muchos de ellos no se eliminaban después, eso puede causar problemas en el siguiente test. Por ejemplo, creas un cliente "no lo borras", y el próximo test esperar no tener clientes, entonces dará fallo porque si existe alguno, eso pasaba en varias situaciones.
=> Eliminación de datos que se quedaban guardados.

Core/View/AdminPlugins.html.twig
[Tarea #1573](https://facturascripts.com/roadmap/EditTask?code=1573)
=> Tarea #1573 - Mostrar icon load al activar, desactivar y eliminar plugins.

Core/Base/Migrations.php, Core/Controller/SendMail.php, Core/Data/Lang/ES/emails_notifications.csv
[Tarea #1409](https://facturascripts.com/roadmap/EditTask?code=1409)
=> Tarea #1409 - Añadidas notificaciones de emails para documentos de venta

Core/View/Master/ListController.html.twig
[Tarea #1215](https://facturascripts.com/roadmap/EditTask?code=1215)
=> Tarea #1215 - Limitar el nombre de los tab en los listados.

Core/Assets/JS/WidgetSelect.js
Cuando un select está encadenado con un padre, el js debe coger los datos de padre para hacer la consulta ajax. Ese dato que debe obtener del padre debe hacerlo de una forma u otra según el tipo del padre. Se ha mejorado esa llamada y la forma en la que se obtiene el dato del padre para contemplar más casos.
=> Mejora la forma en la que se obtiene el valor del campo enlazado con el select.

Core/Controller/ListLogMessage.php
[Tarea #1756](https://facturascripts.com/roadmap/EditTask?code=1756)
=> Tarea #1756 - Poder desactivar y activar cronjobs desde ListLogMessage.

Core/XMLView/ListAlbaranCliente.xml, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListPedidoCliente.xml, Core/XMLView/ListPresupuestoCliente.xml
[Tarea #1741](https://facturascripts.com/roadmap/EditTask?code=1741)
=> Añadida la columna totalcoste a los listados de ventas.

Core/Controller/CopyModel.php, Core/View/CopyModel.html.twig
[Tarea #1142](https://facturascripts.com/roadmap/EditTask?code=1142)
=> Tarea #1142 - Copiar el dto. global al copiar documentos.

Core/Controller/CopyModel.php, Core/Controller/EditAsiento.php, Core/View/CopyAsiento.html.twig, Core/View/CopyModel.html.twig
[Tarea #1502](https://facturascripts.com/roadmap/EditTask?code=1502)
=> Tarea #1502 - Añadida opción de copiar asientos.

Core/Lib/Widget/RowButton.php
[Tarea #1235](https://facturascripts.com/roadmap/EditTask?code=1235)
Ahora el label es opcional, junto con el icono también opcional. De tal forma que puedes tener un botón solo con icono, solo con label, o ambos y el title por separado. Si no se especifica un label y un icono se pondrá un icono por defecto.
=> Tarea #1235 - Añadido el title por separado a los rowActions.

Core/App/AppController.php, Core/App/AppInstaller.php, Core/App/WebRender.php, Core/Html.php, Core/Lib/Email/NewMail.php, Core/Lib/Widget/RowFooter.php, Test/Core/HtmlTest.php, Test/__files/testCustomFunction.html.twig, Test/__files/testTemplate.html.twig
[Tarea #1233](https://facturascripts.com/roadmap/1233)
=> Tarea #1233 - Añadida nueva clase Html y su Test.

Core/Assets/JS/WidgetSelect.js
=> Corrección del widget select encadenado, para poder usarlo con varios tipos de padres.

Core/View/Master/ListController.html.twig
Se coló una llave } de más en un commit anterior. https://github.com/NeoRazorX/facturascripts/commit/d0a54f6d17f48dddea4c7bf23d3ae6b1607b7121
=> Corregido bug en la vista de ListController.html.twig

Core/Lib/ExtendedController/PanelController.php
[Tarea #1790](https://facturascripts.com/roadmap/EditTask?code=1790)
=> Tarea #1790 - Corregido bug al eliminar un registro desde EditControler.

Core/Assets/JS/EditListView.js, Core/Lib/ExtendedController/EditListView.php, Core/View/Master/EditListView.html.twig
Now when reloading the view after saving a record the list is placed on the saved item.
=> Task #1369 - Save to position

Core/Lib/Widget/WidgetFile.php
Una de las traducciones del WidgetFile estaba mal.
=> Pequeño error de traducción en el widgetfile.

Core/Lib/Widget/RowButton.php
=> El title del RowButton no se está traducción.

Core/View/Master/EditListViewInLine.html.twig
Añadido scroll al guardar a la vista EditListView cuando los formularios se visualizan en modo inLine.
Added scroll on save to EditListView when forms are displayed in inLine mode.
=> Añadido scroll al guardar

Core/Html.php, Core/Lib/MultiRequestProtection.php
[Tarea #1842](https://facturascripts.com/roadmap/EditTask?code=1842)
=> Tarea #1842 - Corregido bug de multireqtoken con la nueva clase html.

Test/Core/Model/SecuenciaDocumentoTest.php, Test/Traits/RandomDataTrait.php
[Tarea #775](https://facturascripts.com/roadmap/775)
=> Tarea #775 - Añadido test para las secuencias de los documentos.

Core/Controller/ReportTaxes.php
[Tarea #1911](https://facturascripts.com/roadmap/EditTask?code=1911)
=> Tarea #1911 - Añadir la columna total al informe de impuestos.

Core/View/Master/PanelControllerBottom.html.twig
[Tarea #1780](https://facturascripts.com/roadmap/EditTask?code=1780)
=> Tarea #1780 - Corregido bug en la vista PanelControllerBottom.html.twig

Core/Model/FacturaProveedor.php
[Tarea #1942](https://facturascripts.com/roadmap/EditTask?code=1942)
=> Tarea #1942 - Bug renumerar asientos facturas de compra.

Core/Lib/ExtendedController/ComercialContactController.php
- When the type or fiscal identifier is changed in the client or supplier, since it was not changed in the contact, the validation of the fiscal identifier failed.
Here are some help links:
- (Documentation for developers) https://facturascripts.com/help?type=developer
- (Development roadmap) https://facturascripts.com/roadmap
=> Fix validation error of the fiscal id

Core/Base/ControllerPermissions.php
Con está función los permisos se pasan en forma de array y se establecen al usuario si son correctos los tipados.
=> Añadida función setParams() para establecer los permisos del usuario.

Core/Controller/EditSettings.php
[Tarea #2010](https://facturascripts.com/roadmap/EditTask?code=2010)
=> Tarea #2010 - Corregido bug que impedía guardar null en el impuesto por defecto.

Core/Base/AjaxForms/AccountingHeaderHTML.php
Añadido la carga del idempresa al recoger los datos enviados desde el formulario.
Added the loading of the idempresa when collecting the data sent from the form.
Here are some help links:
- (Documentation for developers) https://facturascripts.com/help?type=developer
- (Development roadmap) https://facturascripts.com/roadmap
=> Fix load company id

Core/Controller/EditSerie.php, Core/Controller/EditSettings.php, Core/XMLView/ListSecuenciaDocumento.xml
[Tarea #2044](https://facturascripts.com/roadmap/EditTask?code=2044)
=> Tarea #2044 - Mostrar u ocultar empresa en las secuencias.

Core/Base/ToolBox.php, Core/Html.php, Core/Tools.php, Core/Validator.php, Test/Core/ToolsTest.php, Test/Core/ValidatorTest.php
- Añade la clase Tools, que es un reemplazo de la clase ToolBox.
- Añade la clase Validator, que permite validad strings, emails y urls.
- Incluye los correspondientes tests unitarios.
=> Nueva clase Tools para reemplazar ToolBox

Core/Controller/EditCuenta.php, Core/Controller/EditSubcuenta.php, Core/Lib/Accounting/Ledger.php, Core/Lib/Export/AsientoExport.php, Core/Lib/Export/PDFExport.php
[Tarea #2219](https://facturascripts.com/roadmap/EditTask?code=2219)
[Tarea #2214](https://facturascripts.com/roadmap/EditTask?code=2214)
PR relacionado de PlantillasPDF: https://github.com/NeoRazorX/plantillas-pdf/pull/62
=> Tarea #2219 y #2214 - Corregir bug con el espacio de los miles en el pdf del diario contable, y añadir saldo al informe.

Core/Controller/EditAsiento.php
[Tarea #2143](https://facturascripts.com/roadmap/EditTask?code=2143)
=> Tarea #2143 - Añadir permiso de exportar al asiento.

Core/Model/Ejercicio.php
Cuando hay múltiples empresas, al dar de alta un nuevo ejercicio de manera automática, ahora se incluye el nombre corto de la empresa en la descripción del nuevo ejercicio.
=> Añadir nombre de empresa

Core/Lib/CostPriceTools.php, Core/XMLView/SettingsDefault.xml, Test/Core/Model/ProductoTest.php
Crear nueva política de precios, precio de coste más alto.
Modificar la clase CostPriceTools para tener en cuenta la nueva política, añadir la opción correspondiente en el desplegable del panel de control
- He revisado mi código antes de enviarlo.
-  He probado que funciona correctamente en mi PC.
=> Tarea#1824- Nueva política de precio de coste. El precio más alto.

Core/View/Tab/AttachedFilePreview.html.twig
Con está opción al descargar un archivo de la biblioteca podemos elegir si lo queremos con enlace limitado al día actual, o con enlace ilimitado.
=> Añadido dropdown al descargar archivos de la biblioteca.

Core/Controller/DocumentStitcher.php, Core/View/DocumentStitcher.html.twig
[Tarea #2145](https://facturascripts.com/roadmap/EditTask?code=2145)
=> Tarea #2145 - Poder seleccionar serie al agrupar documentos.

Core/Lib/Email/MailNotifier.php, Test/Core/Lib/Email/MailNotifierTest.php
- He añadido un parámetro para poder pasar un array de rutas de archivos y que estos se adjunten en el email.
- He añadido un test que comprueba si se ha enviado el email.
=> Tarea #1566 - Permite Adjuntar Archivos a MailNotifier

Core/Controller/EditCliente.php, Core/Controller/EditContacto.php, Core/Controller/EditProveedor.php, Core/Model/Base/Contact.php, Core/Model/Contacto.php, Core/Table/clientes.xml, Core/Table/contactos.xml, Core/Table/proveedores.xml, Core/XMLView/EditCliente.xml, Core/XMLView/EditContacto.xml, Core/XMLView/EditProveedor.xml
[Tarea #2393](https://facturascripts.com/roadmap/2393)
=> Tarea #2393 - Añadir idioma al cliente, contacto y proveedor.

Core/Lib/BusinessDocumentGenerator.php
Ampliación de la clase BusinessDocumentGenerator para que arrastre hacia el documento destino los enlaces de los ficheros adjuntos del documento origen
He revisado mi código antes de enviarlo.
He probado que funciona correctamente en mi PC.
=> Tarea #708. Copiar enlaces de ficheros adjuntos

Core/Lib/PDF/PDFDocument.php, Core/Model/FormaPago.php, Core/Table/formaspago.xml, Core/XMLView/EditFormaPago.xml
=> Tarea #2275 - Añadida opción para mostrar o no datos bancarios en la forma de pago.

Core/Base/DivisaTools.php, Core/Lib/Widget/WidgetMoney.php
When the field name contains the word euros, the euro currency symbol is applied directly.
Here are some help links:
- (Documentation for developers) https://facturascripts.com/help?type=developer
- (Development roadmap) https://facturascripts.com/roadmap
=> Task#2211 - Apply euro symbol

Core/Base/AjaxForms/AccountingLineHTML.php, Core/Controller/EditAsiento.php
Antes de pintar el formulario de asiento se calcula si existe descuadre para añadir los atributos calculados debe y haber al modelo de asiento.
=> Corrección cálculo descuadre

Core/Model/ProductoProveedor.php, Core/Table/productosprov.xml, Core/XMLView/EditProductoProveedor.xml
[Tarea #2508](https://facturascripts.com/roadmap/EditTask?code=2508)
=> Tarea #2508 - Añadida la columna stock a productosprov.

Core/Controller/EditProducto.php, Core/Controller/ListProducto.php, Core/Lib/ProductType.php, Core/Model/Producto.php, Core/Table/productos.xml, Core/XMLView/EditProducto.xml
[Tarea #2524](https://facturascripts.com/roadmap/EditTask?code=2524)
=> Tarea #2524 - Nueva clase ProductType y columna tipo a los productos.

Core/Lib/ProductType.php
Se han cambiado el nombre de las constantes de la clase ProductType.
=> Renombrado las constantes de ProductType.

Core/Base/Migrations.php, Core/Model/Empresa.php, Core/Table/empresas.xml, Core/Table/lineasalbaranescli.xml, Core/Table/lineasalbaranesprov.xml, Core/Table/lineasfacturascli.xml, Core/Table/lineasfacturasprov.xml, Core/Table/lineaspedidoscli.xml, Core/Table/lineaspedidosprov.xml, Core/Table/lineaspresupuestoscli.xml, Core/Table/lineaspresupuestosprov.xml, Core/Table/productos.xml, Core/XMLView/EditEmpresa.xml
Se ha renombrado la columna exceptioniva de la empresa por exepcioniva, y otras mejoras menores.
=> Renombrada columna exceptioniva de la empresa y correcciones menores.

Core/Controller/EditContacto.php, Core/Controller/EditEmpresa.php, Core/Lib/ExtendedController/ComercialContactController.php, Core/Lib/Vies.php, Core/Model/Agente.php, Core/Model/Base/Contact.php, Core/Model/Cliente.php, Core/Model/Contacto.php, Core/Model/Empresa.php, Core/Model/Proveedor.php, composer.json
[Tarea #2539](https://facturascripts.com/roadmap/EditTask?code=2539)
=> Tarea #2539 - Añadida comprobación del VIES en empresas, clientes, proveedores y contactos.

Core/Assets/CSS/custom.css
Añadida una pequeña clase que personalmente uso en casi todos los plugins al usar twig.
=> Añadida clase pointer al css global.

Core/View/Master/MenuTemplate.html.twig
Añadidas varias posiciones a MenuTemplate.html.twig para poder hacer extensiones.
=> Add posiciones twig

Core/Model/Producto.php, Core/XMLView/ListProducto.xml
- Añadir columna 'Precio + impuestos' al listado de Productos creando una nueva columna en el `ListProducto.xml` y calculando su valor en la constructora del modelo Producto.
=> Tarea #700 - Añadir columna 'Precio + impuestos' al listado de Productos.

Core/Plugins.php, Test/Core/PluginsTest.php
- He creado una función para saber si un plugin está instalado o no.
- En la clase `Plugins` he añadido la función estática `isInstalled()`.
- Se incluyen tests unitarios que compruebas esta funcionalidad.
=> Tarea #2624 - Saber si un plugin esta instalado.

Core/Lib/Widget/WidgetTextarea.php
[Tarea #2638](https://facturascripts.com/roadmap/EditTask?code=2638)
=> Tarea #2638 - Mostrar title del textarea en los listados.

Core/Model/Variante.php
La tarea [Tarea #2655](https://facturascripts.com/roadmap/EditTask?code=2655) obliga a realizar este cambio en el core.
=> Tarea #2655 - Obtener o establecer precio variante si es de segunda mano.

Core/Controller/EditProducto.php, Core/XMLView/ListFacturaCliente.xml, Core/XMLView/ListFacturaProveedor.xml
Para mostrar en cada producto sus compras y ventas, tanto de albaranes como de facturas, he incluido nuevas views en:
- Líneas de albaranes de compra.
- Líneas de facturas de compra.
- Líneas de albaranes de venta.
- Líneas de facturas de venta.
Para evitar código repetitivo (filtros, ordenación, etc), he incluido la función "commonOptions".
=> Tareas #2201 y #2434: Cambiar a color DARK las facturas rectificativas;  y Mostrar en cada producto sus compras y ventas

Core/Base/MyFilesToken.php, Core/Html.php
[Tarea #2683](https://facturascripts.com/roadmap/EditTask?code=2683)
=> Tarea #2683 - Añadida función myfilesUrl a twig.

Core/Controller/ListProducto.php
- Se añadieron filtros en la vista de Variantes
- Filtro de Familia
- Filtro de Fabricante
- https://facturascripts.com/roadmap/EditTask?code=2639
- [ X ] He revisado mi código antes de enviarlo.
- [ X ] He probado que funciona correctamente en mi PC.
=> Se añadio el filtro de Familia y Fabricante, sobre la vista de variantes

Core/Html.php
=> Tarea #2718 - Añadida función a twig para obtener la cache.

Core/Model/ReciboCliente.php
Para la tarea [Tarea #2670](https://facturascripts.com/roadmap/2670) necesitamos que los pagos de los recibos vengan ordenados.
=> Tarea #2670 - Ordenar el pago de los recibos.

Core/Lib/Accounting/PaymentToAccounting.php
- Cuando el documento o pago es negativo los gastos tiene que ser positivos o en caso contrario se realiza un abono de los gastos en vez de cargarlos al sujeto del documento.
=> fix gastos negativos

Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Base/Migrations.php, Core/Controller/EditSettings.php, Core/Model/Serie.php, Core/Table/series.xml, Core/View/Tab/RefundFacturaCliente.html.twig, Core/View/Tab/RefundFacturaProveedor.html.twig, Core/XMLView/EditSerie.xml, Core/XMLView/ListSerie.xml, Core/XMLView/SettingsDefault.xml
[Tarea #801](https://facturascripts.com/roadmap/EditTask?code=801)
=> Tarea #801 - Añadido el tipo a las series.

Core/Base/AjaxForms/SalesHeaderHTML.php
[Tarea #2084](https://facturascripts.com/roadmap/2084)
Añadida la función renderNewFields que faltaba en SalesHeaderHTML
=> Tarea #2084 - Añadida función renderNewFields a SalesHeaderHTML

Core/Controller/ReportTaxes.php, Core/View/ReportTaxes.html.twig
[Tarea #2838](https://facturascripts.com/roadmap/EditTask?code=2838)
=> Tarea #2838 - Corregido el informe de impuestos.

Core/Controller/ListSerie.php
- He incluido el use de la clase Tools
- He incluido un filtro tipo Select para filtrar por el Tipo de Serie
=> Tarea #2809 Filtro por Tipo de las Series en el listado de Series

Core/Assets/JS/Custom.js, Core/Lib/Email/NewMail.php, Core/View/Macro/Toasts.html.twig, Core/View/Master/MenuTemplate.html.twig, Core/View/Master/MicroTemplate.html.twig
[Tarea #2860](https://facturascripts.com/roadmap/EditTask?code=2860)
=> Tarea #2860 - Rediseño del spinner loader

Core/Assets/JS/Custom.js, Core/View/Macro/Toasts.html.twig, Core/View/Tab/PurchasesDocument.html.twig, Core/View/Tab/SalesDocument.html.twig
=> Corrección del animateSpinner al mostrar varios mensajes

Core/Base/AjaxForms/CommonLineHTML.php, Core/Base/AjaxForms/PurchasesLineHTML.php, Core/Base/AjaxForms/SalesLineHTML.php
[Tarea #2852](https://facturascripts.com/roadmap/EditTask?code=2852)
=> Tarea #2852 - Calcular el subtotal de la línea en segunda mano.

Core/Controller/ConfigEmail.php, Core/Controller/EditEmailSent.php, Core/Controller/SendMail.php, Core/Lib/Email/NewMail.php, Core/Lib/Export/MAILExport.php, Core/Model/EmailSent.php, Core/Table/emails_sent.xml, Core/View/Master/MenuTemplate.html.twig, Core/View/SendMail.html.twig, Core/View/Tab/EmailSentAttachment.html.twig, Core/View/Tab/EmailSentHtml.html.twig, Core/XMLView/ListEmailSent.xml
[Tarea #2869](https://facturascripts.com/roadmap/2869)
=> Tarea #2869 - Guardar adjuntos de los emails

Core/Assets/JS/Custom.js, Core/View/Macro/Toasts.html.twig
Ahora el animateSpinner cuando ternima, el mensaje de "completado" o "error" es opcional. Además, se ha corregido el css para permitir clicar sobre los elementos de atrás del mensajes del Toasts.
=> Mejora del animateSpinner

Core/Lib/Accounting/Ledger.php
- Se ha añadido la columna de saldo al total del informe.
- Se ha corregido un error en el posicionamiento de los totales cuando no se agrupaba. Se ha eliminado la columna 'cuenta' que no existe en el informe no agrupado.
=> Añadida columna saldo en el diario contable

README.md
- Se han cambiado los estilos de los badges.
- Se ha cambiado el estilo del titulo principal
- Se ha añadido el logotipo
- Se ha añadido la imagen principal
- Se añaden links para traducciones del README
- Se añade Disclaimer
- Se añaden principales enlaces al inicio
=> modificar estilo y agregar imagenes al README.md

Core/Base/PluginDeploy.php
Falta por añadir al DeployManager que copie la carpeta Worker.
=> Añadido al PluginDeploy el copiado de los archivos Worker

Core/View/AdminPlugins.html.twig
- Mostrar los plugins requieridos de cada plugin en el Listado de plugins instaldado (AdminPlugins)
=> Tarea #987 - mostrar los plugins requieridos

Core/Model/WorkEvent.php, Core/Table/work_events.xml
Necesitamos saber que usuario desencadeno el worker.
=> Añadido el nick del usuario que desencadena el worker

Core/Lib/Email/SpaceBlock.php
Necesitamos tener una clase para añadir espacios entre los bloques del email si tener que añadir css a cada bloque.
=> Añadida clase SpaceBlock para los emails.

Core/Lib/ExtendedController/DocFilesTrait.php, Core/View/Tab/DocFiles.html.twig
[Tarea #1119](https://facturascripts.com/roadmap/EditTask?code=1119)
=> Tarea #1119 - Subir varios archivos a la vez.

Core/Lib/Widget/WidgetRadio.php
Este Widget de usa en PlantillasPDF y MultiEmail, además es interesante tenerlo en el core para poder usarlo. Permite mostrar los radio input de una html normal, o convertirlos en imágenes.
=> Nuevo WidgetRadio

phpunit-plugins.xml
=> Pequeñas correcciones.

Core/View/AdminPlugins.html.twig
- Agregar campo de búsqueda en los plugins instalados
=> agregar campo de busqueda en los plugins instalados

Core/Model/Base/ModelClass.php
En ocasiones necesitamos poder extender la función url() de los modelos, y con esta mejora evitamos la herencia.
=> Añadida extensión a la función url() de los modelos

Core/Assets/JS/WidgetLibrary.js, Core/Lib/ExtendedController/PanelController.php, Core/Lib/Widget/WidgetLibrary.php
[Tarea #3081](https://facturascripts.com/roadmap/3081)
=> Tarea #3081 - Correcciones al widget library

Core/View/SendMail.html.twig
[Tarea #2941](https://facturascripts.com/roadmap/EditTask?code=2941)
=> Tarea #2941 - Permitir enviar multiples archivos por input en el email

Core/Controller/CopyModel.php
[Tarea #2849](https://facturascripts.com/roadmap/EditTask?code=2849)
=> Tarea #2849 - Añadidos Pipes a CopyModel

Core/Model/Contacto.php, Core/Table/contactos.xml, Core/XMLView/EditContacto.xml
[Tarea #2902](https://facturascripts.com/roadmap/EditTask?code=2902)
=> Tarea #2902 - Añadida columna web a los contactos

Core/View/Tab/PreviewFiles.html.twig
La vista de PreviewFile se le olvido añadir soporte para subir varios archivos a la vez.
- [] He probado que funciona correctamente con una base de datos vacía.
=> Añadida la opción de subir varios archivos desde PreviewFiles

Core/Controller/SendMail.php
- Añadir placeholder '{number2}' en template email para quien quiera usarlo.
- Add placeholder '{number2}' on email template for whoever might want it.
=> Add placeholder {number2} for email

Core/Lib/Widget/ColumnItem.php, Core/View/Master/ListView.html.twig
- Añade un icono de ordenación en cada columna del listview que tengan opción de ordenación.
- [ X ] He revisado mi código antes de enviarlo.
- [ X ] He probado que funciona correctamente en mi PC.
- [ X ] He probado que funciona correctamente con una base de datos vacía.
=> #1535 ordenar en listview

Core/Model/Base/Receipt.php
Este cambio es necesario para hacer correctamente la tarea [2191](https://facturascripts.com/roadmap/2191)
=> El pipe del onchange del modelo Onchange impide cambios desde otros plugins

Core/Lib/Vies.php
[Tarea #3150](https://facturascripts.com/roadmap/3150)
=> Tarea #3150 - Comprobar que el país sea de la unión europea al comprobar vies

Core/Controller/Dashboard.php
- Refactorizar con el metodo Cach::remember().
=> refactorizar con Cache remember

Core/Model/ProductoImagen.php
- Añadida comprobación que exista el archivo original antes de crear el thumbails.
=> Añadida comprobación de archivo

Core/Model/Base/BusinessDocument.php
[Tarea #2808](https://facturascripts.com/roadmap/2808)
=> Tarea #2808 - Obtener archivos desde el modelo BusinessDocument

Core/Base/AjaxForms/CommonSalesPurchases.php, Core/Base/AjaxForms/SalesLineHTML.php
[Tarea #3143](https://facturascripts.com/roadmap/EditTask?code=3143)
=> Tarea #3143 - Mostrar el coste de las líneas de venta en el modal

Core/Base/AjaxForms/PurchasesController.php, Core/Base/AjaxForms/SalesController.php
[Tarea #2854](https://facturascripts.com/roadmap/EditTask?code=2854)
=> Tarea #2854 - Guardar documento al marcar como pagado.

Core/Controller/EditProducto.php
[Tarea #2883](https://facturascripts.com/roadmap/2883)
=> Tarea #2883 - Añadir archivos a la ficha de productos

Core/Controller/Updater.php
En ocasiones necesitamos saber las actualizaciones pendientes que tengamos ya sea del core o de los plugins, actualmente eso lo hace el controlador Updater, pero si queremos esa información en otro sitio toca implementarlo todo de nuevo. Con este cambio podemos llamar a la función estática del controlador Updater y obtener el listado de actualizaciones pendientes.
=> Permite obtener el listado de actualizaciones pendientes

Core/Model/RegularizacionImpuesto.php
[Tarea #2216](https://facturascripts.com/roadmap/2216)
**PR DEL PLUGIN RELACIONADO**
https://github.com/FacturaScripts/modelo303/pull/8
=> Tarea #2216 - Añade la opción de hacer el modelo 303 por meses

Core/Assets/JS/EditProducto.js, Core/Controller/EditProducto.php, Core/Model/Producto.php, Core/Model/ProductoImagen.php, Core/Model/Variante.php, Core/Table/productos_imagenes.xml, Core/View/Tab/ProductoImagen.html.twig
- Se implementa jquery ui sortable para poder ordenar las imagenes mediante drag and drop.
- Se modifica el modelo ProductoImagen añadiendo el campo orden y asignandole inicialmente la id en el campo orden si este aún no tiene valor guardado.
- Se agrega el campo orden a la tabla.
- En el controlador se modifica el filtro del orden en el loadData de la vista y se crea un action para guardar el orden que nos llega desde ajax.
- Se añade un titulo para que aparezca un tooltip indicando que es posible ordenar las imagenes arrastrando y soltando.
- Se modifican los métodos getImages() de las clases Producto y Variante para que devuelvan las imagenes ordenadas por el nuevo campo orden.
=> Tarea #3214   poder ordenar imagenes de productos

Core/Lib/Email/NewMail.php
[Tarea #3299](https://facturascripts.com/roadmap/EditTask?code=3299)
=> Tarea #3299 - Corregido fallo al guardar adjunto del email

Core/Base/DataBase.php, Core/Base/MiniLog.php, Core/DebugBar.php
- Incluimos en el contexto de los logs el tiempo de ejecución real de cada consulta a base de datos.
=> incluir el tiempo de ejecucion de la consulta sql en el contexto del log

Core/Model/CuentaBancoCliente.php, Core/Table/cuentasbcocli.xml, Core/XMLView/EditCuentaBancoCliente.xml
[Tarea #3127](https://facturascripts.com/roadmap/3127)
=> Tarea #3127 - Ahora se permite establecer el mandato correctamente

Core/Lib/Email/HtmlBlock.php, Core/Lib/Email/NewMail.php
[Tarea #3298](https://facturascripts.com/roadmap/3298)
=> Tarea #3298 - Corrección al crear el html del email para enviar

Core/Controller/Root.php
- agregar titulo al controlador Root
=> agregar titulo al controlador Root

Core/Controller/ReportTaxes.php
En el informe de impuestos no se estaba teniendo en cuenta correctamente las facturas intracomunitarias.
=> Comprobar facturas intracomunitarias al generar el informe

Core/Base/InitClass.php, Core/Lib/ExtendedController/BaseController.php
En ocasiones necesitamos poder añadir un pipe() que se ejecute en todos los EditController o ListController.
=> Añadir opción de pipes al todos los EditController y ListController

Core/Controller/ListProducto.php
- En la pestaña de stock del menú almacén, productos, faltan filtros para:
reservado >=
reservado <=
pendiente recepción >=
pendiente recepción <=
disponible >=
disponible <=
=> Tarea #3024 - agregar filtros reservado pendiente recepcion disponible

Core/Model/Subcuenta.php
Siempre se estaba actualizando la subcuenta sin comprobar si había cambios, generando miles de workers.
=> Error al comprobar el balance de la subcuenta

Core/Controller/EditRole.php
- La página de administrar permisos del grupo no está eliminando los permisos de controladores que ya no existen al guardar.
El problema viene cuando quitamos un plugin que ya no vamos a usar nunca y nos vamos a editar los permisos. Nos están apoareciendo controladores que ya no existen.
Solución
Al guardar los permisos debemos eliminar aquellos de páginas que ya no existen en la tabla pages.
- Buscamos los permisos que ya no tienen página y los borramos
- Si al borrar los permisos, se borran todos los del rol, eliminamos el rol vacío.
=> Tarea #3351 - eliminar permisos de controladores que no existen

Core/Lib/ReceiptGenerator.php
=> Añadimos evento al marcar un recibo como pagado y actualizar la factura

Core/Model/Variante.php
En ocasiones queremos que otros plugins puedan editar la descripción que se genera de las variantes o cambiarla, con este cambio permite hacerlo sin herencia.
- [] He probado que funciona correctamente con una base de datos vacía.
=> Añadidos nuevos pipes para la descripción de las variantes

Core/Controller/DocumentStitcher.php
-  al agrupar documentos, el listado de más documentos está mostrando documentos que no son compatibles:
Tienen otra serie.
Tienen otra divisa.
Tienen otro descuento global.
- he añadido también que sean de la **misma empresa**.
=> Tarea #3119 - agregar where serie divisa dto empresa a partir agrupar

Core/Controller/Login.php
Necesitamos que al hacer el usuario login se guarde automáticamente el usuario en la sesión
=> Guardar la sesión del usuario al hacer login

Core/Controller/EditFacturaCliente.php, Core/Controller/EditFacturaProveedor.php, Core/View/Tab/RefundFacturaCliente.html.twig, Core/View/Tab/RefundFacturaProveedor.html.twig
[Tarea #3422](https://facturascripts.com/roadmap/3422)
=> Tarea #3422 - Estado por defecto al crear factura rectificativa

Core/Model/User.php, Core/Model/UserMessage.php, Core/Table/users_messages.xml, Core/View/Master/MenuTemplate.html.twig
- Implementar clase UserMessage para mostrar mensajes para el usuario en la misma request o en la request siguiente.
- El método addActionBtn muy bien a lo que te refieres y no sé como implementarlo.
- El método addHelpLink igualmente no se a que te refieres.
Se usaria de la siguiente forma:
```php
Session::user()
->error('save-error')
->save();
Session::user()
->error('save-error-despues')
->showLater()
->save();
Session::user()
->warning('accounting')
->addLinkBtn('EditEjercicio?code=2023', 'user')
->save();
```
=> Tarea #2553 - Implementar mensejes flash usuario

Core/Base/Calculator.php
Cuando hacemos una rectificativa sobre una factura de productos de segunda mano los cálculos totales no salen bien. Con este cambio se comprueba si la serie del documento es un serie rectificativa para corregir el cálculo correctamente.
=> Corregido el cálculo de las rectificativas cuando es de segunda mano

Core/View/Master/PanelController.html.twig, Core/View/Master/PanelControllerTop.html.twig
Este cambio es necesario para cubrir la tarea [Tarea #3315](https://facturascripts.com/roadmap/3315) de EscanearDocumentos.
=> Añadir ganchos al PanelController

Core/Tools.php
=> documentar clase Tools

Core/View/AdminPlugins.html.twig, Core/View/Dashboard.html.twig, Core/View/Macro/Utils.html.twig, Core/View/Updater.html.twig
[Tarea #3184](https://facturascripts.com/roadmap/EditTask?code=3184)
=> Tarea #3184 - Añadido mensaje para registrar la instalación

Core/Lib/FiscalNumberValidator.php
Permitir validar los ids fiscales manualmente.
=> Permitir validar el id fiscal manualmente

Core/Controller/CopyModel.php
Este pr es necesario para completar la tarea [3453](https://facturascripts.com/roadmap/3453) de ServiciosProgramados
=> Añadidos pipes a copyModel

Core/Lib/OpenAi.php
Se añaden opciones para crear y gestionar los vectores.
=> Nuevas opciones en openAI

Core/Lib/Widget/WidgetSelect.php
El widgetSelect actual tiene un fallo cuando está en readonly, este pr corrige el problema.
=> Corrección al widgetSelect

Core/Controller/About.php, Core/View/About.html.twig
- Agregar pagina `/About` que permite obtener un resumen del sistema y la instalación(útil para poder enviar a Soporte y diagnosticar posibles errores).
=> agregar pagina About

Core/Controller/EditUser.php, Core/Controller/Login.php, Core/Lib/TwoFactorManager.php, Core/Model/User.php, Core/Table/users.xml, Core/View/Tab/UserTwoFactor.html.twig, Core/XMLView/EditUser.xml, composer.json
Modificaciones y cambios para el doble factor.
=> Correcciones y cambios al doble factor

Core/Lib/API/Base/APIResourceClass.php
- actualizar dependencia Request
=> actualizar dependencia Request

Core/Controller/AdminPlugins.php, Core/Controller/SendMail.php, Core/Lib/ExtendedController/ProductImagesTrait.php
- Ahora no existe un segundo parametro como default.
=> refactorizar segundo parametro ahora no existe

Core/Model/User.php
- inicializar propiedad two_factor_enabled a false en el modelo
=> inicializar propiedad two_factor_enabled a false en el modelo

Core/Controller/About.php
=> actualizar clase obsoleta

Core/Controller/ConfigEmail.php, Core/Controller/DocumentStitcher.php, Core/Controller/EditFabricante.php, Core/Controller/EditFacturaCliente.php, Core/Controller/EditFacturaProveedor.php, Core/Controller/EditFamilia.php, Core/Controller/EditGrupoClientes.php, Core/Controller/EditReciboCliente.php, Core/Controller/EditReciboProveedor.php, Core/Controller/EditTarifa.php, Core/Controller/ListAsiento.php, Core/Controller/ListAttachedFile.php, Core/Controller/ListLogMessage.php, Core/Lib/ExtendedController/BaseController.php, Core/Lib/ExtendedController/ComercialContactController.php, Core/Lib/ExtendedController/EditController.php, Core/Lib/ExtendedController/ListBusinessDocument.php, Core/Lib/ExtendedController/ListController.php, Core/View/DocumentStitcher.html.twig, Core/View/Master/ListView.html.twig
La nueva clase request tiene su método array para los listados que no se estaba aplicando.
=> Usar la clase request array para los listados

Core/Table/clientes.xml, Core/Table/gruposclientes.xml, Core/Table/tarifas.xml
Corregido bug con tablas que se han renombrado en un commit anterior por error.
=> Corregido bug de tablas con fa-solid

Core/Lib/Widget/BaseWidget.php, Core/Lib/Widget/GroupItem.php, Core/Lib/Widget/RowButton.php, Core/Lib/Widget/RowFooter.php, Core/Lib/Widget/RowStatistics.php, Core/Lib/Widget/RowStatus.php, Core/Lib/Widget/VisualItem.php, Core/Lib/Widget/WidgetAutocomplete.php, Core/Lib/Widget/WidgetCheckbox.php, Core/Lib/Widget/WidgetPassword.php, Core/Lib/Widget/WidgetRadio.php, Core/Lib/Widget/WidgetSelect.php, Core/Lib/Widget/WidgetTextarea.php
=> Eliminada la clase Translator de los widgets

Core/Lib/AjaxForms/PurchasesFooterHTML.php, Core/Lib/AjaxForms/PurchasesHeaderHTML.php, Core/Lib/AjaxForms/PurchasesLineHTML.php, Core/Lib/AjaxForms/PurchasesModalHTML.php, Core/Lib/AjaxForms/SalesFooterHTML.php, Core/Lib/AjaxForms/SalesHeaderHTML.php, Core/Lib/AjaxForms/SalesLineHTML.php, Core/Lib/AjaxForms/SalesModalHTML.php
=> Corregidas columnas botones documentos bootstrap 5

Core/Base/Utils.php, Core/Lib/ListFilter/BaseFilter.php, Core/Lib/Widget/WidgetLink.php, Core/Tools.php, Test/Core/Model/AttachedFileTest.php, Test/Core/Model/CiudadTest.php, Test/Core/Model/CuentaEspecialTest.php, Test/Core/Model/DivisaTest.php, Test/Core/Model/FabricanteTest.php, Test/Core/Model/FamiliaTest.php, Test/Core/Model/ProvinciaTest.php
Marcada como deprecated la clase utils
=> Deprecated utils

Core/Base/Controller.php, Core/Contract/PurchasesLineModInterface.php, Core/Contract/PurchasesModInterface.php, Core/Contract/SalesLineModInterface.php, Core/Contract/SalesModInterface.php, Core/Lib/AjaxForms/AccountingFooterHTML.php, Core/Lib/AjaxForms/AccountingHeaderHTML.php, Core/Lib/AjaxForms/AccountingLineHTML.php, Core/Lib/AjaxForms/AccountingModalHTML.php, Core/Lib/AjaxForms/CommonLineHTML.php, Core/Lib/AjaxForms/CommonSalesPurchases.php, Core/Lib/AjaxForms/PurchasesController.php, Core/Lib/AjaxForms/PurchasesFooterHTML.php, Core/Lib/AjaxForms/PurchasesHeaderHTML.php, Core/Lib/AjaxForms/PurchasesLineHTML.php, Core/Lib/AjaxForms/PurchasesModalHTML.php, Core/Lib/AjaxForms/SalesController.php, Core/Lib/AjaxForms/SalesFooterHTML.php, Core/Lib/AjaxForms/SalesHeaderHTML.php, Core/Lib/AjaxForms/SalesLineHTML.php, Core/Lib/AjaxForms/SalesModalHTML.php, Core/Model/Base/PurchaseDocument.php, Core/Session.php
Los ajaxForms no estaban correctamente movidos a la carpeta lib.
=> Correcciones a los ajaxForms

Core/Lib/Email/NewMail.php, Core/Response.php, Core/UploadedFile.php
Ahora al enviar un email se comprueba si se alcanzo el límite por hora, además se añadieron funciones a las clases Response y UploadFile para su compatibilidad.
=> Limitar envío de email y cambios en response y uploadFile

Core/Lib/OpenAi.php
Añadida opción de obtener el hilo de openAI.
=> Añadida opción para leer el hilo de openAI

Core/Lib/OpenAi.php
Nueva funciones necesarias para la clase openAI
=> cambios en la clase openai

Core/Lib/OpenAi.php
=> añadida url del asistente

Core/Controller/Login.php, Core/Request.php
- Se ha refactorizado Login.php
- Se ha agregado un método en Request.php para refactorizar Login.php
=> Refactorización a Core/Controller/Login.php

Core/Lib/Vies.php
Se han realizado mejoras en la clase `Vies` para facilitar su uso en pruebas unitarias y mejorar la legibilidad del código.
1. Se ha agregado la capacidad de simular respuestas del servicio VIES para pruebas unitarias:
- Nuevo método `simulateViesResponse()` que permite simular diferentes resultados
- Se pueden simular tres tipos de respuestas: válido, inválido y error
2. Se han introducido constantes descriptivas para los resultados:
- `RESULT_VALID = 1`
- `RESULT_INVALID = 0`
- `RESULT_ERROR = -1`
3. Se ha optimizado la lógica de simulación:
- La comprobación de respuesta simulada se realiza al inicio del método `check()`
- Se evitan validaciones innecesarias cuando se usa una respuesta simulada
```php
// Simular número de IVA válido
Vies::simulateViesResponse(Vies::RESULT_VALID);
// …
```
=> agregar respuesta simulada a Vies para usar en tests

Core/Controller/Login.php
- Tras el pull anterior debido a no testear no me he percatado de que había una función mal formada o con argumentos incorrectos. Esta pull es un parche para ese error.
- Se han modificado todas las existencias de esa función para evitar el error.
=> fix: bug de Request nulo

Core/Controller/EditContacto.php, Core/Controller/EditProducto.php, Core/Lib/ExtendedController/ComercialContactController.php
- Al usar el Trait DocFilesTrait es necesario definir la propiedad $logLevels
=> agregar $logLevels al usar DocFilesTrait

Core/Controller/Login.php
- No existe la propiedad $user y no se usa en el resto del controlador Login.
=> asignacion no necesaria

Core/Controller/EditUser.php
=> cambiar id por nick

Core/Controller/ApiCreateFacturaCliente.php, Core/Controller/ApiExportFacturaCliente.php, Core/Lib/API/Base/APIResourceClass.php, Core/Template/ApiController.php
-  Actualizar métodos obsoletos en api
=> actualizar metodos obsoletos en api

Core/DbQuery.php, Test/Core/DbQueryTest.php
Tarea #3501 - add maxString and minString
=> Tarea #3501 - add maxString and minString

Core/Controller/ApiCreateFacturaRectificativaCliente.php, Core/Controller/ApiRoot.php, Core/Kernel.php
Tarea #3851 add end point crear factura rectificativa
https://github.com/elguitarraverde/facturascripts/tree/Tarea-%233851---end-point-crear-factura-rectificativa
@NeoRazorX ya tienes los cambios en la rama master.
=> Tarea #3851 add end point crear factura rectificativa

.scrutinizer.yml
- actualizar la versión de php
=> Update php version .scrutinizer.yml

composer.json, package.json
- actualizar descripcion con bootstrap 5
=> actualizar descripcion con bootstrap 5

Core/Data/Codpais/DOM/defaultPlan.csv, Core/Data/Codpais/DOM/impuestos.csv
- Se actualizaron las cuentas contables de DOM para el manejo de los impuestos en compras y ventas
- Se actualiza el archivo impuestos.csv de DOM agregando los campos codsubcuentarep y codsubcuentasop
- Updated defaultPlan.csv for DOM data
- Updated impuestos.csv for DOM data
=> Updated defaultPlan.csv and impuestos.csv

Core/Model/Base/BusinessDocument.php
=> Añadido user como dependencia necesaria en BussinesDocument

Core/Lib/ExtendedController/ProductImagesTrait.php, Core/UploadedFile.php
=> Añadido comprobar que tenga barra al final la carpeta

Core/Assets/JS/WidgetSelect.js, Core/Lib/Widget/WidgetSelect.php, package.json
- actualizar tema select2 para usar con bootstrap5
=> actualizar tema select2 para usar con bootstrap5

Core/Model/Tarifa.php
En ocasiones desde un plugin queremos modificar el comportamiento de la función apply() del modelo Tarifa pero sin hacer herencia.
=> Añadido pipe para el modelo Tarifa en su función apply

Core/Lib/Accounting/InvoiceToAccounting.php
Use the AccountingClass base class from Dinamic to facilitate inheritance from plugins. This helps you customize invoice accounting without having to override entire methods, avoiding code duplication and making maintenance easier.
=> Use AccountingClass from Dinamic

Core/Controller/EditProducto.php, Core/Controller/ListCliente.php, Core/Lib/Widget/WidgetDatalist.php, Core/Lib/Widget/WidgetSelect.php, Core/Model/AtributoValor.php, Core/Model/Base/ModelClass.php, Core/Model/Variante.php
- Describe los cambios que has hecho en el código.
- No incluyas diferentes funcionalidades en un mismo PR, es decir, si cambias el listado de usuarios, no modifiques también la impresión en PDF.
- Funcionalidades distintas deben ir en pull requests separados.
- No modifiques las traducciones. Las traducciones se gestionan desde https://facturascripts.com/traducciones/
- Borra estas líneas, son solo para que las leas.
- No es necesario que escribas esto en inglés si ya lo escribes en español.
- (Discord) …
=> Reemplaza ALL_LIMIT por getLimit en CodeModel

Core/UploadedFile.php
Necesario para poder validar los test de Ticketbai.
=> Add test mode to UploadedFile for easier file handling during development
